### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by MaxLaMenace10280** [joBr99/nspanel-lovelace-ui#1017]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/121713411/b3283eb5-91a5-47a4-84c1-da82df806703)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/121713411/62d97627-f6e1-437a-a9c1-53bebaf4931f)


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/121713411/d094082a-cf06-4711-b6a3-8736f3c3b8b2)


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.14.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.1
 Home Assistant Supervisor: 2023.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting babel
  Downloading Babel-2.13.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 35.8 MB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.13.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[19:01:09] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-11-09 19:01:14.859194 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-11-09 19:01:14.860237 INFO AppDaemon: Python version is 3.11.6
2023-11-09 19:01:14.860541 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-11-09 19:01:14.860777 INFO AppDaemon: Added log: AppDaemon
2023-11-09 19:01:14.861251 INFO AppDaemon: Added log: Error
2023-11-09 19:01:14.861744 INFO AppDaemon: Added log: Access
2023-11-09 19:01:14.862155 INFO AppDaemon: Added log: Diag
2023-11-09 19:01:15.171399 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-11-09 19:01:15.502275 INFO HASS: HASS Plugin Initializing
2023-11-09 19:01:15.502747 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2023-11-09 19:01:15.503072 INFO HASS: HASS Plugin initialization complete
2023-11-09 19:01:15.503385 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-11-09 19:01:15.621378 INFO MQTT: MQTT Plugin Initializing
2023-11-09 19:01:15.621992 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-11-09 19:01:15.622374 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-11-09 19:01:15.623349 INFO AppDaemon: Initializing HTTP
2023-11-09 19:01:15.623876 INFO AppDaemon: Using 'ws' for event stream
2023-11-09 19:01:15.630013 INFO AppDaemon: Starting API
2023-11-09 19:01:15.633358 INFO AppDaemon: Starting Admin Interface
2023-11-09 19:01:15.634054 INFO AppDaemon: Starting Dashboards
2023-11-09 19:01:15.669746 INFO HASS: Connected to Home Assistant 2023.11.1
2023-11-09 19:01:15.716467 INFO MQTT: Connected to Broker at URL core-mosquitto.local.hass.io:1883
2023-11-09 19:01:15.741298 INFO AppDaemon: Got initial state from namespace mqtt
2023-11-09 19:01:15.746867 INFO MQTT: MQTT Plugin initialization complete
2023-11-09 19:01:15.810464 INFO HASS: Evaluating startup conditions
2023-11-09 19:01:15.825965 INFO AppDaemon: App 'nspanel-1' added
2023-11-09 19:01:15.828607 INFO AppDaemon: Found 1 active apps
2023-11-09 19:01:15.829668 INFO AppDaemon: Found 0 inactive apps
2023-11-09 19:01:15.830939 INFO AppDaemon: Found 0 global libraries
2023-11-09 19:01:15.832230 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-11-09 19:01:15.833909 INFO AppDaemon: Running on port 5050
2023-11-09 19:01:15.836028 INFO HASS: Startup condition met: hass state=RUNNING
2023-11-09 19:01:15.838608 INFO HASS: All startup conditions met
2023-11-09 19:01:15.865570 INFO AppDaemon: Got initial state from namespace default
2023-11-09 19:01:17.865060 INFO AppDaemon: Scheduler running in realtime
2023-11-09 19:01:17.881367 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-11-09 19:01:17.882582 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-11-09 19:01:17.883785 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-11-09 19:01:17.885264 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-11-09 19:01:17.891820 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-11-09 19:01:17.894543 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-11-09 19:01:17.913672 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2023-11-09 19:01:17.915529 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-11-09 19:01:18.173257 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-11-09 19:01:18.175822 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-11-09 19:01:18.177420 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-11-09 19:01:18.179443 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-11-09 19:01:18.180859 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-11-09 19:01:18.182512 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-11-09 19:01:18.184507 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-11-09 19:01:18.186197 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-11-09 19:01:18.187500 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-11-09 19:01:18.188231 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-11-09 19:01:18.188858 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-11-09 19:01:18.189461 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-11-09 19:01:18.191338 INFO AppDaemon: Calling initialize() for nspanel-1
2023-11-09 19:01:18.306277 INFO nspanel-1: Starting
2023-11-09 19:01:18.314040 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanel_entree/RESULT', 'panelSendTopic': 'cmnd/nspanel_entree/CustomSend', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'locale': 'fr_FR', 'cards': [{'type': 'cardEntities', 'title': 'Volets AV', 'entities': [{'entity': 'cover.salle_de_bain_mrs100_main_channel'}, {'entity': 'cover.volet_bureau_mrs100_main_channel'}, {'entity': 'cover.volet_cuisine_mrs100_main_channel'}]}, {'type': 'cardEntities', 'title': 'Volets ARR', 'entities': [{'entity': 'cover.smart_roller_shutter_timer_mrs100_main_channel'}, {'entity': 'cover.volet_baie_sam_mrs100_main_channel'}, {'entity': 'cover.volet_chambre_mrs100_main_channel'}, {'entity': 'cover.volet_salle_a_manger_mrs100_main_channel'}]}]}
2023-11-09 19:01:18.316253 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanel_entree/RESULT', 'panelSendTopic': 'cmnd/nspanel_entree/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'fr_FR', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'title': 'Volets AV', 'entities': [{'entity': 'cover.salle_de_bain_mrs100_main_channel'}, {'entity': 'cover.volet_bureau_mrs100_main_channel'}, {'entity': 'cover.volet_cuisine_mrs100_main_channel'}]}, {'type': 'cardEntities', 'title': 'Volets ARR', 'entities': [{'entity': 'cover.smart_roller_shutter_timer_mrs100_main_channel'}, {'entity': 'cover.volet_baie_sam_mrs100_main_channel'}, {'entity': 'cover.volet_chambre_mrs100_main_channel'}, {'entity': 'cover.volet_salle_a_manger_mrs100_main_channel'}]}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-11-09 19:01:18.324585 INFO nspanel-1: Sending MQTT Message: pageType~pageStartup
2023-11-09 19:01:18.340820 INFO nspanel-1: Registering callbacks for the following items: ['cover.salle_de_bain_mrs100_main_channel', 'cover.volet_bureau_mrs100_main_channel', 'cover.volet_cuisine_mrs100_main_channel', 'cover.smart_roller_shutter_timer_mrs100_main_channel', 'cover.volet_baie_sam_mrs100_main_channel', 'cover.volet_chambre_mrs100_main_channel', 'cover.volet_salle_a_manger_mrs100_main_channel', 'weather.example']
2023-11-09 19:01:18.359094 INFO nspanel-1: Started (v4.0.3)
2023-11-09 19:01:18.362135 INFO AppDaemon: App initialization complete
2023-11-09 19:02:00.369039 INFO nspanel-1: Sending MQTT Message: time~19:02~

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
I don't see any configuration problem, but my NSPanel remains stuck on "Waiting for content"
my home assistant server is installed on a virtual computer

help me please :)

**Comment by joBr99** [comment]
Please restart tasmota and share logs from tasmota console.

**Comment by MaxLaMenace10280** [comment]
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/121713411/2856b588-8683-4350-8d9c-4833d654f120)

**Comment by joBr99** [comment]
There's your problem - Tasmota isn't able to connect to your mqtt server. The log of your mqtt server might provide addional context.

Note that the mqtt password on tasmota needs to be at least 5 chars long.

**Comment by MaxLaMenace10280** [comment]
Yes ok, but I have a password of 6 characters (6 digits)

**Comment by joBr99** [comment]
failed to connect also sounds more like you are using the wrong ip address in your config on tasmota

**Comment by MaxLaMenace10280** [comment]
to your avios, I must put the IP address of the HA server or that of MQTT on my tasmota?
![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/121713411/a4dbe82d-5f4f-4e8b-bf36-69afb16a9a02)

**Comment by joBr99** [comment]
yes that should be correct - please check the logs of your mosquitto addon

**Comment by MaxLaMenace10280** [comment]
2023-11-09 18:40:45: New connection from 172.30.32.2:33542 on port 1883.
2023-11-09 18:40:45: Client <unknown> closed its connection.
2023-11-09 18:42:45: New connection from 172.30.32.2:56884 on port 1883.
2023-11-09 18:42:45: Client <unknown> closed its connection.
2023-11-09 18:43:02: New connection from 172.30.33.3:49997 on port 1883.
2023-11-09 18:43:02: New client connected from 172.30.33.3:49997 as appdaemon (p2, c1, k60, u'mqtt_user').
2023-11-09 18:44:45: New connection from 172.30.32.2:43886 on port 1883.
2023-11-09 18:44:45: Client <unknown> closed its connection.
2023-11-09 18:46:45: New connection from 172.30.32.2:53300 on port 1883.
2023-11-09 18:46:45: Client <unknown> closed its connection.
2023-11-09 18:48:45: New connection from 172.30.32.2:56260 on port 1883.
2023-11-09 18:48:45: Client <unknown> closed its connection.
2023-11-09 18:50:45: New connection from 172.30.32.2:48262 on port 1883.
2023-11-09 18:50:45: Client <unknown> closed its connection.
2023-11-09 18:52:45: New connection from 172.30.32.2:49124 on port 1883.
2023-11-09 18:52:45: Client <unknown> closed its connection.
2023-11-09 18:54:45: New connection from 172.30.32.2:46064 on port 1883.
2023-11-09 18:54:45: Client <unknown> closed its connection.
2023-11-09 18:56:45: New connection from 172.30.32.2:40986 on port 1883.
2023-11-09 18:56:45: Client <unknown> closed its connection.
2023-11-09 18:58:45: New connection from 172.30.32.2:59710 on port 1883.
2023-11-09 18:58:45: Client <unknown> closed its connection.
2023-11-09 19:00:02: Saving in-memory database to /data//mosquitto.db.
2023-11-09 19:00:45: New connection from 172.30.32.2:34924 on port 1883.
2023-11-09 19:00:45: Client <unknown> closed its connection.
2023-11-09 19:00:48: Client appdaemon disconnected.
2023-11-09 19:01:15: New connection from 172.30.33.3:43619 on port 1883.
2023-11-09 19:01:15: New client connected from 172.30.33.3:43619 as appdaemon (p2, c1, k60, u'mqtt_user').
2023-11-09 19:02:45: New connection from 172.30.32.2:49906 on port 1883.
2023-11-09 19:02:45: Client <unknown> closed its connection.
2023-11-09 19:04:45: New connection from 172.30.32.2:55588 on port 1883.
2023-11-09 19:04:45: Client <unknown> closed its connection.
2023-11-09 19:06:45: New connection from 172.30.32.2:38914 on port 1883.
2023-11-09 19:06:45: Client <unknown> closed its connection.
2023-11-09 19:08:45: New connection from 172.30.32.2:54864 on port 1883.
2023-11-09 19:08:45: Client <unknown> closed its connection.
2023-11-09 19:10:45: New connection from 172.30.32.2:37400 on port 1883.
2023-11-09 19:10:45: Client <unknown> closed its connection.
2023-11-09 19:12:45: New connection from 172.30.32.2:34472 on port 1883.
2023-11-09 19:12:45: Client <unknown> closed its connection.
2023-11-09 19:14:45: New connection from 172.30.32.2:45226 on port 1883.
2023-11-09 19:14:45: Client <unknown> closed its connection.
2023-11-09 19:16:45: New connection from 172.30.32.2:51472 on port 1883.
2023-11-09 19:16:45: Client <unknown> closed its connection.
2023-11-09 19:18:45: New connection from 172.30.32.2:58432 on port 1883.
2023-11-09 19:18:45: Client <unknown> closed its connection.
2023-11-09 19:20:45: New connection from 172.30.32.2:32932 on port 1883.
2023-11-09 19:20:45: Client <unknown> closed its connection.
2023-11-09 19:22:45: New connection from 172.30.32.2:53986 on port 1883.
2023-11-09 19:22:45: Client <unknown> closed its connection.
2023-11-09 19:24:45: New connection from 172.30.32.2:55088 on port 1883.
2023-11-09 19:24:45: Client <unknown> closed its connection.
2023-11-09 19:26:45: New connection from 172.30.32.2:44310 on port 1883.
2023-11-09 19:26:45: Client <unknown> closed its connection.
2023-11-09 19:28:45: New connection from 172.30.32.2:32986 on port 1883.
2023-11-09 19:28:45: Client <unknown> closed its connection.
2023-11-09 19:29:09: Client appdaemon disconnected.
2023-11-09 19:29:37: New connection from 172.30.33.3:40581 on port 1883.
2023-11-09 19:29:37: Client appdaemon disconnected, not authorised.
2023-11-09 19:29:38: New connection from 172.30.33.3:58887 on port 1883.
2023-11-09 19:29:38: Client appdaemon disconnected, not authorised.
2023-11-09 19:29:40: New connection from 172.30.33.3:41747 on port 1883.
2023-11-09 19:29:40: Client appdaemon disconnected, not authorised.
2023-11-09 19:29:44: New connection from 172.30.33.3:44435 on port 1883.
2023-11-09 19:29:44: Client appdaemon disconnected, not authorised.
2023-11-09 19:29:52: New connection from 172.30.33.3:55383 on port 1883.
2023-11-09 19:29:52: Client appdaemon disconnected, not authorised.
2023-11-09 19:30:03: Saving in-memory database to /data//mosquitto.db.
2023-11-09 19:30:08: New connection from 172.30.33.3:47921 on port 1883.
2023-11-09 19:30:08: Client appdaemon disconnected, not authorised.
2023-11-09 19:30:24: New connection from 172.30.33.3:47137 on port 1883.
2023-11-09 19:30:24: Client appdaemon disconnected, not authorised.
2023-11-09 19:30:39: New connection from 172.30.33.3:37145 on port 1883.
2023-11-09 19:30:39: Client appdaemon disconnected, not authorised.
2023-11-09 19:30:45: New connection from 172.30.32.2:42562 on port 1883.
2023-11-09 19:30:45: Client <unknown> closed its connection.
2023-11-09 19:30:55: New connection from 172.30.33.3:59607 on port 1883.
2023-11-09 19:30:55: Client appdaemon disconnected, not authorised.
2023-11-09 19:31:11: New connection from 172.30.33.3:33309 on port 1883.
2023-11-09 19:31:11: Client appdaemon disconnected, not authorised.
2023-11-09 19:31:27: New connection from 172.30.33.3:60111 on port 1883.
2023-11-09 19:31:27: Client appdaemon disconnected, not authorised.
2023-11-09 19:31:42: New connection from 172.30.33.3:48667 on port 1883.
2023-11-09 19:31:42: Client appdaemon disconnected, not authorised.
2023-11-09 19:31:58: New connection from 172.30.33.3:59545 on port 1883.
2023-11-09 19:31:58: Client appdaemon disconnected, not authorised.
2023-11-09 19:32:15: New connection from 172.30.33.3:50143 on port 1883.
2023-11-09 19:32:15: Client appdaemon disconnected, not authorised.
2023-11-09 19:32:31: New connection from 172.30.33.3:44173 on port 1883.
2023-11-09 19:32:31: Client appdaemon disconnected, not authorised.
2023-11-09 19:32:45: New connection from 172.30.32.2:43682 on port 1883.
2023-11-09 19:32:45: Client <unknown> closed its connection.
2023-11-09 19:33:00: New connection from 172.30.33.3:60299 on port 1883.
2023-11-09 19:33:00: New client connected from 172.30.33.3:60299 as appdaemon (p2, c1, k60, u'mqtt_user').
2023-11-09 19:34:45: New connection from 172.30.32.2:45610 on port 1883.
2023-11-09 19:34:45: Client <unknown> closed its connection.
2023-11-09 19:36:45: New connection from 172.30.32.2:53910 on port 1883.
2023-11-09 19:36:45: Client <unknown> closed its connection.
2023-11-09 19:38:45: New connection from 172.30.32.2:38072 on port 1883.
2023-11-09 19:38:45: Client <unknown> closed its connection.

**Comment by joBr99** [comment]
This part of the log doesn't have any connection attempt from your tasmota device.

**Comment by MaxLaMenace10280** [comment]
yes, that's what I have trouble understanding

**Comment by joBr99** [comment]
you can enable more verbose logging on tasmota with the command `WebLog 4`

**Comment by joBr99** [comment]
there's nothing related to mqtt on this screenshot, restart your device - stuff related to mqtt start's with "xx MQT:"

**Comment by joBr99** [comment]
yeah doesn't provide more inforamtion; please try changing "client" in the tasmota config to something different ("nsp_entree" or so)

**Comment by MaxLaMenace10280** [comment]
I tried to change the password; the name.... but nothing changes :(

**Comment by joBr99** [comment]
Where is your VM installed? Do you have a firewall in between blocking port 1883?

**Comment by MaxLaMenace10280** [comment]
It is installed on a mini PC dedicated to a home assistant. I don't think I have a firewall or anything else because my nspanel already worked with this configuration. one day there was a power outage, and since then the nspanel has not been able to reconnect. despite attempts to reset. I will continue the investigation tomorrow, because my head is going to explode😅

**Comment by joBr99** [comment]
you wrote above that your ha is installed on a virtual computer

**Comment by MaxLaMenace10280** [comment]
yes, virtual PC software on my mini PC (this is one of the ways I found to have home assistant)

**Comment by JGnasaki** [comment]
Hi. I have also this Problem. But I use ESPHome.  MQTT schould be correct (I hope...). Hier ist a part of the AppDaemon-Log:

2023-11-11 16:02:45.953465 INFO AppDaemon: Calling initialize() for nspanel-1
2023-11-11 16:02:45.956659 INFO nspanel-1: Starting
2023-11-11 16:02:45.958885 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-11-11 16:02:45.962506 INFO nspanel-1: Input config: {'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend', 'model': 'eu'}
2023-11-11 16:02:45.965808 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'featureExperimentalSliders': False, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': [], 'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend'}
2023-11-11 16:02:45.972112 WARNING nspanel-1: ------------------------------------------------------------
2023-11-11 16:02:45.973202 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-11-11 16:02:45.974302 WARNING nspanel-1: ------------------------------------------------------------
2023-11-11 16:02:45.977047 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'

2023-11-11 16:02:45.978888 WARNING nspanel-1: ------------------------------------------------------------

**Comment by joBr99** [comment]
No you don't have the same issue, please open your own issue with the requested information.

**Comment by MaxLaMenace10280** [comment]
Hey @joBr99  🙂 I still have the problem. I didn't find the solution, I tried to reinstall all the apps on HA but still the same

**Comment by joBr99** [comment]
without any further information there's nothing I can help you with

Did you try to connect to the mqtt server from a different device? (using mqtt explorer for example)

**Comment by MaxLaMenace10280** [comment]
I am new to this field I do not know how to do . there is only the ns panel which is on mqtt for the moment
