### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by JGnasaki** [joBr99/nspanel-lovelace-ui#1021]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

ESPHome, not Tasmota:

substitutions:
  devicename: nspanel-az-keller
  friendly_devicename: nspanel-az-keller
  panel_recv_topic: "tele/nspanel-az-keller/RESULT"
  panel_send_topic: "cmnd/nspanel-az-keller/CustomSend"

esphome:
  name: $devicename

esp32:
  board: esp32dev

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
MQTT:
  type: mqtt
  namespace: mqtt
  client_id: "appdaemon"
  #client_host: core-mosquitto.local.hass.io
  client_host: 192.168.178.240
  client_port: 1883
  client_user: "mqtt-user"
  client_password: "the-mqtt-PW"
  client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
spanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panel_recv_topic: "tele/nspanel-az-keller/RESULT"
    panel_send_topic: "cmnd/nspanel-az-keller/CustomSend"
    model: "eu"


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
2023-11-11 16:02:45.953465 INFO AppDaemon: Calling initialize() for nspanel-1
2023-11-11 16:02:45.956659 INFO nspanel-1: Starting
2023-11-11 16:02:45.958885 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-11-11 16:02:45.962506 INFO nspanel-1: Input config: {'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend', 'model': 'eu'}
2023-11-11 16:02:45.965808 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'featureExperimentalSliders': False, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': [], 'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend'}
2023-11-11 16:02:45.972112 WARNING nspanel-1: ------------------------------------------------------------
2023-11-11 16:02:45.973202 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-11-11 16:02:45.974302 WARNING nspanel-1: ------------------------------------------------------------
2023-11-11 16:02:45.977047 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'

2023-11-11 16:02:45.978888 WARNING nspanel-1: ------------------------------------------------------------

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_
 
Installation on Rasp4

**Comment by joBr99** [comment]
The indentation of your appdaemon config is wrong:

```
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io
      client_host: 192.168.178.240
      client_port: 1883
      client_user: "mqtt-user"
      client_password: "the-mqtt-PW"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

MQTT needs to be on the same level as HASS

**Comment by JGnasaki** [comment]
OK thanks. The error in the log is gone, but it still comes:
Waiting for Content.

2023-11-11 16:37:51.823242 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-11-11 16:37:51.831164 INFO AppDaemon: Calling initialize() for nspanel-1
2023-11-11 16:37:51.840805 INFO nspanel-1: Starting
2023-11-11 16:37:51.847028 INFO nspanel-1: Input config: {'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend', 'updateMode': 'auto-notify', 'locale': 'de_DE', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '6:00:00', 'value': 8}, {'time': '23:00:00', 'value': 2}], 'screensaver': {'entity': 'sensor.schuppen_temperature'}, 'cards': [{'type': 'cardGrid', 'title': 'Test', 'entities': [{'entity': 'sensor.thermostat_hwr_batterie', 'name': 'HWR Batterie'}]}]}
2023-11-11 16:37:51.850511 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '6:00:00', 'value': 8}, {'time': '23:00:00', 'value': 2}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'featureExperimentalSliders': False, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'de_DE', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardGrid', 'title': 'Test', 'entities': [{'entity': 'sensor.thermostat_hwr_batterie', 'name': 'HWR Batterie'}]}], 'screensaver': {'type': 'screensaver', 'entity': 'sensor.schuppen_temperature', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': [], 'panel_recv_topic': 'tele/nspanel-az-keller/RESULT', 'panel_send_topic': 'cmnd/nspanel-az-keller/CustomSend'}
2023-11-11 16:37:51.861294 INFO nspanel-1: Sending MQTT Message: pageType~pageStartup
2023-11-11 16:37:51.897556 INFO nspanel-1: gtest123: ['sensor.thermostat_hwr_batterie', 'sensor.schuppen_temperature']
2023-11-11 16:37:51.901706 INFO nspanel-1: Registering callbacks for the following items: ['sensor.thermostat_hwr_batterie', 'sensor.schuppen_temperature']
2023-11-11 16:37:51.917268 INFO MQTT: Topic tele/tasmota_your_mqtt_topic/RESULT already subscribed to
2023-11-11 16:37:51.929242 INFO nspanel-1: Started (v4.3.1)

with this apps.yaml:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panel_recv_topic: "tele/nspanel-az-keller/RESULT"
    panel_send_topic: "cmnd/nspanel-az-keller/CustomSend"
    updateMode: "auto-notify"
    locale: "de_DE"
    model: "eu"
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:00:00"
        value: 8
      - time: "23:00:00"
        value: 2
    screensaver:
      entity: sensor.schuppen_temperature
    cards:
      - type: cardGrid
        title: Test
        entities:
          - entity: sensor.thermostat_hwr_batterie
            name: HWR Batterie

**Comment by joBr99** [comment]
You are not using the correct config variables for the send/recive topics.

```
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel-az-keller/RESULT"
    panelSendTopic: "cmnd/nspanel-az-keller/CustomSend"
    updateMode: "auto-notify"
    locale: "de_DE"
    model: "eu"
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:00:00"
        value: 8
      - time: "23:00:00"
        value: 2
    screensaver:
      entity: sensor.schuppen_temperature
    cards:
      - type: cardGrid
        title: Test
        entities:
          - entity: sensor.thermostat_hwr_batterie
            name: HWR Batterie
```

**Comment by JGnasaki** [comment]
Good morning and thank you. Now I have content on the device. 
Best regards Jörg
