### ISSUE TITLE
[BUG] Screen blanks / app crashes when screen is touched.

### ISSUE THREAD

**Issue by athanas** [joBr99/nspanel-lovelace-ui#1060]
### PROBLEM DESCRIPTION

I recently upgraded HA to the latest, and upgraded all HACS devices/entities.  After doing so, my NSPANEL became unresponsive to a touch.  The screen would blank, and the application would restart on the NSPANEL.  The error in the logs:

```
2023-11-21 18:27:14.582211 WARNING nspanel2: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/conf/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 229, in button_press
    self._pages_gen.render_card(self._current_card)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 719, in render_card
    self.generate_entities_page(navigation, card.title, card.entities, card.cardType, temp_unit)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 408, in generate_entities_page
    command += self.generate_entities_item(item, cardType, tempUnit)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 250, in generate_entities_item
    color = self.get_entity_color(entity, ha_type=entityType, overwrite=colorOverride)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 105, in get_entity_color
    color = rgb_brightness([253, 216, 53], attr.brightness)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/helper.py", line 34, in rgb_brightness
    brightness = int(scale(brightness,(0,255),(70,255)))
  File "/conf/apps/nspanel-lovelace-ui/luibackend/helper.py", line 9, in scale
    return ((val - src[0]) / (src[1]-src[0])) * (dst[1]-dst[0]) + dst[0]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

```
Digging into the code, the argument ‘val’ in luibackend/helper.py—>scale() was passed in as None as per the stack trace above.  If I caught this and set ‘val’ to a nominal value, the panel returns to full functionality.

BTW, this is a great project.  You’ve done a wonderful job with it.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:

---
hello_world:
  module: hello
  class: HelloWorld
##############################################
### Addition NSPANEL
##############################################
nspanel1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    number.nspanel1_page_timeout: 3
    panelRecvTopic: "tele/nspanel1/RESULT"
    panelSendTopic: "cmnd/nspanel1/CustomSend"
    featureExperimentalSliders: True
    model: us-p
    timeFormat: "%I:%M ?%p"
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:30:00"
        value: 2
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
       entity: weather.kbcb_daynight
    cards:
       #      - type: cardEntities
       # entities:
       #   - entity: switch.media_light
       #   - entity: light.addition_stage_light
       # title: Example X
      - type: cardGrid
        entities:
          - entity: light.addition_front_light
          - entity: light.addition_stage_light
          - entity: light.bookcase_light
          - entity: switch.media_light_3
            icon: mdi:wall-sconce-round
          - entity: switch.shop_light
            icon: mdi:hammer-wrench
          - entity: switch.fan
            icon: mdi:fan
        title: Addition Lights
      - type: cardMedia
        entity: media_player.volumio
        title: Music Player
        entities:
          - entity: switch.livingroom_speakers
            icon: mdi:volume-low
            name: LR
          - entity: switch.addition_speakers_3
            icon: mdi:volume-low
          - entity: delete
          - entity: switch.media_light_3
            icon: mdi:wall-sconce-round

##############################################
### Entryway NSPANEL
##############################################
nspanel2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    number.nspanel2_page_timeout: 3
    panelRecvTopic: "tele/nspanel2/RESULT"
    panelSendTopic: "cmnd/nspanel2/CustomSend"
    featureExperimentalSliders: True
    model: us-p
    timeFormat: "%I:%M ?%p"
    sleepTimeout: 20
    sleepBrightness:
      - time: "6:30:00"
        value: 6
      - time: "23:00:00"
        value: 0
    locale: "en_US"
    screensaver:
       entity: weather.kbcb_daynight
    cards:
      - type: cardGrid
        entities:
          - entity: light.livingroom_ceiling_mss570x_main_channel_3
          - entity: light.kitchen_ceiling_mss570x_main_channel_4
            icon: mdi:wall-sconce-round
          - entity: light.floor_lamp
          - entity: light.dining_room
            icon: mdi:table-picnic
          - entity: switch.under_bed_light
            icon: mdi:bed
          - entity: light.bedroom_1
        title: Lighting
      - type: cardMedia
        entity: media_player.volumio
        title: Music Player
        entities:
          - entity: switch.livingroom_speakers
            icon: mdi:volume-low
            name: LR
          - entity: switch.addition_speakers_3
            icon: mdi:volume-low
          - entity: delete
          - entity: switch.media_light_3
            icon: mdi:wall-sconce-round

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by randybb** [comment]
update your panels. version v4.3.3 is needed to support HA 2023.11.x

**Comment by athanas** [comment]
Hello Roman,
I did  a

FlashNextion
http://nspanel.pky.eu/lovelace-ui/github/nspanel-us-p-v4.3.3.tft

on each panel.  Thank you for the super speedy response.
-Peter

**Comment by joBr99** [comment]
You need to update the appdaemon app and restart appdaemon afterwards. Flashing the TFT Firmware is not required.

**Comment by theknut** [comment]
I'm still having this issue. I'm not even using HA, I'm using ioBroker. Every time I touch the screen it blanks / restarts. I have to `FlashNextion http://nspanel.pky.eu/lovelace-ui/github/nspanel-v4.3.3.tft` to make it work. Once I restart the ioBroker script it blanks / crashes upon touching. I always have to flash in order to make it work again.

**Comment by joBr99** [comment]
This is something diff

**Comment by theknut** [comment]
Can you please link me to the post? The ioBroker forum pagination is insane
and the search won't help either.

Johannes ***@***.***> schrieb am Do., 23. Nov. 2023, 23:32:

**Comment by joBr99** [comment]
https://forum.iobroker.net/topic/58170/sonoff-nspanel-mit-lovelace-ui
