### ISSUE TITLE
[BUG] Card grid breaks when there is a light on it

### ISSUE THREAD

**Issue by JasperHorn** [joBr99/nspanel-lovelace-ui#1063]
### PROBLEM DESCRIPTION
My card page has been completely empty (also lacking the navigation to the other cards) for a few weeks now. Probably since I installed the latest update. This stops happening when I remove the light from my card page. Having either an IKEA Tradfri bulb or a light entity group (the only two light types I have to test with) breaks the page, having a non-existent light entity does not.

(Personally, I wasn't actually using the panel to control these lights, so I'm fine just removing them from the page, but it makes sense to report it anyway)

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
nspanel_living_room:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel-living-room/RESULT"
    panelSendTopic: "cmnd/nspanel-living-room/CustomSend"
    locale: "nl_NL"
    model: "eu"
    cards:
      - type: cardGrid
        entities:
          - entity: light.ikea_of_sweden_tradfri_bulb_e27_cws_806lm_light
```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-11-23 13:33:43.657254 WARNING nspanel_living_room: ------------------------------------------------------------
2023-11-23 13:33:43.663124 WARNING nspanel_living_room: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/apps/nspanel-lovelace-ui/luibackend/controller.py", line 228, in button_press
    self._pages_gen.render_card(self._current_card)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 717, in render_card
    self.generate_entities_page(navigation, card.title, card.entities, card.cardType, temp_unit)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 408, in generate_entities_page
    command += self.generate_entities_item(item, cardType, tempUnit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 250, in generate_entities_item
    color = self.get_entity_color(entity, ha_type=entityType, overwrite=colorOverride)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 102, in get_entity_color
    color = rgb_brightness(color, attr.brightness)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/helper.py", line 34, in rgb_brightness
    brightness = int(scale(brightness,(0,255),(70,255)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/helper.py", line 9, in scale
    return ((val - src[0]) / (src[1]-src[0])) * (dst[1]-dst[0]) + dst[0]
             ~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

2023-11-23 13:33:43.663910 WARNING nspanel_living_room: ------------------------------------------------------------

```

### TO REPRODUCE
Put a light on a card grid card.

### EXPECTED BEHAVIOUR
Have the card work and have the light entity on it.

### SCREENSHOTS
Will add a photo later.

### ADDITIONAL CONTEXT
Using ESPHome.

### PANEL / FIRMWARE VERION
EU

**Comment by JasperHorn** [comment]
Never mind, additional restarting fixed the problem (I had gotten distracted while making the issues, and only realized afterwards that I had intended to restart AppDeamon after uploading the firmware manually).

Interestingly, it also fixed the problem for the second panel, which I hadn't done the extra upload of the firmware for. My AppDeamon had been crashing earlier, so I had started it again after fixing that, and I had assumed that was as no worse than a restart. Perhaps that assumption was wrong. Or perhaps something else happened, I don't really know. Either way, the problem disappeared for me...

**Comment by joBr99** [comment]
See #1036.

There was an Backend Update for Home Assistant 2023.11, fixing this issue with the light entities. No TFT Upgrade required only the backend & a AppDaemon Restart.

**Comment by JasperHorn** [comment]
Yeah, I don't know why starting AppDaemon (that wasn't running) wasn't enough, but the extra restart was. But it does work now.

Thanks for the quick response!

**Comment by JasperHorn** [comment]
It seems that the problem wasn't entirely solved. When I do a restart, it works but it seems that a day later the problems are back. I will do some more investigating and reopen the issue when I have.
