### ISSUE TITLE
Problems with FORECASTER

### ISSUE THREAD

**Issue by freitas666** [joBr99/nspanel-lovelace-ui#1079]
### PROBLEM DESCRIPTION

After last update, my weather stop to show in screen... all others work just weather not...

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
  
  nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPAINEL/RESULT"
    panelSendTopic: "cmnd/NSPAINEL/CustomSend"
    updateMode: "auto-notify"
#    timeFormat: "%I:%M ?%p"
    dateFormatBabel: "E d MMM yyyy"
    model: us-p
    sleepTimeout: 20 
    sleepBrightness:
      - time: "sunrise"
        value: 100
      - time: "sunset"
        value: 10
    sleepOverride:
      entity: switch.nspainel
      brightness: 100
    locale: "pt_BR"
    screensaver:
      doubleTapToUnlock: True
      entity: weather.pirateweather
      theme: !include /homeassistant/appdaemon/screensaver-theme-include/screensaver-theme.yaml
      defaultCard: temp
    cards:
      - type: cardThermo
        title: Ar Condicionado
        entity: climate.ar_condicionado


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2023-12-03 12:35:06.951781 INFO AppDaemon: Added log: AppDaemon
2023-12-03 12:35:06.951880 INFO AppDaemon: Added log: Error
2023-12-03 12:35:06.951962 INFO AppDaemon: Added log: Access
2023-12-03 12:35:06.952043 INFO AppDaemon: Added log: Diag
2023-12-03 12:35:07.085233 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-12-03 12:35:07.218173 INFO HASS: HASS Plugin Initializing
2023-12-03 12:35:07.218292 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2023-12-03 12:35:07.218394 INFO HASS: HASS Plugin initialization complete
2023-12-03 12:35:07.218547 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-12-03 12:35:07.268833 INFO MQTT: MQTT Plugin Initializing
2023-12-03 12:35:07.268963 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-12-03 12:35:07.269081 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-12-03 12:35:07.269378 INFO AppDaemon: Initializing HTTP
2023-12-03 12:35:07.269565 INFO AppDaemon: Using 'ws' for event stream
2023-12-03 12:35:07.271743 INFO AppDaemon: Starting API
2023-12-03 12:35:07.273388 INFO AppDaemon: Starting Admin Interface
2023-12-03 12:35:07.273628 INFO AppDaemon: Starting Dashboards
2023-12-03 12:35:07.284074 INFO HASS: Connected to Home Assistant 2023.11.3
2023-12-03 12:35:07.326757 INFO AppDaemon: App 'nspanel-1' added
2023-12-03 12:35:07.327269 INFO AppDaemon: Found 1 active apps
2023-12-03 12:35:07.327430 INFO AppDaemon: Found 0 inactive apps
2023-12-03 12:35:07.327866 INFO AppDaemon: Found 0 global libraries
2023-12-03 12:35:07.328011 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-12-03 12:35:07.328581 INFO AppDaemon: Running on port 5050
2023-12-03 12:35:07.368035 INFO HASS: Evaluating startup conditions
2023-12-03 12:35:07.375017 INFO HASS: Startup condition met: hass state=RUNNING
2023-12-03 12:35:07.375592 INFO HASS: All startup conditions met
2023-12-03 12:35:07.422394 INFO AppDaemon: Got initial state from namespace default
2023-12-03 12:35:07.461582 INFO MQTT: Connected to Broker at URL 192.168.2.46:1883
2023-12-03 12:35:07.736114 INFO AppDaemon: Got initial state from namespace mqtt
2023-12-03 12:35:07.737607 INFO MQTT: MQTT Plugin initialization complete
2023-12-03 12:35:09.333633 INFO AppDaemon: Scheduler running in realtime
2023-12-03 12:35:09.338082 INFO AppDaemon: Adding /homeassistant/appdaemon/apps to module import path
2023-12-03 12:35:09.338686 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-12-03 12:35:09.339265 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-12-03 12:35:09.339809 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-12-03 12:35:09.340382 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-12-03 12:35:09.341021 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-12-03 12:35:09.341555 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/config-check to module import path
2023-12-03 12:35:09.350617 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/hello.py - ignoring
2023-12-03 12:35:09.351654 INFO AppDaemon: Loading App Module: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-12-03 12:35:09.500229 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-12-03 12:35:09.500878 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-12-03 12:35:09.501530 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-12-03 12:35:09.501997 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-12-03 12:35:09.502466 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-12-03 12:35:09.502937 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-12-03 12:35:09.503510 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-12-03 12:35:09.504095 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-12-03 12:35:09.504597 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-12-03 12:35:09.505127 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-12-03 12:35:09.505643 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-12-03 12:35:09.506139 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/config-check/checkconfig.py - ignoring
2023-12-03 12:35:09.506583 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-12-03 12:35:09.508012 INFO AppDaemon: Calling initialize() for nspanel-1
2023-12-03 12:35:09.551690 INFO nspanel-1: Starting
2023-12-03 12:35:09.555211 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/NSPAINEL/RESULT', 'panelSendTopic': 'cmnd/NSPAINEL/CustomSend', 'updateMode': 'auto-notify', 'dateFormatBabel': 'E d MMM yyyy', 'model': 'us-p', 'sleepTimeout': 20, 'sleepBrightness': [{'time': 'sunrise', 'value': 100}, {'time': 'sunset', 'value': 10}], 'sleepOverride': {'entity': 'switch.nspainel', 'brightness': 100}, 'locale': 'pt_BR', 'screensaver': {'doubleTapToUnlock': True, 'entity': 'weather.pirateweather', 'theme': None, 'defaultCard': 'temp'}, 'cards': [{'type': 'cardThermo', 'title': 'Ar Condicionado', 'entity': 'climate.ar_condicionado'}, {'type': 'cardPower', 'title': 'Consumo', 'entities': [{'entity': 'sensor.total_casa_mes', 'icon': 'mdi:calendar-month'}, {'entity': 'delete'}, {'entity': 'sensor.total_casa_semana', 'icon': 'mdi:numeric-7-box', 'speed': -20}, {'entity': 'delete'}, {'entity': 'sensor.total_casa_dia', 'icon': 'mdi:numeric-1-box', 'speed': 20}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_maquina_de_lavar', 'icon': 'mdi:washing-machine', 'speed': 20}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_chuveiro_office', 'icon': 'mdi:shower-head'}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_office', 'icon': 'phu:rooms-computer'}, {'entity': 'delete'}]}, {'type': 'cardMedia', 'entity': 'media_player.spotify_leo_de_freitas', 'title': 'Música', 'icon': 'mdi:spotify'}, {'type': 'cardEntities', 'entities': [{'entity': 'light.fita_led_bancada', 'name': 'Mesa'}, {'entity': 'light.fita_led_mesa', 'name': 'Mesa'}, {'entity': 'light.abajur_office', 'name': 'Led'}, {'entity': 'light.estante', 'name': 'Estante'}, {'entity': 'switch.office_l1', 'name': 'Escritório'}], 'title': 'Office'}, {'type': 'cardEntities', 'title': 'Persianas', 'entities': [{'entity': 'cover.persiana_do_quarto', 'name': 'Quarto'}, {'entity': 'cover.persiana_da_sala', 'name': 'Sala'}, {'entity': 'cover.persiana_do_escritorio', 'name': 'Escritório'}, {'entity': 'cover.cortina_cozinha', 'name': 'Cozinha'}, {'entity': 'cover.toldo_curtain', 'name': 'Toldo'}]}, {'type': 'cardGrid', 'title': 'Luzes1', 'entities': [{'entity': 'switch.sacada', 'name': 'Sacada'}, {'entity': 'switch.trilho', 'name': 'Trilho'}, {'entity': 'switch.cabeceira', 'name': 'Cabeceira'}, {'entity': 'switch.cozinha', 'name': 'Cozinha'}, {'entity': 'switch.mesa_de_jantar', 'name': 'Mesa'}]}, {'type': 'cardGrid', 'title': 'Luzes2', 'entities': [{'entity': 'light.painel', 'name': 'Painel'}, {'entity': 'switch.garagem', 'name': 'Garagem'}, {'entity': 'switch.entrada', 'name': 'Hall'}, {'entity': 'switch.suite_1', 'name': 'Banheiro'}, {'entity': 'switch.interruptor_lavabo_l1', 'name': 'Lavabo'}, {'entity': 'light.abajur_sala', 'name': 'Abajur Sala'}, {'entity': 'light.abajur_office', 'name': 'Abajur Office'}, {'entity': 'switch.lavanderia', 'name': 'Lavanderia'}]}]}
2023-12-03 12:35:09.556218 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/NSPAINEL/RESULT', 'panelSendTopic': 'cmnd/NSPAINEL/CustomSend', 'updateMode': 'auto-notify', 'model': 'us-p', 'sleepTimeout': 20, 'sleepBrightness': [{'time': 'sunrise', 'value': 100}, {'time': 'sunset', 'value': 10}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'featureExperimentalSliders': False, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': {'entity': 'switch.nspainel', 'brightness': 100}, 'locale': 'pt_BR', 'timeFormat': '%H:%M', 'dateFormatBabel': 'E d MMM yyyy', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardThermo', 'title': 'Ar Condicionado', 'entity': 'climate.ar_condicionado'}, {'type': 'cardPower', 'title': 'Consumo', 'entities': [{'entity': 'sensor.total_casa_mes', 'icon': 'mdi:calendar-month'}, {'entity': 'delete'}, {'entity': 'sensor.total_casa_semana', 'icon': 'mdi:numeric-7-box', 'speed': -20}, {'entity': 'delete'}, {'entity': 'sensor.total_casa_dia', 'icon': 'mdi:numeric-1-box', 'speed': 20}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_maquina_de_lavar', 'icon': 'mdi:washing-machine', 'speed': 20}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_chuveiro_office', 'icon': 'mdi:shower-head'}, {'entity': 'delete'}, {'entity': 'sensor.energia_gasta_dia_office', 'icon': 'phu:rooms-computer'}, {'entity': 'delete'}]}, {'type': 'cardMedia', 'entity': 'media_player.spotify_leo_de_freitas', 'title': 'Música', 'icon': 'mdi:spotify'}, {'type': 'cardEntities', 'entities': [{'entity': 'light.fita_led_bancada', 'name': 'Mesa'}, {'entity': 'light.fita_led_mesa', 'name': 'Mesa'}, {'entity': 'light.abajur_office', 'name': 'Led'}, {'entity': 'light.estante', 'name': 'Estante'}, {'entity': 'switch.office_l1', 'name': 'Escritório'}], 'title': 'Office'}, {'type': 'cardEntities', 'title': 'Persianas', 'entities': [{'entity': 'cover.persiana_do_quarto', 'name': 'Quarto'}, {'entity': 'cover.persiana_da_sala', 'name': 'Sala'}, {'entity': 'cover.persiana_do_escritorio', 'name': 'Escritório'}, {'entity': 'cover.cortina_cozinha', 'name': 'Cozinha'}, {'entity': 'cover.toldo_curtain', 'name': 'Toldo'}]}, {'type': 'cardGrid', 'title': 'Luzes1', 'entities': [{'entity': 'switch.sacada', 'name': 'Sacada'}, {'entity': 'switch.trilho', 'name': 'Trilho'}, {'entity': 'switch.cabeceira', 'name': 'Cabeceira'}, {'entity': 'switch.cozinha', 'name': 'Cozinha'}, {'entity': 'switch.mesa_de_jantar', 'name': 'Mesa'}]}, {'type': 'cardGrid', 'title': 'Luzes2', 'entities': [{'entity': 'light.painel', 'name': 'Painel'}, {'entity': 'switch.garagem', 'name': 'Garagem'}, {'entity': 'switch.entrada', 'name': 'Hall'}, {'entity': 'switch.suite_1', 'name': 'Banheiro'}, {'entity': 'switch.interruptor_lavabo_l1', 'name': 'Lavabo'}, {'entity': 'light.abajur_sala', 'name': 'Abajur Sala'}, {'entity': 'light.abajur_office', 'name': 'Abajur Office'}, {'entity': 'switch.lavanderia', 'name': 'Lavanderia'}]}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.pirateweather', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': True, 'alternativeLayout': False, 'defaultCard': 'temp', 'key': 'screensaver', 'theme': None}, 'hiddenCards': []}
2023-12-03 12:35:09.560896 INFO nspanel-1: Sending MQTT Message: pageType~pageStartup
2023-12-03 12:35:09.568598 INFO nspanel-1: Configuring Sleep Override. Config is {'entity': 'switch.nspainel', 'brightness': 100}
2023-12-03 12:35:09.570695 INFO nspanel-1: gtest123: ['climate.ar_condicionado', 'sensor.total_casa_mes', 'delete', 'sensor.total_casa_semana', 'delete', 'sensor.total_casa_dia', 'delete', 'sensor.energia_gasta_dia_maquina_de_lavar', 'delete', 'sensor.energia_gasta_dia_chuveiro_office', 'delete', 'sensor.energia_gasta_dia_office', 'delete', 'media_player.spotify_leo_de_freitas', 'light.fita_led_bancada', 'light.fita_led_mesa', 'light.abajur_office', 'light.estante', 'switch.office_l1', 'cover.persiana_do_quarto', 'cover.persiana_da_sala', 'cover.persiana_do_escritorio', 'cover.cortina_cozinha', 'cover.toldo_curtain', 'switch.sacada', 'switch.trilho', 'switch.cabeceira', 'switch.cozinha', 'switch.mesa_de_jantar', 'light.painel', 'switch.garagem', 'switch.entrada', 'switch.suite_1', 'switch.interruptor_lavabo_l1', 'light.abajur_sala', 'light.abajur_office', 'switch.lavanderia', 'weather.pirateweather']
2023-12-03 12:35:09.571995 INFO nspanel-1: Registering callbacks for the following items: ['climate.ar_condicionado', 'sensor.total_casa_mes', 'sensor.total_casa_semana', 'sensor.total_casa_dia', 'sensor.energia_gasta_dia_maquina_de_lavar', 'sensor.energia_gasta_dia_chuveiro_office', 'sensor.energia_gasta_dia_office', 'media_player.spotify_leo_de_freitas', 'light.fita_led_bancada', 'light.fita_led_mesa', 'light.abajur_office', 'light.estante', 'switch.office_l1', 'cover.persiana_do_quarto', 'cover.persiana_da_sala', 'cover.persiana_do_escritorio', 'cover.cortina_cozinha', 'cover.toldo_curtain', 'switch.sacada', 'switch.trilho', 'switch.cabeceira', 'switch.cozinha', 'switch.mesa_de_jantar', 'light.painel', 'switch.garagem', 'switch.entrada', 'switch.suite_1', 'switch.interruptor_lavabo_l1', 'light.abajur_sala', 'light.abajur_office', 'switch.lavanderia', 'weather.pirateweather']
2023-12-03 12:35:09.591809 INFO nspanel-1: Started (v4.3.1)
2023-12-03 12:35:09.592796 INFO AppDaemon: App initialization complete
2023-12-03 12:35:09.737780 INFO nspanel-1: MQTT callback for: {'topic': 'tele/NSPAINEL/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"8"}'}
2023-12-03 12:35:09.739515 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: 8 Panel Version: None
2023-12-03 12:35:10.196242 INFO nspanel-1: MQTT callback for: {'topic': 'tele/NSPAINEL/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,us-p"}'}
2023-12-03 12:35:10.197973 INFO nspanel-1: Received Message from Screen: event,startup,53,us-p
2023-12-03 12:35:10.199590 INFO nspanel-1: Sending MQTT Message: X
2023-12-03 12:35:10.202945 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 53
2023-12-03 12:35:10.204036 INFO nspanel-1: Startup Event
2023-12-03 12:35:10.214890 INFO nspanel-1: Sending MQTT Message: time~12:35~
2023-12-03 12:35:10.249809 INFO nspanel-1: Sending MQTT Message: date~dom. 3 dez. 2023
2023-12-03 12:35:10.253176 INFO nspanel-1: Sending MQTT Message: dimmode~99~100~6371~~0
2023-12-03 12:35:10.255497 INFO nspanel-1: Sending MQTT Message: pageType~screensaver
2023-12-03 12:35:10.257644 INFO nspanel-1: Sending MQTT Message: timeout~20
2023-12-03 12:35:10.264612 WARNING nspanel-1: ------------------------------------------------------------
2023-12-03 12:35:10.264857 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2023-12-03 12:35:10.265022 WARNING nspanel-1: Worker Ags: {'id': '00679025bf904cbc995203c584c5eb6f', 'name': 'nspanel-1', 'objectid': 'bed76f6be3ab4b93a7623a76fa510d47', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f970b1b5a10>>, 'data': {'topic': 'tele/NSPAINEL/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,us-p"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/NSPAINEL/RESULT', '__thread_id': 'thread-0'}}
2023-12-03 12:35:10.265190 WARNING nspanel-1: ------------------------------------------------------------
2023-12-03 12:35:10.267021 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 40, in mqtt_event_callback
    self._controller.startup()
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 40, in startup
    self._pages_gen.render_card(self._current_card)
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 764, in render_card
    self.update_screensaver_weather(theme)
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 145, in update_screensaver_weather
    item_str += self.generate_entities_item(item, "cardEntities", mask=["type", "entityId"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 375, in generate_entities_item
    if type(item.stype) == int and len(entity.attributes.forecast) >= item.stype:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AttrDict' object has no attribute 'forecast'

2023-12-03 12:35:10.267268 WARNING nspanel-1: ------------------------------------------------------------
2023-12-03 12:35:10.290424 INFO nspanel-1: MQTT callback for: {'topic': 'tele/NSPAINEL/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"8"}'}
2023-12-03 12:35:10.291703 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 8 Panel Version: 53

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
Hey, this is not fixable in the AppDaemon Backend, as AppDaemon doesn't support service calls with a result.

See #1001

This is already fixed in the upcoming backend that is no longer based on AppDaemon. #1058

You can try the new backend or use a weather integration that is still providing the forecast as an attribute on the entity itself.
