### ISSUE TITLE
Waiting for content

### ISSUE THREAD

**Issue by ladousek** [joBr99/nspanel-lovelace-ui#112]
Hello, I am sorry that open this ticket but after update my NSPanel is still waiting for content. I tried to make all flash again but not successful. Could I ask for ideas? I am really dont know what reason could be.

![image](https://user-images.githubusercontent.com/51122310/161382625-163d2cbc-98bf-4807-b47f-e67f01af6763.png)
![image](https://user-images.githubusercontent.com/51122310/161382644-af409049-a9f9-419b-a661-deef313348ec.png)
![image](https://user-images.githubusercontent.com/51122310/161382663-1da8e9a4-f544-44ef-a43e-d660b918a962.png)
![image](https://user-images.githubusercontent.com/51122310/161382691-8779ed63-7f33-4267-bee8-695a34701854.png)
![image](https://user-images.githubusercontent.com/51122310/161382780-8e0e4799-4b3a-48cf-96c7-7bbde36f96b0.png)

Thank you for support. 
Ladislav

**Comment by joBr99** [comment]
Hey, 
please have a look into the log of appdaemon and post the log's from there.

![image](https://user-images.githubusercontent.com/29555657/161383142-35f77ebe-a9a5-45ad-98f4-e5e102f1ed95.png)

**Comment by ladousek** [comment]
2022-04-02 14:05:42.021720 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:05:42.023606 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-04-02 14:05:42.025777 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:05:42.044523 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 63, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-04-02 14:05:42.046608 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:12:37.911756 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:12:37 +0000] "GET / HTTP/1.1" 302 191 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:12:38.653820 INFO AppDaemon: New client Admin Client connected
2022-04-02 14:17:50.754478 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:17:55.780625 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:00.808143 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:05.828570 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:10.847758 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:15.867763 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:20.888337 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:25.932632 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:33.951420 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:39.196357 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:44.258226 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:49.435970 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:54.539398 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:18:59.572363 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:19:04.613168 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-04-02 14:19:12.743418 INFO HASS: Connected to Home Assistant 2022.3.8
2022-04-02 14:19:32.713456 WARNING AppDaemon: Excessive time spent in utility loop: 23136.0ms, 23135.0ms in check_app_updates(), 1.0ms in other
2022-04-02 14:19:33.616034 INFO HASS: Evaluating startup conditions
2022-04-02 14:19:33.721712 INFO HASS: Startup condition met: hass state=RUNNING
2022-04-02 14:19:33.724086 INFO HASS: All startup conditions met
2022-04-02 14:19:33.905242 INFO AppDaemon: Processing restart for HASS
2022-04-02 14:19:33.907590 INFO AppDaemon: Terminating nspanel-1
2022-04-02 14:19:33.914242 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-04-02 14:19:33.949213 INFO nspanel-1: Starting
2022-04-02 14:19:33.952706 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2022-04-02 14:19:33.964202 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nsp_novy/RESULT', 'panelSendTopic': 'cmnd/nsp_novy/CustomSend', 'timeoutScreensaver': 20, 'brightnessScreensaver': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'locale': 'de_DE', 'dateFormatBabel': 'full', 'timeFormat': '%H:%M', 'dateFormat': '%A, %d. %B %Y', 'weather': 'weather.example', 'pages': [{'type': 'cardEntities', 'heading': 'Example Page 1', 'items': ['cover.example_cover', 'switch.example_switch', 'input_boolean.example_input_boolean', 'sensor.example_sensor']}, {'type': 'cardEntities', 'heading': 'Example Page 2', 'items': ['button.example_button', 'input_button.example_input_button', 'light.light_example', 'delete']}, {'type': 'cardEntities', 'heading': 'Example Page 3', 'items': ['scene.example_scene', 'delete', 'delete', 'delete']}, {'type': 'cardGrid', 'heading': 'Example Page 4', 'items': ['light.light_example', 'button.example_button', 'cover.example_cover', 'scene.example_scene', 'switch.example_switch', 'delete']}, {'type': 'cardThermo', 'heading': 'Exmaple Thermostat', 'item': 'climate.example_climate'}, {'type': 'cardMedia', 'item': 'media_player.spotify_user'}, {'type': 'cardAlarm', 'item': 'alarm_control_panel.alarmo'}]}
2022-04-02 14:19:33.974196 INFO nspanel-1: Parsed Page config to the following Tree: 
 None:internal_root -> root 
 |- 0:cardEntities_Example_Page_1 -> internal_root 
     |- 0:cover_example_cover -> cardEntities_Example_Page_1 
     |- 1:switch_example_switch -> cardEntities_Example_Page_1 
     |- 2:input_boolean_example_input_boolean -> cardEntities_Example_Page_1 
     |- 3:sensor_example_sensor -> cardEntities_Example_Page_1 
 |- 1:cardEntities_Example_Page_2 -> internal_root 
     |- 0:button_example_button -> cardEntities_Example_Page_2 
     |- 1:input_button_example_input_button -> cardEntities_Example_Page_2 
     |- 2:light_light_example -> cardEntities_Example_Page_2 
     |- 3:delete -> cardEntities_Example_Page_2 
 |- 2:cardEntities_Example_Page_3 -> internal_root 
     |- 0:scene_example_scene -> cardEntities_Example_Page_3 
     |- 1:delete -> cardEntities_Example_Page_3 
     |- 2:delete -> cardEntities_Example_Page_3 
     |- 3:delete -> cardEntities_Example_Page_3 
 |- 3:cardGrid_Example_Page_4 -> internal_root 
     |- 0:light_light_example -> cardGrid_Example_Page_4 
     |- 1:button_example_button -> cardGrid_Example_Page_4 
     |- 2:cover_example_cover -> cardGrid_Example_Page_4 
     |- 3:scene_example_scene -> cardGrid_Example_Page_4 
     |- 4:switch_example_switch -> cardGrid_Example_Page_4 
     |- 5:delete -> cardGrid_Example_Page_4 
 |- 4:cardThermo_Exmaple_Thermostat -> internal_root 
 |- 5:cardMedia_unkown -> internal_root 
 |- 6:cardAlarm_unkown -> internal_root 
2022-04-02 14:19:33.982513 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:19:33.984475 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-04-02 14:19:33.985991 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:19:33.989425 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 63, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-04-02 14:19:33.992053 WARNING nspanel-1: ------------------------------------------------------------
2022-04-02 14:20:13.871171 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:20:13 +0000] "GET /aui/index.html HTTP/1.1" 304 176 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:20:13.881989 INFO AppDaemon: Client disconnected unexpectedly from Admin Client
2022-04-02 14:20:13.895721 INFO AppDaemon: Client disconnection from Admin Client
2022-04-02 14:20:14.384057 INFO AppDaemon: New client Admin Client connected
2022-04-02 14:20:14.534457 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:20:14 +0000] "GET /aui/favicon.ico HTTP/1.1" 200 252 "http://homeassistant:5050/aui/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:20:46.115363 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:20:46 +0000] "GET /aui/index.html HTTP/1.1" 304 176 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:20:46.122399 INFO AppDaemon: Client disconnection from Admin Client
2022-04-02 14:20:46.604520 INFO AppDaemon: New client Admin Client connected
2022-04-02 14:21:27.306656 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:21:27 +0000] "GET /aui/index.html HTTP/1.1" 304 176 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:21:27.313055 INFO AppDaemon: Client disconnection from Admin Client
2022-04-02 14:21:27.836000 INFO AppDaemon: New client Admin Client connected
2022-04-02 14:22:08.155889 INFO nspanel-1: 192.168.68.118 [02/Apr/2022:12:22:08 +0000] "GET /aui/index.html HTTP/1.1" 304 176 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
2022-04-02 14:22:08.162361 INFO AppDaemon: Client disconnection from Admin Client
2022-04-02 14:22:08.643169 INFO AppDaemon: New client Admin Client connected

**Comment by joBr99** [comment]
`AttributeError: 'NoneType' object has no attribute 'mqtt_publish'`

indicates that's something wrong with your mqtt configuration in appdaemon, take a look at the logs of your mqtt broker, maybe that's helpful

**Comment by ladousek** [comment]
All another sonnofs works, also zigbee2mqtt.

**Mosquitto broker:**
1648899945: Opening ipv4 listen socket on port 1883.
1648899945: Opening ipv6 listen socket on port 1883.
1648899945: Opening websockets listen socket on port 1884.
1648899945: Warning: Mosquitto should not be run as root/administrator.
1648899945: mosquitto version 1.6.12 running
1648899945: New connection from 127.0.0.1 on port 1883.
1648899945: Socket error on client <unknown>, disconnecting.
1648899968: New connection from 192.168.68.106 on port 1883.
1648899968: New client connected from 192.168.68.106 as sonoff_104 (p2, c1, k30, u'mqtt_lada').
1648899974: New connection from 192.168.68.105 on port 1883.
1648899974: New client connected from 192.168.68.105 as sonoff_102 (p2, c1, k30, u'mqtt_lada').
1648899975: New connection from 192.168.68.102 on port 1883.
1648899975: New client connected from 192.168.68.102 as sonoff_105 (p2, c1, k30, u'mqtt_lada').
1648899976: New connection from 192.168.68.103 on port 1883.
1648899976: New client connected from 192.168.68.103 as sonoff_103 (p2, c1, k30, u'mqtt_lada').
1648899976: New connection from 192.168.68.104 on port 1883.
1648899976: New client connected from 192.168.68.104 as sonoff_kuchyne_lustr (p2, c1, k30, u'mqtt_lada').
1648899982: New connection from 192.168.68.107 on port 1883.
1648899982: New client connected from 192.168.68.107 as sonoff_101 (p2, c1, k30, u'mqtt_lada').
1648899994: New connection from 172.30.32.1 on port 1883.
1648899994: New client connected from 172.30.32.1 as 5DsIxJP29Bpy9n6z63V8ie (p2, c1, k60, u'mqtt_lada').
1648899994: New connection from 172.30.32.1 on port 1883.
1648899994: New client connected from 172.30.32.1 as auto-A58E417D-9D92-2CC1-9BE9-B345AC9A91EC (p2, c1, k60).
1648900105: New connection from 172.30.32.1 on port 1883.
1648900105: New client connected from 172.30.32.1 as mqttjs_c0a6accd (p2, c1, k60, u'mqtt_lada').
1648900188: New connection from 172.30.32.2 on port 1883.
1648900188: Socket error on client <unknown>, disconnecting.
1648900308: New connection from 172.30.32.2 on port 1883.
1648900308: Socket error on client <unknown>, disconnecting.
1648900345: Socket error on client auto-A58E417D-9D92-2CC1-9BE9-B345AC9A91EC, disconnecting.
1648900351: Socket error on client 5DsIxJP29Bpy9n6z63V8ie, disconnecting.
1648900389: New connection from 172.30.32.1 on port 1883.
1648900389: New client connected from 172.30.32.1 as 39YfxyC4Pusc7e2JIgbV9o (p2, c1, k60, u'mqtt_lada').
1648900389: New connection from 172.30.32.1 on port 1883.
1648900389: New client connected from 172.30.32.1 as auto-7DBB6D1F-470C-C6A7-FDDF-9B6C8905A67F (p2, c1, k60).
1648900428: New connection from 172.30.32.2 on port 1883.
1648900428: Socket error on client <unknown>, disconnecting.
1648900548: New connection from 172.30.32.2 on port 1883.
1648900548: Socket error on client <unknown>, disconnecting.
1648900668: New connection from 172.30.32.2 on port 1883.
1648900668: Socket error on client <unknown>, disconnecting.
1648900715: New connection from 192.168.68.124 on port 1883.
1648900715: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648900750: Socket error on client NSPanelNovy, disconnecting.
1648900757: New connection from 192.168.68.124 on port 1883.
1648900757: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648900788: New connection from 172.30.32.2 on port 1883.
1648900788: Socket error on client <unknown>, disconnecting.
1648900789: Socket error on client NSPanelNovy, disconnecting.
1648900796: New connection from 192.168.68.124 on port 1883.
1648900796: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648900891: Socket error on client NSPanelNovy, disconnecting.
1648900897: New connection from 192.168.68.124 on port 1883.
1648900897: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648900908: New connection from 172.30.32.2 on port 1883.
1648900908: Socket error on client <unknown>, disconnecting.
1648900921: Socket error on client NSPanelNovy, disconnecting.
1648900928: New connection from 192.168.68.124 on port 1883.
1648900928: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648900995: New connection from 192.168.68.124 on port 1883.
1648900995: Client NSPanelNovy already connected, closing old connection.
1648900995: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648901028: New connection from 172.30.32.2 on port 1883.
1648901028: Socket error on client <unknown>, disconnecting.
1648901148: New connection from 172.30.32.2 on port 1883.
1648901148: Socket error on client <unknown>, disconnecting.
1648901268: New connection from 172.30.32.2 on port 1883.
1648901268: Socket error on client <unknown>, disconnecting.
1648901388: New connection from 172.30.32.2 on port 1883.
1648901388: Socket error on client <unknown>, disconnecting.
1648901508: New connection from 172.30.32.2 on port 1883.
1648901508: Socket error on client <unknown>, disconnecting.
1648901628: New connection from 172.30.32.2 on port 1883.
1648901628: Socket error on client <unknown>, disconnecting.
1648901746: Saving in-memory database to /data/mosquitto.db.
1648901748: New connection from 172.30.32.2 on port 1883.
1648901748: Socket error on client <unknown>, disconnecting.
1648901847: Socket error on client NSPanelNovy, disconnecting.
1648901855: New connection from 192.168.68.124 on port 1883.
1648901855: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648901868: New connection from 172.30.32.2 on port 1883.
1648901868: Socket error on client <unknown>, disconnecting.
1648901870: Socket error on client auto-7DBB6D1F-470C-C6A7-FDDF-9B6C8905A67F, disconnecting.
1648901876: Socket error on client 39YfxyC4Pusc7e2JIgbV9o, disconnecting.
1648901913: New connection from 172.30.32.1 on port 1883.
1648901913: New client connected from 172.30.32.1 as 4zMPpjMGcXYanUKvbyAM3k (p2, c1, k60, u'mqtt_lada').
1648901915: New connection from 172.30.32.1 on port 1883.
1648901915: New client connected from 172.30.32.1 as auto-DC0773CD-ABA0-74F2-FEB1-8C541AD0B162 (p2, c1, k60).
1648901928: Socket error on client NSPanelNovy, disconnecting.
1648901938: New connection from 192.168.68.124 on port 1883.
1648901938: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648901982: Client mqttjs_c0a6accd disconnected.
1648901988: New connection from 172.30.32.2 on port 1883.
1648901988: Socket error on client <unknown>, disconnecting.
1648902025: New connection from 172.30.32.1 on port 1883.
1648902025: New client connected from 172.30.32.1 as mqttjs_77f1c72a (p2, c1, k60, u'mqtt_lada').
1648902074: Socket error on client NSPanelNovy, disconnecting.
1648902080: New connection from 192.168.68.124 on port 1883.
1648902080: New client connected from 192.168.68.124 as NSPanelNovy (p2, c1, k30, u'mqtt_lada').
1648902108: New connection from 172.30.32.2 on port 1883.

**Comment by joBr99** [comment]
Cannot see a request from AppDaemon there, can you send the logs that is appdaemon producing right after restarting it?

**Comment by ladousek** [comment]
**AppDaemon** after restart
Installing collected packages: babel
Successfully installed babel-2.9.1
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:40:12] INFO: Starting AppDaemon...
2022-04-02 14:40:15.964407 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-04-02 14:40:15.965111 INFO AppDaemon: Python version is 3.9.7
2022-04-02 14:40:15.965791 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-04-02 14:40:15.966558 INFO AppDaemon: Added log: AppDaemon
2022-04-02 14:40:15.967335 INFO AppDaemon: Added log: Error
2022-04-02 14:40:15.968153 INFO AppDaemon: Added log: Access
2022-04-02 14:40:15.968953 INFO AppDaemon: Added log: Diag
2022-04-02 14:40:16.054068 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-04-02 14:40:16.202084 INFO HASS: HASS Plugin Initializing
2022-04-02 14:40:16.202902 INFO HASS: HASS Plugin initialization complete
2022-04-02 14:40:16.204040 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-04-02 14:40:16.231264 INFO MQTT: MQTT Plugin Initializing
2022-04-02 14:40:16.232099 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-04-02 14:40:16.232887 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-04-02 14:40:16.235292 INFO AppDaemon: Initializing HTTP
2022-04-02 14:40:16.236948 INFO AppDaemon: Using 'ws' for event stream
2022-04-02 14:40:16.251197 INFO AppDaemon: Starting API
2022-04-02 14:40:16.266366 INFO AppDaemon: Starting Admin Interface
2022-04-02 14:40:16.268156 INFO AppDaemon: Starting Dashboards
2022-04-02 14:40:16.341182 INFO HASS: Connected to Home Assistant 2022.3.8
2022-04-02 14:40:16.353077 INFO MQTT: Connected to Broker at URL 192.168.68.129:1883
2022-04-02 14:40:16.367174 INFO AppDaemon: Got initial state from namespace mqtt
2022-04-02 14:40:16.369143 INFO MQTT: MQTT Plugin initialization complete
2022-04-02 14:40:16.475821 INFO AppDaemon: App 'nspanel-1' added
2022-04-02 14:40:16.480455 INFO AppDaemon: Found 1 total apps
2022-04-02 14:40:16.483221 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2022-04-02 14:40:16.486766 INFO AppDaemon: Running on port 5050
2022-04-02 14:40:16.712988 INFO HASS: Evaluating startup conditions
2022-04-02 14:40:16.748577 INFO HASS: Startup condition met: hass state=RUNNING
2022-04-02 14:40:16.750483 INFO HASS: All startup conditions met
2022-04-02 14:40:16.859962 INFO AppDaemon: Got initial state from namespace default
2022-04-02 14:40:18.517193 INFO AppDaemon: Scheduler running in realtime
2022-04-02 14:40:18.531702 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-04-02 14:40:18.534016 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2022-04-02 14:40:18.535931 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2022-04-02 14:40:18.568817 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2022-04-02 14:40:18.573037 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2022-04-02 14:40:18.665956 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2022-04-02 14:40:18.670405 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2022-04-02 14:40:18.674287 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2022-04-02 14:40:18.678049 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2022-04-02 14:40:18.682473 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2022-04-02 14:40:18.687017 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py - ignoring
2022-04-02 14:40:18.691587 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2022-04-02 14:40:18.695661 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2022-04-02 14:40:18.700947 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2022-04-02 14:40:18.704391 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-04-02 14:40:19.059423 INFO nspanel-1: Starting
2022-04-02 14:40:19.077191 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nsp_novy/RESULT', 'panelSendTopic': 'cmnd/nsp_novy/CustomSend', 'timeoutScreensaver': 20, 'brightnessScreensaver': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'locale': 'de_DE', 'dateFormatBabel': 'full', 'timeFormat': '%H:%M', 'dateFormat': '%A, %d. %B %Y', 'weather': 'weather.example', 'pages': [{'type': 'cardEntities', 'heading': 'Example Page 1', 'items': ['cover.example_cover', 'switch.example_switch', 'input_boolean.example_input_boolean', 'sensor.example_sensor']}, {'type': 'cardEntities', 'heading': 'Example Page 2', 'items': ['button.example_button', 'input_button.example_input_button', 'light.light_example', 'delete']}, {'type': 'cardEntities', 'heading': 'Example Page 3', 'items': ['scene.example_scene', 'delete', 'delete', 'delete']}, {'type': 'cardGrid', 'heading': 'Example Page 4', 'items': ['light.light_example', 'button.example_button', 'cover.example_cover', 'scene.example_scene', 'switch.example_switch', 'delete']}, {'type': 'cardThermo', 'heading': 'Exmaple Thermostat', 'item': 'climate.example_climate'}, {'type': 'cardMedia', 'item': 'media_player.spotify_user'}, {'type': 'cardAlarm', 'item': 'alarm_control_panel.alarmo'}]}
2022-04-02 14:40:19.085462 INFO nspanel-1: Parsed Page config to the following Tree: 
 None:internal_root -> root 
 |- 0:cardEntities_Example_Page_1 -> internal_root 
     |- 0:cover_example_cover -> cardEntities_Example_Page_1 
     |- 1:switch_example_switch -> cardEntities_Example_Page_1 
     |- 2:input_boolean_example_input_boolean -> cardEntities_Example_Page_1 
     |- 3:sensor_example_sensor -> cardEntities_Example_Page_1 
 |- 1:cardEntities_Example_Page_2 -> internal_root 
     |- 0:button_example_button -> cardEntities_Example_Page_2 
     |- 1:input_button_example_input_button -> cardEntities_Example_Page_2 
     |- 2:light_light_example -> cardEntities_Example_Page_2 
     |- 3:delete -> cardEntities_Example_Page_2 
 |- 2:cardEntities_Example_Page_3 -> internal_root 
     |- 0:scene_example_scene -> cardEntities_Example_Page_3 
     |- 1:delete -> cardEntities_Example_Page_3 
     |- 2:delete -> cardEntities_Example_Page_3 
     |- 3:delete -> cardEntities_Example_Page_3 
 |- 3:cardGrid_Example_Page_4 -> internal_root 
     |- 0:light_light_example -> cardGrid_Example_Page_4 
     |- 1:button_example_button -> cardGrid_Example_Page_4 
     |- 2:cover_example_cover -> cardGrid_Example_Page_4 
     |- 3:scene_example_scene -> cardGrid_Example_Page_4 
     |- 4:switch_example_switch -> cardGrid_Example_Page_4 
     |- 5:delete -> cardGrid_Example_Page_4 
 |- 4:cardThermo_Exmaple_Thermostat -> internal_root 
 |- 5:cardMedia_unkown -> internal_root 
 |- 6:cardAlarm_unkown -> internal_root 
2022-04-02 14:40:19.104323 INFO nspanel-1: Sending MQTT Message: pageType,pageStartup
2022-04-02 14:40:19.176967 ERROR nspanel-1: Skipping Weather Update, entity not found
2022-04-02 14:40:19.271543 INFO nspanel-1: Current time 14:40:19.263141
2022-04-02 14:40:19.282837 INFO nspanel-1: Current time 14:40:19.276638
2022-04-02 14:40:19.294374 INFO nspanel-1: Setting dim value to {'time': '7:00:00', 'value': 10}
2022-04-02 14:40:19.322310 INFO nspanel-1: Started
2022-04-02 14:40:19.332855 INFO AppDaemon: App initialization complete
2022-04-02 14:40:24.402098 INFO nspanel-1: Received Message from Screen: event,startup,26,eu
2022-04-02 14:40:24.411234 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 26
2022-04-02 14:40:24.418197 INFO nspanel-1: Startup Event
2022-04-02 14:40:24.425413 INFO nspanel-1: Sending MQTT Message: time,14:40
2022-04-02 14:40:24.553096 INFO nspanel-1: Sending MQTT Message: date,?Samstag, 2. April 2022
2022-04-02 14:40:24.564766 INFO nspanel-1: Sending MQTT Message: timeout,20
2022-04-02 14:40:24.576247 INFO nspanel-1: Sending MQTT Message: dimmode,10
2022-04-02 14:40:24.598084 INFO nspanel-1: Sending MQTT Message: pageType,screensaver
2022-04-02 14:40:24.627901 ERROR nspanel-1: Skipping Weather Update, entity not found

**Comment by joBr99** [comment]
hmm, looks like your error is gone

**Comment by ladousek** [comment]
Still "Waiting for content"

**Comment by ladousek** [comment]
Could be something usefull in here?
![image](https://user-images.githubusercontent.com/51122310/161383941-0743c0d4-8552-45f9-8f76-94fe262225d0.png)

**Comment by joBr99** [comment]
which url did you use to flash the panel?

this is the version of the current pre-release `event,startup,26,eu`, but the messages of look like they are from v2.3.0

I just removed the pre-relase tag from 2.4.1, search for updates in hacs and update to 2.4.1

**Comment by ladousek** [comment]
Tasmota: https://github.com/tasmota/install/raw/main/firmware/unofficial/tasmota32-nspanel.bin
Berry driver: https://github.com/joBr99/nspanel-lovelace-ui/blob/main/tasmota/autoexec.be (but needed to rename for upload and rename back)
EU Version: `FlashNextion http://nspanel.pky.eu/lui-release.tft`

**Comment by joBr99** [comment]
yeah, strange http://nspanel.pky.eu/lui-release.tft should have pointed to 2.3.0, 

update in HACS to v2.4.1 and restart appdaemon, this should solve the problem

**Comment by ladousek** [comment]
Perfect :-) Awesome, thank you very much. What did you adjust? I am just curious.

**Comment by joBr99** [comment]
released 2.4.1 as pre-release yesterday (so newest non-beta version is hacs was 2.3.0)

and it seems like the lui-release uri already pointed to the pre-release
