### ISSUE TITLE
[BUG] Blank screen after homeassistant update to 2024.1

### ISSUE THREAD

**Issue by lcorsini** [joBr99/nspanel-lovelace-ui#1132]
### PROBLEM DESCRIPTION
The screen goes blank and unresponsive on a card that contains more than a light entity

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_C32EAC/RESULT"
    panelSendTopic: "cmnd/tasmota_C32EAC/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 1
    locale: "it_IT"
    screensaver:
      entities:
        - entity: sensor.tado_smart_thermostat_ru2827039488_current_temperature
          icon: mdi:home-thermometer
        - entity: weather.casa
          name: Today
        - entity: weather.casa
          type: 1
        - entity: weather.casa
          type: 2
      statusIcon1:
        entity: switch.tasmota_divano
      statusIcon2:
        entity: switch.tasmota_terrazzo
    hiddenCards:
      - type: cardGrid
        title: Salotto
        key: salotto
        entities:
          - entity: light.hue_white_lamp_1
            name: Lampada
            icon: mdi:lamp
          #- entity: light.lampade_muro
          #  name: Plafoniere
          #  icon: mdi:wall-sconce
          - entity: light.piantana
            name: Piantana
            icon: mdi:floor-lamp
          #- entity: light.tavolo
          #  name: Tavolo
          #  icon: mdi:ceiling-light-multiple
      - type: cardGrid
        title: Bagnetto
        key: bagnetto
        entities:
          - entity: switch.presaventolabagnetto
            icon: mdi:fan
            name: ventola
    cards:
      - type: cardGrid
        entities:
          - entity: navigate.salotto
            icon: mdi:sofa
            name: Salotto
          - entity: navigate.bagnetto
            icon: mdi:paper-roll-outline
            name: Bagnetto
        title: Luci
      - type: cardThermo
        title: Termostato
        entity: climate.tado_smart_thermostat_ru2827039488
      - type: cardThermo
        title: Condizionatore Sala
        entity: climate.condizionatoresalotto
      - type: cardThermo
        title: Condizionatore Corridoio
        entity: climate.condizionatorecorridioio
      - type: cardQR
        title: Wifi
        qrCode: "WIFI:S:<REDACTED>;T:WPA2;P:<REDACTED>;;"
        entities:
          - entity: iText.<REDACTED>
            name: Name
            icon: mdi:wifi
          - entity: iText.<REDACTED>
            name: Password
            icon: mdi:key

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

Jan 09 10:29:48 raspberrypi appdaemon[24679]: 2024-01-09 10:29:48.655280 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
Jan 09 10:29:48 raspberrypi appdaemon[24679]: 2024-01-09 10:29:48.655767 WARNING nspanel-1: Worker Ags: {'id': 'd7e97b828af04756907bca65041d3164', 'name': 'nspanel-1', 'objectid': 'a70048b407e946e394d615c57c37c64e', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0xf33672d0>>, 'data': {'topic': 'tele/tasmota_C32EAC/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,navigate.salotto,button"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/tasmota_C32EAC/RESULT', '__thread_id': 'thread-0'}}
Jan 09 10:29:48 raspberrypi appdaemon[24679]: 2024-01-09 10:29:48.656263 WARNING nspanel-1: ------------------------------------------------------------
Jan 09 10:29:48 raspberrypi appdaemon[24679]: 2024-01-09 10:29:48.661275 WARNING nspanel-1: Traceback (most recent call last):
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/srv/appdaemon/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     self._controller.button_press(entity_id, btype, value)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 291, in button_press
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     self._pages_gen.render_card(self._current_card)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 717, in render_card
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     self.generate_entities_page(navigation, card.title, card.entities, card.cardType, temp_unit)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 408, in generate_entities_page
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     command += self.generate_entities_item(item, cardType, tempUnit)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 250, in generate_entities_item
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     color = self.get_entity_color(entity, ha_type=entityType, overwrite=colorOverride)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 102, in get_entity_color
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     color = rgb_brightness(color, attr.brightness)
Jan 09 10:29:48 raspberrypi appdaemon[24679]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py", line 34, in rgb_brightness
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     brightness = int(scale(brightness,(0,255),(70,255)))
Jan 09 10:29:48 raspberrypi appdaemon[24679]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 09 10:29:48 raspberrypi appdaemon[24679]:   File "/home/homeassistant/data/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py", line 9, in scale
Jan 09 10:29:48 raspberrypi appdaemon[24679]:     return ((val - src[0]) / (src[1]-src[0])) * (dst[1]-dst[0]) + dst[0]
Jan 09 10:29:48 raspberrypi appdaemon[24679]:              ~~~~^~~~~~~~
Jan 09 10:29:48 raspberrypi appdaemon[24679]: TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Jan 09 10:29:48 raspberrypi appdaemon[24679]: 2024-01-09 10:29:48.661788 WARNING nspanel-1: ------------------------------------------------------------

```

### TO REPRODUCE
Restart AppDaemon and navigate NSPanel to desired card

### EXPECTED BEHAVIOUR
to correctly show the card

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
problem showed after upgrading homeassistant from 2023.9 to 2024.1

### PANEL / FIRMWARE VERION
US-L

**Comment by joBr99** [comment]
Please see #1036
