### ISSUE TITLE
[BUG] Berror error handling

### ISSUE THREAD

**Issue by Bascht74** [joBr99/nspanel-lovelace-ui#1143]
### PROBLEM DESCRIPTION
I cannot initialize a panel and I don't find the error.
Maybe I deleted an entity but this should not generate the error message in my optinion.
There should be an error handling that skips the entity with no uuid and generate a warning in the log.
The applicatio would be more robust...

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2024-01-19 07:48:54.870453 WARNING panel-eg-wohnzimmer: ------------------------------------------------------------
2024-01-19 07:48:54.870598 WARNING panel-eg-wohnzimmer: Unexpected error running initialize() for panel-eg-wohnzimmer
2024-01-19 07:48:54.870677 WARNING panel-eg-wohnzimmer: ------------------------------------------------------------
2024-01-19 07:48:54.871469 WARNING panel-eg-wohnzimmer: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 27, in initialize
    controller = LuiController(cfg, mqttsend.send_mqtt_msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 27, in __init__
    self.register_callbacks()
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 150, in register_callbacks
    items = self._config.get_all_entity_names()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 229, in get_all_entity_names
    entities.extend(card.get_entity_names())
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 82, in get_entity_names
    entityIds.setdefault(self.entity.uuid, []).append(val.get("entity"))
                         ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uuid'

2024-01-19 07:48:54.871586 WARNING panel-eg-wohnzimmer: ------------------------------------------------------------


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
the panel initializes and there is a warning in the log

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
current one, just flashed last week --> 4.3.3

**Comment by joBr99** [comment]
as I don't have a glass sphere, please add your apps.yaml to the issue - likely that it has something to do with the statusIcon config
