### ISSUE TITLE
DWD Weather not supported?

### ISSUE THREAD

**Issue by Chreece** [joBr99/nspanel-lovelace-ui#119]
Hello there!

You are sweating there, the developement flies! 

I wanted to check DWD weather to use a daily weather update on NSPanel and not hourly.

Unfortunately nothing shows up.
Appdaemon logs:

```
2022-04-03 13:40:46.011567 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2022-04-03 13:40:46.012000 WARNING nspanel-1: Worker Ags: {'id': 'c1eec30bb51342ae8fbd8d09b119c1e1', 'name': 'nspan                                                                          el-1', 'objectid': '41eb613daa3243cb9e9cc69b3031e95e', 'type': 'scheduler', 'function': <bound method LuiController                                                                          .weather_update of <luibackend.controller.LuiController object at 0x7f37fac680d0>>, 'pin_app': True, 'pin_thread':                                                                           1, 'kwargs': {'interval': 900, '__thread_id': 'thread-1'}}
2022-04-03 13:40:46.012413 WARNING nspanel-1: ------------------------------------------------------------
2022-04-03 13:40:46.013091 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 904, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 82, in weather_update
    self._pages_gen.update_screensaver_weather()
  File "/conf/apps/nspanel-lovelace-ui/luibackend/pages.py", line 81, in update_screensaver_weather
    up   = datetime.datetime.fromisoformat(up)
ValueError: Invalid isoformat string: '2022-04-03T00:00:00Z'
```

**Comment by joBr99** [comment]
It expects the values from the weather integration in HomeAssistant (https://www.home-assistant.io/integrations/weather/)

I never tried, but it should be possible to change the provider for that data in HomeAssistant, also I've only found this Integation releated to DWD: https://www.home-assistant.io/integrations/dwd_weather_warnings/

Please share some more details about your setup in homeassistant including screenshots with the states of the configured entity from developer tools.

**Comment by Chreece** [comment]
It's a HACS integration:
https://github.com/FL550/dwd_weather

![image](https://user-images.githubusercontent.com/68458228/161426862-e750a055-2428-4bc9-be3a-d47617572d07.png)

**Comment by Chreece** [comment]
It's missing the tzinfo and maybe that's the problem...

**Comment by joBr99** [comment]
try to do this change or update in hacs to main (and restart appdaemon)

https://github.com/joBr99/nspanel-lovelace-ui/commit/9ba4d04cccaa41dfa16587fcc1293b8828f6dcb8

The issue is that the datetime format is different, this change shound't affect date parsing from the ha weather integeration, but should allow parsing of arbitrary ISO 8601 strings and should solve this specifc problem, however using dwd could still have other side effects, for example I'm not sure if they are using the same weather conditions.

**Comment by Chreece** [comment]
Yes it works! Thank you!
As far as I know, the weather condition names are universal and standarized in HA
