### ISSUE TITLE
NSpanel home screen stopped showing icons

### ISSUE THREAD

**Issue by madebywitteveen** [joBr99/nspanel-lovelace-ui#1214]
yes, restarted the APPDEAMON and HA several times

### PROBLEM DESCRIPTION
The home screen of the lovelace ui where the clock is stopped showing the icons below the clock.
Only the clock and one horizontal line is showing.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/wallpanellivingroom/RESULT"
    panelSendTopic: "cmnd/wallpanellivingroom/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 3
      - time: "20:00:00"
        value: 1
      - time: "22:00:00"
        value: 0
    locale: "en_US"
    screensaver:
      entities:
        - entity: sensor.quatt_hp1_temperatureoutside
          icon: sun-thermometer-outline
        - entity: weather.forecast_home
          type: 0
        - entity: weather.forecast_home
          type: 1
        - entity: weather.forecast_home
          type: 2
        - entity:
        - entity: sensor.wallpanel_living_room_analog_temperature1
          icon: home-thermometer
      defaultCard: navigate.mc
    cards:
      - type: cardGrid
        key: mc
        title: MANCAVE
        entities:
          - entity: switch.mancave_desk
            icon: desk-lamp
          - entity: input_button.leave_room
          - entity: light.shellydimmer2_3494547a3481
          - entity: script.mancave_rgbon
            icon: projector-screen
      - type: cardGrid
        title: THEATRE
        entities:
          - entity: light.shellydimmer2_3494547a3481
          - entity: script.mancave_rgbon
          - entity:
          - entity: input_button.theatre_on
            icon: movie-open
          - entity: input_button.theatre_off
            icon: movie-off
      - type: cardGrid
        title: TEMPERATURE
        entities:
          - entity: sensor.shellyuni_3c6105e4eed3_temperature
          - entity: sensor.tstat_bf7056_current_temperature
          - entity: switch.boiler
          - entity: sensor.wallpanel_living_room_analog_temperature1
      - type: cardThermo
        title: LIVINGROOM
        entity: climate.tstat_bf7056_lyric_t6_thermostat
      - type: cardEntities
        title: BEDROOM
        entities:
          - entity: cover.shade_controls
      - type: cardGrid
        title: POWER
        entities:
          - entity: sensor.p1_meter_3c39e72a105a_active_current_l1
          - entity: sensor.p1_meter_3c39e72a105a_active_power_l1

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2024-04-14 15:45:23.043952 INFO nspanel-1: Dropping identical consecutive message: timeout~20
2024-04-14 15:45:23.053068 WARNING nspanel-1: ------------------------------------------------------------
2024-04-14 15:45:23.053423 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2024-04-14 15:45:23.053701 WARNING nspanel-1: Worker Ags: {'id': '650ba76d44094e20af9bb177b078645d', 'name': 'nspanel-1', 'objectid': '99345c4c59d543a3a39447c298c5d9d3', 'type': 'state', 'function': <bound method LuiController.state_change_callback of <luibackend.controller.LuiController object at 0x7f4b11269710>>, 'attribute': 'all', 'entity': 'sensor.quatt_hp1_temperatureoutside', 'new_state': {'entity_id': 'sensor.quatt_hp1_temperatureoutside', 'state': '14.25', 'attributes': {'unit_of_measurement': '°C', 'device_class': 'temperature', 'friendly_name': 'Quatt hp1 temperatureOutside'}, 'last_changed': '2024-04-14T13:45:23.032217+00:00', 'last_reported': '2024-04-14T13:45:23.032217+00:00', 'last_updated': '2024-04-14T13:45:23.032217+00:00', 'context': {'id': '01HVEDNZAR85XZV7M7EGRGYP9F', 'parent_id': None, 'user_id': None}}, 'old_state': {'entity_id': 'sensor.quatt_hp1_temperatureoutside', 'state': '14.15', 'attributes': {'unit_of_measurement': '°C', 'device_class': 'temperature', 'friendly_name': 'Quatt hp1 temperatureOutside'}, 'last_changed': '2024-04-14T13:45:17.031523+00:00', 'last_reported': '2024-04-14T13:45:17.031523+00:00', 'last_updated': '2024-04-14T13:45:17.031523+00:00', 'context': {'id': '01HVEDNSF7PBDJKB5NAC5QT6ZJ', 'parent_id': None, 'user_id': None}}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'attribute': 'all', '__thread_id': 'thread-0'}}
2024-04-14 15:45:23.054126 WARNING nspanel-1: ------------------------------------------------------------
2024-04-14 15:45:23.056308 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/config/apps/nspanel-lovelace-ui/luibackend/controller.py", line 173, in state_change_callback
    self._pages_gen.render_card(self._current_card, send_page_type=False)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 764, in render_card
    self.update_screensaver_weather(theme)
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 145, in update_screensaver_weather
    item_str += self.generate_entities_item(item, "cardEntities", mask=["type", "entityId"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/nspanel-lovelace-ui/luibackend/pages.py", line 375, in generate_entities_item
    if type(item.stype) == int and len(entity.attributes.forecast) >= item.stype:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AttrDict' object has no attribute 'forecast'
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERSION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_

**Comment by joBr99** [comment]
See #1204 and the release notes of the latest version.

https://github.com/joBr99/nspanel-lovelace-ui/releases/tag/v4.4.0
