### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by jonasfritzsche** [joBr99/nspanel-lovelace-ui#1243]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[x] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x ] Provide a screenshot of your tasmota mqtt configuration:
<img width="317" alt="tasmota" src="https://github.com/user-attachments/assets/baf690ec-2378-4ed1-ad1c-077044a7e063">

- [x ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /config/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.178.137
      client_port: 1883
      client_user: jonas
      client_password: xxxxxxx
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:


```

- [x ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_eingang/RESULT"
    panelSendTopic: "cmnd/nspanel_eingang/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "Europe/Berlin"
    screensaver:
      entity: weather.k3ll3r
    cards:
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2



```
- [x ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
[21:55:37] INFO: Starting AppDaemon...
2024-08-14 21:56:04.802110 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-08-14 21:56:04.811451 INFO AppDaemon: Python version is 3.11.9
2024-08-14 21:56:04.813315 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-08-14 21:56:04.814671 INFO AppDaemon: Added log: AppDaemon
2024-08-14 21:56:04.816003 INFO AppDaemon: Added log: Error
2024-08-14 21:56:04.817450 INFO AppDaemon: Added log: Access
2024-08-14 21:56:04.818992 INFO AppDaemon: Added log: Diag
2024-08-14 21:56:06.370516 WARNING AppDaemon: appdir: /config/appdaemon does not exist exist
2024-08-14 21:56:06.371781 WARNING AppDaemon: appdir: /config/appdaemon/apps does not exist exist
2024-08-14 21:56:06.382415 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-08-14 21:56:07.942761 INFO HASS: HASS Plugin Initializing
2024-08-14 21:56:07.944085 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-08-14 21:56:07.945678 INFO HASS: HASS Plugin initialization complete
2024-08-14 21:56:07.947636 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2024-08-14 21:56:08.517371 INFO MQTT: MQTT Plugin Initializing
2024-08-14 21:56:08.519345 INFO MQTT: Using 'appdaemon/status' as Will Topic
2024-08-14 21:56:08.521023 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2024-08-14 21:56:08.525425 INFO AppDaemon: Initializing HTTP
2024-08-14 21:56:08.528264 INFO AppDaemon: Using 'ws' for event stream
2024-08-14 21:56:08.561717 INFO AppDaemon: Starting API
2024-08-14 21:56:08.581645 INFO AppDaemon: Starting Admin Interface
2024-08-14 21:56:08.584076 INFO AppDaemon: Starting Dashboards
2024-08-14 21:56:08.753792 INFO HASS: Connected to Home Assistant 2024.7.2
2024-08-14 21:56:08.757885 INFO AppDaemon: Starting Apps with 0 workers and 0 pins
2024-08-14 21:56:08.760575 INFO AppDaemon: Running on port 5050
2024-08-14 21:56:09.051194 INFO MQTT: Connected to Broker at URL 192.168.178.137:1883
2024-08-14 21:56:09.129236 INFO HASS: Evaluating startup conditions
2024-08-14 21:56:09.147778 INFO AppDaemon: Got initial state from namespace mqtt
2024-08-14 21:56:09.150681 INFO MQTT: MQTT Plugin initialization complete
2024-08-14 21:56:09.181917 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-14 21:56:09.184271 INFO HASS: All startup conditions met
2024-08-14 21:56:09.298375 INFO AppDaemon: Got initial state from namespace default
2024-08-14 21:56:10.784344 INFO AppDaemon: Scheduler running in realtime
2024-08-14 21:56:10.799687 INFO AppDaemon: App initialization complete

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
```
2024-08-14 21:56:06.371781 WARNING AppDaemon: appdir: /config/appdaemon/apps does not exist exist
```

Did you download the Backend from HACS?
Does this folder exist?
![image](https://github.com/user-attachments/assets/a36a6578-8569-41be-93af-33232c3e443d)

**Comment by jonasfritzsche** [comment]
Yes I downloaded the Backend from HACS.
<img width="962" alt="hacs" src="https://github.com/user-attachments/assets/0bd2fad5-2682-4d7a-8c0d-fc38a5b01c07">

And yes, this folder does exist.
<img width="246" alt="liubackend" src="https://github.com/user-attachments/assets/33a0bc02-82d9-4d40-8ae0-aa47fa7b0794">
<img width="251" alt="appsfolder" src="https://github.com/user-attachments/assets/f2bbe9c6-4618-457a-ae10-4a7d225c50f2">

**Comment by joBr99** [comment]
Where is your app daemon.yaml located?

**Comment by jonasfritzsche** [comment]
It is located under /addon_configs/a0d7b954_appdaemon/appdaemon.yaml
<img width="518" alt="image" src="https://github.com/user-attachments/assets/0427c94a-09fe-47b2-a777-5e2d59ac8dd8">

**Comment by joBr99** [comment]
Do you have Home assistant OS and installed appdamen as app or do you have your own docker containers?

**Comment by jonasfritzsche** [comment]
Yes I have Home Assistant OS on Raspberry Pi and then installed Appdeamon as app.
<img width="661" alt="appdeamon" src="https://github.com/user-attachments/assets/14a3904d-bb07-4b45-9a99-87326c735148">

**Comment by joBr99** [comment]
ah lol, why did you change the app_dir in the appdaemon.yaml

https://docs.nspanel.pky.eu/stable/configure_mqtt/

Please use:

```
  app_dir: /homeassistant/appdaemon/apps/
```

**Comment by jonasfritzsche** [comment]
I read the FAQ for this issue and there it says:

"Check the location of your apps.yaml With the AppDaemon Addon >= 15 the config dir has been moved. It's required to configure the location back to the old one, **this is done by the app_dir line in your appdaemon.yaml**. This also requires you to move your apps.yaml to this location. Please make sure your apps.yaml is at **/config/appdaemon/apps/apps.yaml** and move it otherwise."

Did I misunderstood that? I will change the line in my file and give you feedback.

**Comment by jonasfritzsche** [comment]
Okay so I changed the line to "app_dir: /homeassistant/appdaemon/apps/":
<img width="578" alt="appdeamonyaml" src="https://github.com/user-attachments/assets/37bf92b9-86ab-4134-a2f6-1f89974b67fb">

Unfortunately after a restart of AppDeamon and Tasmota, I still have the "waiting for content" screen.
Is there anything else to check?

MQTT-Explorer is finding the panel:
<img width="605" alt="mqttexplorer" src="https://github.com/user-attachments/assets/a946db0d-26d0-48e8-90f5-6994c5235e8b">

**Comment by joBr99** [comment]
Please post the log from appdaemon again

**Comment by jonasfritzsche** [comment]
Seems like there ist a problem with the date format:

2024-08-16 10:03:43.885404 INFO nspanel-1: Received Message from Screen: event,startup,53,eu
2024-08-16 10:03:43.906829 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 53
2024-08-16 10:03:43.918771 INFO nspanel-1: Startup Event
2024-08-16 10:03:43.984193 INFO nspanel-1: Dropping identical consecutive message: time~10:03~
2024-08-16 10:03:43.986572 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:43.988720 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2024-08-16 10:03:43.991918 WARNING nspanel-1: Worker Ags: {'id': '7622c194cfa74b0abb1dbb238eb6c2eb', 'name': 'nspanel-1', 'objectid': '043cc66878ae4b06ba1a529ead9fbe42', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f8dfde7d0>>, 'data': {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,eu"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/nspanel_eingang/RESULT', '__thread_id': 'thread-0'}}
2024-08-16 10:03:43.994302 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:44.010044 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 34, in mqtt_event_callback
    self.customrecv_event_callback(event_name, data, kwargs)
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 58, in customrecv_event_callback
    self._controller.startup()
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 35, in startup
    self._pages_gen.update_date("")
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 128, in update_date
    date = babel.dates.format_date(datetime.datetime.now(), dateformat, locale=self._locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 681, in format_date
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 334, in parse
    parts = parse_locale(identifier, sep=sep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 1246, in parse_locale
    raise ValueError(f"expected only letters, got {lang!r}")
ValueError: expected only letters, got 'europe/berlin'

2024-08-16 10:03:44.011961 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:44.069889 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"9"}'}
2024-08-16 10:03:44.083950 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 9 Panel Version: 53
2024-08-16 10:03:49.693205 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,eu"}'}
2024-08-16 10:03:49.713361 INFO nspanel-1: Received Message from Screen: event,startup,53,eu
2024-08-16 10:03:49.748874 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 53
2024-08-16 10:03:49.773324 INFO nspanel-1: Startup Event
2024-08-16 10:03:49.854148 INFO nspanel-1: Dropping identical consecutive message: time~10:03~
2024-08-16 10:03:49.856191 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:49.858089 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2024-08-16 10:03:49.860176 WARNING nspanel-1: Worker Ags: {'id': '7622c194cfa74b0abb1dbb238eb6c2eb', 'name': 'nspanel-1', 'objectid': '043cc66878ae4b06ba1a529ead9fbe42', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f8dfde7d0>>, 'data': {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,eu"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/nspanel_eingang/RESULT', '__thread_id': 'thread-0'}}
2024-08-16 10:03:49.862649 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:49.875669 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 34, in mqtt_event_callback
    self.customrecv_event_callback(event_name, data, kwargs)
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 58, in customrecv_event_callback
    self._controller.startup()
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 35, in startup
    self._pages_gen.update_date("")
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 128, in update_date
    date = babel.dates.format_date(datetime.datetime.now(), dateformat, locale=self._locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 681, in format_date
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 334, in parse
    parts = parse_locale(identifier, sep=sep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 1246, in parse_locale
    raise ValueError(f"expected only letters, got {lang!r}")
ValueError: expected only letters, got 'europe/berlin'

2024-08-16 10:03:49.877530 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:49.931214 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"9"}'}
2024-08-16 10:03:49.942859 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 9 Panel Version: 53
2024-08-16 10:03:56.168146 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,eu"}'}
2024-08-16 10:03:56.183141 INFO nspanel-1: Received Message from Screen: event,startup,53,eu
2024-08-16 10:03:56.210091 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 53
2024-08-16 10:03:56.235771 INFO nspanel-1: Startup Event
2024-08-16 10:03:56.313005 INFO nspanel-1: Dropping identical consecutive message: time~10:03~
2024-08-16 10:03:56.315339 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:56.318128 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2024-08-16 10:03:56.320895 WARNING nspanel-1: Worker Ags: {'id': '7622c194cfa74b0abb1dbb238eb6c2eb', 'name': 'nspanel-1', 'objectid': '043cc66878ae4b06ba1a529ead9fbe42', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f8dfde7d0>>, 'data': {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,53,eu"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/nspanel_eingang/RESULT', '__thread_id': 'thread-0'}}
2024-08-16 10:03:56.322995 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:56.336394 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 34, in mqtt_event_callback
    self.customrecv_event_callback(event_name, data, kwargs)
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 58, in customrecv_event_callback
    self._controller.startup()
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 35, in startup
    self._pages_gen.update_date("")
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 128, in update_date
    date = babel.dates.format_date(datetime.datetime.now(), dateformat, locale=self._locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/dates.py", line 681, in format_date
    locale = Locale.parse(locale)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 334, in parse
    parts = parse_locale(identifier, sep=sep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/babel/core.py", line 1246, in parse_locale
    raise ValueError(f"expected only letters, got {lang!r}")
ValueError: expected only letters, got 'europe/berlin'

2024-08-16 10:03:56.338210 WARNING nspanel-1: ------------------------------------------------------------
2024-08-16 10:03:56.401404 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_eingang/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"9"}'}
2024-08-16 10:03:56.424606 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 9 Panel Version: 53

**Comment by joBr99** [comment]
Please change:

```
    locale: "Europe/Berlin"
```
in your apps.yaml to:

```
    locale: "de_DE"
```

https://docs.nspanel.pky.eu/stable/config-overview/?h=de_de#supported-keys-for-locale-config

**Comment by jonasfritzsche** [comment]
Finally that did the trick!
The display is working now, thank you!
