### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by Rayeliint** [joBr99/nspanel-lovelace-ui#1264]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
![Screenshot 2024-10-07 at 8 00 06 AM](https://github.com/user-attachments/assets/4ed94987-5e61-42d7-acb1-f264ed8ced60)

- [ ] Provide your appdaemon.yaml: 
```
secrets: /homeassistant/secrets.yaml
appdaemon:
  app_dir: /homeassistant/appdaemon/apps/
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: Australia/Brisbane
  namespace: mqtt
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.182
      client_port: 1883
      client_user: "xxxx"
      client_password: "xxxxx"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [ ] Provide your apps.yaml:
```
  ---
hello_world:
  module: hello
  class: HelloWorld
spotify_mood_lights_sync:
  module: spotify_mood_lights_sync
  class: SpotifyMoodLightsSync
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  media_player: media_player.outside_sonos
  light: light.outside_kitchen_dl1
  mode: search
  max_retries: 1
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/kitchen/RESULT"
    panelSendTopic: "tele/kitchen/CustomSend"
    model: us-l
    sleepTimeout: 20
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "22:00:00"
        value: 3
    locale: "en_US"
    timeFormat: "%-I:%M   ?%p"
    screensaver:
      type: screensaver2
      entities:
        - entity: weather.morala_weather #weather.runaway_bay
        - entity: sensor.home_total_energy_today
        - entity: sensor.wind_state
        - entity: sensor.wind_speed
        - entity: light.guests
          icon: mdi:human-female-boy
      theme:
        autoWeather: true      
    cards:
      - type: cardEntities
        title: Kitchen
        key: Kitchen
        entities:
          - entity: switch.bench_lights
          - entity: switch.kitchen_light
      #- type: cardEntities
      #  title: Test Entities Card
       # entities:
         # - entity: sensor.wind_speed
        #  - entity: sensor.wind_state
         # - entity: scene.dining_scene
         #   name: Dining
         #   icon: mdi:lightbulb
         # - entity: scene.lounge_scene
         #   name: Lounge
         #   icon: mdi:lightbulb
         # - entity: group.balcony_downlights
         #   name: Balcony
         #   icon: mdi:lightbulb
         # - entity: group.outdoor_kitchen
         #   name: Bar
         #   icon: mdi:grill
       # title: Groups
nspanel-2:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/dining/RESULT"
    panelSendTopic: "tele/dining/CustomSend"
    model: us-l
    sleepTimeout: 20
  #  sleepBrightness:
   #   - time: "7:00:00"
   #     value: 30
   #   - time: "23:00:00"
   #     value: 5
    locale: "en_US"
    timeFormat: "%-I:%M   ?%p"
    screensaver:
      entities:
        - entity: weather.morala_weather #weather.runaway_bay
        - entity: sensor.home_total_energy_today
        - entity: sensor.wind_state
        - entity: sensor.wind_speed
        - entity: light.guests
          icon: mdi:human-female-boy
      theme:
        autoWeather: true
    cards:
      - type: cardEntities
        title: Balcony Switches
        entities:
          - entity: cover.blind_lr
          - entity: sensor.wind_state
      - type: cardEntities
        title: Screen 2
        entities:
          - entity: sensor.wind_speed
        #  - entity: sensor.wind_state
        #  - entity: switch.kitchen_light
         #   name: Kitchen
          #  icon: mdi:lightbulb
       # title: Kitchen


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  2024-10-07 07:56:30.725107 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-10-07 07:56:30.725471 INFO AppDaemon: Python version is 3.11.10
2024-10-07 07:56:30.725682 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-10-07 07:56:30.725873 INFO AppDaemon: Added log: AppDaemon
2024-10-07 07:56:30.726076 INFO AppDaemon: Added log: Error
2024-10-07 07:56:30.726252 INFO AppDaemon: Added log: Access
2024-10-07 07:56:30.726431 INFO AppDaemon: Added log: Diag
2024-10-07 07:56:31.139030 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-10-07 07:56:31.512807 INFO HASS: HASS Plugin Initializing
2024-10-07 07:56:31.513124 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-10-07 07:56:31.513383 INFO HASS: HASS Plugin initialization complete
2024-10-07 07:56:31.513795 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2024-10-07 07:56:31.652721 INFO MQTT: MQTT Plugin Initializing
2024-10-07 07:56:31.653226 INFO MQTT: Using 'appdaemon/status' as Will Topic
2024-10-07 07:56:31.653472 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2024-10-07 07:56:31.654370 INFO AppDaemon: Initializing HTTP
2024-10-07 07:56:31.655073 INFO AppDaemon: Using 'ws' for event stream
2024-10-07 07:56:31.661208 INFO AppDaemon: Starting API
2024-10-07 07:56:31.665222 INFO AppDaemon: Starting Admin Interface
2024-10-07 07:56:31.665796 INFO AppDaemon: Starting Dashboards
2024-10-07 07:56:31.690168 INFO HASS: Connected to Home Assistant 2024.10.1
2024-10-07 07:56:31.719429 INFO MQTT: Connected to Broker at URL 192.168.1.182:1883
2024-10-07 07:56:31.740582 INFO AppDaemon: Got initial state from namespace mqtt
2024-10-07 07:56:31.746512 INFO MQTT: MQTT Plugin initialization complete
2024-10-07 07:56:31.780774 WARNING AppDaemon: ------------------------------------------------------------
2024-10-07 07:56:31.781287 WARNING AppDaemon: Unexpected error loading config file: /config/apps/apps.yaml
2024-10-07 07:56:31.782134 WARNING AppDaemon: ------------------------------------------------------------
2024-10-07 07:56:31.820009 INFO HASS: Evaluating startup conditions
2024-10-07 07:56:31.826712 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 578, in read_config_file
    return utils.read_config_file(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 586, in read_config_file
    return read_yaml_config(path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 756, in read_yaml_config
    config = yaml.load(config_file_contents, Loader=yaml.SafeLoader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 676, in _secret_yaml
    raise ValueError("{} not found in secrets file".format(node.value))
ValueError: spotify_client_id not found in secrets file

2024-10-07 07:56:31.830654 WARNING AppDaemon: ------------------------------------------------------------
2024-10-07 07:56:31.832948 WARNING AppDaemon: File '/config/apps/apps.yaml' invalid structure - ignoring
2024-10-07 07:56:31.836501 INFO AppDaemon: Found 0 active apps
2024-10-07 07:56:31.837128 INFO AppDaemon: Found 0 inactive apps
2024-10-07 07:56:31.837642 INFO AppDaemon: Found 0 global libraries
2024-10-07 07:56:31.838238 INFO AppDaemon: Starting Apps with 0 workers and 0 pins
2024-10-07 07:56:31.839440 INFO AppDaemon: Running on port 5050
2024-10-07 07:56:31.845268 INFO HASS: Startup condition met: hass state=RUNNING
2024-10-07 07:56:31.845721 INFO HASS: All startup conditions met
2024-10-07 07:56:31.933573 INFO AppDaemon: Got initial state from namespace default
2024-10-07 07:56:33.848410 INFO AppDaemon: Scheduler running in realtime
2024-10-07 07:56:33.856380 INFO AppDaemon: Adding /config/apps to module import path
2024-10-07 07:56:33.857094 INFO AppDaemon: Adding /config/apps/ad_sunset_lights to module import path
2024-10-07 07:56:33.857858 INFO AppDaemon: Adding /config/apps/ad_toggle_light to module import path
2024-10-07 07:56:33.858470 INFO AppDaemon: Adding /config/apps/ad-spotify-mood-lights-sync to module import path
2024-10-07 07:56:33.859145 INFO AppDaemon: Adding /config/apps/nspanel-lovelace-ui to module import path
2024-10-07 07:56:33.859790 INFO AppDaemon: Adding /config/apps/nspanel-lovelace-ui/luibackend to module import path
2024-10-07 07:56:33.860603 INFO AppDaemon: Adding /config/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2024-10-07 07:56:33.861344 INFO AppDaemon: Adding /config/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2024-10-07 07:56:33.862138 INFO AppDaemon: Adding /config/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2024-10-07 07:56:33.862827 INFO AppDaemon: Adding /config/apps/Appdaemon-Ring-Doorbell-Automations to module import path
2024-10-07 07:56:33.878591 WARNING AppDaemon: No app description found for: /config/apps/hello.py - ignoring
2024-10-07 07:56:33.880435 WARNING AppDaemon: No app description found for: /config/apps/ad_sunset_lights/sunset_lights.py - ignoring
2024-10-07 07:56:33.881773 WARNING AppDaemon: No app description found for: /config/apps/ad_toggle_light/toggle_light.py - ignoring
2024-10-07 07:56:33.883372 WARNING AppDaemon: No app description found for: /config/apps/ad-spotify-mood-lights-sync/spotify_mood_lights_sync.py - ignoring
2024-10-07 07:56:33.884926 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py - ignoring
2024-10-07 07:56:33.886407 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2024-10-07 07:56:33.887927 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2024-10-07 07:56:33.889617 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2024-10-07 07:56:33.891068 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2024-10-07 07:56:33.892472 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2024-10-07 07:56:33.893960 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2024-10-07 07:56:33.895592 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2024-10-07 07:56:33.897095 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2024-10-07 07:56:33.898674 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2024-10-07 07:56:33.900305 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2024-10-07 07:56:33.901796 WARNING AppDaemon: No app description found for: /config/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2024-10-07 07:56:33.903289 WARNING AppDaemon: No app description found for: /config/apps/Appdaemon-Ring-Doorbell-Automations/ring_automations.py - ignoring
2024-10-07 07:56:33.905245 INFO AppDaemon: App initialization complete


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
```
2024-10-07 07:56:31.832948 WARNING AppDaemon: File '/config/apps/apps.yaml' invalid structure - ignoring
```

Try to remove the first 4 lines of your apps.yaml.

The two spaces in front of the `--` aren't valid yaml and the hello world app is useless.

**Comment by Rayeliint** [comment]
Unfortunately @joBr99 that didnt work.
Any other ideas please?

**Comment by joBr99** [comment]
Please resend your appdeamon logs.

**Comment by Rayeliint** [comment]
Here they are
``
2024-10-09 17:21:35.014957 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:21:40.017473 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:21:45.019843 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:21:50.021294 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:21:55.023047 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:00.024242 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:05.025716 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:10.028864 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:15.031375 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:20.033039 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:25.034607 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:30.037250 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:35.039710 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:40.042156 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:45.044547 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:50.047262 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:22:55.049854 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:00.052381 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:05.056792 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:10.058981 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:15.061611 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:20.064007 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:25.065418 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:30.067053 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:35.068917 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:40.071051 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:45.074163 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:50.076889 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:23:55.079568 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:00.082031 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:05.084660 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:10.086655 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:15.088931 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:20.090939 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:25.092871 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:30.094734 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:35.096977 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:40.098408 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:45.101919 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:50.104309 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:24:55.107046 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:00.109117 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:05.111449 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:10.113631 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:15.115038 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:20.117297 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:25.119382 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:30.121122 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:35.123319 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:40.126884 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:45.128834 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:50.131631 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:25:55.133610 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:00.135974 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:05.138005 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:10.140040 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:15.141422 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:20.144120 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:25.146074 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:30.148131 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:35.149620 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:40.152023 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:45.153825 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:50.155426 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:26:55.156455 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:00.157546 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:05.159535 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:10.161944 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:15.164620 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:20.167038 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:25.169481 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:30.171514 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:35.173779 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:40.175537 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:45.178035 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:50.179749 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:27:55.181768 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:00.183644 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:05.185536 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:10.187487 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:15.190113 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:20.192661 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:25.195213 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:30.196840 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:35.199244 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:40.201498 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:45.203902 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:50.206780 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:28:55.209578 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:00.211543 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:05.213650 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:10.215418 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:15.217537 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:20.219805 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:25.222776 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:30.224932 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:35.226882 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:40.228516 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:45.230665 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:50.232949 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
2024-10-09 17:29:55.234906 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
``

**Comment by joBr99** [comment]
There is something wrong with your MQTT config in appdaemon.yaml.

Please try to remove `namespace: mqtt` and restart appdaemon.



This is the template from the documentation for appdaemon.yaml:

```
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  app_dir: /homeassistant/appdaemon/apps/ # !!! This is really important for AppDaemon HA Addon >= 15
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      #client_host: 192.168.75.30
      client_port: 1883
      client_user: "mqttuser"
      client_password: "mqttpassword"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

**Comment by Rayeliint** [comment]
Yes, already tried that, still not working.
What i did find when restarting Appdaemon was it looks like it is trying to access the wrong folder?
It has an error WARNING AppDaemon: Unexpected error loading config file: /config/apps/apps.yaml
This should be /config/appdaemon/apps/apps.yaml should it not?
No idea how to sort that out in my limited knowledge.

**Comment by joBr99** [comment]
No, folder path is fine as this is the perspective of the appdaemon container.

MQTT needs to be fixed before looking into anything else.

In your first post mqtt was working fine.

`2024-10-07 07:56:31.746512 INFO MQTT: MQTT Plugin initialization complete`
