### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by mrcoktail** [joBr99/nspanel-lovelace-ui#1277]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
![image](https://github.com/user-attachments/assets/bc034c5b-2ef8-4d39-b377-0ccce8e47129)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 43.6044622
  longitude: 1.4442469
  elevation: 2
  time_zone: Europe/Paris
  app_dir: /config/appdaemon/apps/apps.yaml
  plugins:
    HASS:
      type: hass
  MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.1.24
      client_port: 1883
      client_user: mqtt_admin
      client_password: ********
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:

  GNU nano 8.0                                                                  apps.yaml                                                                            
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/NSPANEL/RESULT"
    panelSendTopic: "cmnd/NSPANEL/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "7:00:00"
        value: 10
      - time: "23:00:00"
        value: 0
    locale: "fr_FR"
    screensaver:
      entity: weather.maison
    cards:
      - type: cardEntities
        entities:
          - entity: switch.radiateur_alice_2
          - entity: light.salon
        title: Example 1
      - type: cardGrid
        entities:
          - entity: switch.example_item
          - entity: light.example_item
        title: Example 2




```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[22:17:38] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-11-11 22:17:45.089121 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-11-11 22:17:45.089798 INFO AppDaemon: Python version is 3.11.10
2024-11-11 22:17:45.090386 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-11-11 22:17:45.090887 INFO AppDaemon: Added log: AppDaemon
2024-11-11 22:17:45.091418 INFO AppDaemon: Added log: Error
2024-11-11 22:17:45.091852 INFO AppDaemon: Added log: Access
2024-11-11 22:17:45.092269 INFO AppDaemon: Added log: Diag
2024-11-11 22:17:45.473531 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-11-11 22:17:45.812310 INFO HASS: HASS Plugin Initializing
2024-11-11 22:17:45.812614 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-11-11 22:17:45.812901 INFO HASS: HASS Plugin initialization complete
2024-11-11 22:17:45.813752 INFO AppDaemon: Initializing HTTP
2024-11-11 22:17:45.814889 INFO AppDaemon: Using 'ws' for event stream
2024-11-11 22:17:45.823894 INFO AppDaemon: Starting API
2024-11-11 22:17:45.828976 INFO AppDaemon: Starting Admin Interface
2024-11-11 22:17:45.829794 INFO AppDaemon: Starting Dashboards
2024-11-11 22:17:45.865733 INFO HASS: Connected to Home Assistant 2024.11.1
2024-11-11 22:17:45.883365 INFO AppDaemon: App 'hello_world' added
2024-11-11 22:17:45.885620 INFO AppDaemon: Found 1 active apps
2024-11-11 22:17:45.886159 INFO AppDaemon: Found 0 inactive apps
2024-11-11 22:17:45.886728 INFO AppDaemon: Found 0 global libraries
2024-11-11 22:17:45.887310 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-11-11 22:17:45.889024 INFO AppDaemon: Running on port 5050
2024-11-11 22:17:45.960107 INFO HASS: Evaluating startup conditions
2024-11-11 22:17:45.974311 INFO HASS: Startup condition met: hass state=RUNNING
2024-11-11 22:17:45.974922 INFO HASS: All startup conditions met
2024-11-11 22:17:46.012745 INFO AppDaemon: Got initial state from namespace default
2024-11-11 22:17:47.899231 INFO AppDaemon: Scheduler running in realtime
2024-11-11 22:17:47.905599 INFO AppDaemon: Adding /config/apps to module import path
2024-11-11 22:17:47.908285 INFO AppDaemon: Loading App Module: /config/apps/hello.py
2024-11-11 22:17:47.974976 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2024-11-11 22:17:47.977627 INFO AppDaemon: Calling initialize() for hello_world
2024-11-11 22:17:48.088270 INFO hello_world: Hello from AppDaemon
2024-11-11 22:17:48.090226 INFO hello_world: You are now ready to run Apps!
2024-11-11 22:17:48.092253 INFO AppDaemon: App initialization complete



```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
Please change app dir to
```
app_dir: /homeassistant/appdaemon/apps/
```
like in the documentation
https://docs.nspanel.pky.eu/stable/configure_mqtt/?h=app_di#configure-mqtt-connection-on-appdaemon

and repost the appdaemon log

**Comment by mrcoktail** [comment]
Done!

s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23:22:50] INFO: Starting AppDaemon...
2024-11-11 23:22:57.319400 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-11-11 23:22:57.319785 INFO AppDaemon: Python version is 3.11.10
2024-11-11 23:22:57.320117 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-11-11 23:22:57.320459 INFO AppDaemon: Added log: AppDaemon
2024-11-11 23:22:57.320832 INFO AppDaemon: Added log: Error
2024-11-11 23:22:57.321178 INFO AppDaemon: Added log: Access
2024-11-11 23:22:57.321514 INFO AppDaemon: Added log: Diag
2024-11-11 23:22:57.742368 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-11-11 23:22:58.140315 INFO HASS: HASS Plugin Initializing
2024-11-11 23:22:58.140933 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-11-11 23:22:58.141524 INFO HASS: HASS Plugin initialization complete
2024-11-11 23:22:58.142672 INFO AppDaemon: Initializing HTTP
2024-11-11 23:22:58.143744 INFO AppDaemon: Using 'ws' for event stream
2024-11-11 23:22:58.153608 INFO AppDaemon: Starting API
2024-11-11 23:22:58.161837 INFO AppDaemon: Starting Admin Interface
2024-11-11 23:22:58.162963 INFO AppDaemon: Starting Dashboards
2024-11-11 23:22:58.225260 INFO HASS: Connected to Home Assistant 2024.11.1
2024-11-11 23:22:58.255352 INFO AppDaemon: App 'hello_world' added
2024-11-11 23:22:58.257892 INFO AppDaemon: Found 1 active apps
2024-11-11 23:22:58.258843 INFO AppDaemon: Found 0 inactive apps
2024-11-11 23:22:58.259382 INFO AppDaemon: Found 0 global libraries
2024-11-11 23:22:58.260211 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-11-11 23:22:58.261749 INFO AppDaemon: Running on port 5050
2024-11-11 23:22:58.336390 INFO HASS: Evaluating startup conditions
2024-11-11 23:22:58.351774 INFO HASS: Startup condition met: hass state=RUNNING
2024-11-11 23:22:58.353604 INFO HASS: All startup conditions met
2024-11-11 23:22:58.397370 INFO AppDaemon: Got initial state from namespace default
2024-11-11 23:23:00.271506 INFO AppDaemon: Scheduler running in realtime
2024-11-11 23:23:00.278798 INFO AppDaemon: Adding /config/apps to module import path
2024-11-11 23:23:00.282250 INFO AppDaemon: Loading App Module: /config/apps/hello.py
2024-11-11 23:23:00.364939 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2024-11-11 23:23:00.371551 INFO AppDaemon: Calling initialize() for hello_world
2024-11-11 23:23:00.491007 INFO hello_world: Hello from AppDaemon
2024-11-11 23:23:00.493830 INFO hello_world: You are now ready to run Apps!
2024-11-11 23:23:00.496104 INFO AppDaemon: App initialization complete

**Comment by joBr99** [comment]
Where is your apps.yaml located?

It's supposed to be here:

![image](https://github.com/user-attachments/assets/8820fce9-09d1-435d-be16-de3a699cb1dc)

**Comment by mrcoktail** [comment]
Exactelly here...

**Comment by joBr99** [comment]
Do you have the nspanel-lovelace-ui folder there?

**Comment by mrcoktail** [comment]
Yes

**Comment by joBr99** [comment]
Where is your appdaemon.yaml located?

**Comment by mrcoktail** [comment]
![Screenshot_20241111_234521_Chrome](https://github.com/user-attachments/assets/e9348466-7d37-4a7c-a923-5eb28d9c20cb)

**Comment by joBr99** [comment]
Hey, this is the wrong location. They moved it to /addon_configs/a0d7b954_appdaemon/

![image](https://github.com/user-attachments/assets/1b3b781d-2166-4859-8e67-34a4840d5858)

**Comment by mrcoktail** [comment]
ok i have moved appdaemon.yaml in /addon_configs/a0d7b954_appdaemon/ abd i have new logs with new errors

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[23:55:40] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-11-11 23:55:46.992364 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-11-11 23:55:46.993112 INFO AppDaemon: Python version is 3.11.10
2024-11-11 23:55:46.993724 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-11-11 23:55:46.994466 INFO AppDaemon: Added log: AppDaemon
2024-11-11 23:55:46.995185 INFO AppDaemon: Added log: Error
2024-11-11 23:55:46.995758 INFO AppDaemon: Added log: Access
2024-11-11 23:55:46.996350 INFO AppDaemon: Added log: Diag
2024-11-11 23:55:47.394877 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-11-11 23:55:47.790558 INFO HASS: HASS Plugin Initializing
2024-11-11 23:55:47.791215 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-11-11 23:55:47.791831 INFO HASS: HASS Plugin initialization complete
2024-11-11 23:55:47.792903 INFO AppDaemon: Initializing HTTP
2024-11-11 23:55:47.793800 INFO AppDaemon: Using 'ws' for event stream
2024-11-11 23:55:47.801625 INFO AppDaemon: Starting API
2024-11-11 23:55:47.806987 INFO AppDaemon: Starting Admin Interface
2024-11-11 23:55:47.807913 INFO AppDaemon: Starting Dashboards
2024-11-11 23:55:47.838794 INFO HASS: Connected to Home Assistant 2024.11.1
2024-11-11 23:55:47.902813 INFO AppDaemon: App 'nspanel-1' added
2024-11-11 23:55:47.905196 INFO AppDaemon: Found 1 active apps
2024-11-11 23:55:47.905795 INFO AppDaemon: Found 0 inactive apps
2024-11-11 23:55:47.906254 INFO AppDaemon: Found 0 global libraries
2024-11-11 23:55:47.908467 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-11-11 23:55:47.910784 INFO AppDaemon: Running on port 5050
2024-11-11 23:55:47.969558 INFO HASS: Evaluating startup conditions
2024-11-11 23:55:47.991455 INFO HASS: Startup condition met: hass state=RUNNING
2024-11-11 23:55:47.992019 INFO HASS: All startup conditions met
2024-11-11 23:55:48.034418 INFO AppDaemon: Got initial state from namespace default
2024-11-11 23:55:49.922922 INFO AppDaemon: Scheduler running in realtime
2024-11-11 23:55:49.927776 INFO AppDaemon: Adding /homeassistant/appdaemon/apps to module import path
2024-11-11 23:55:49.928731 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui to module import path
2024-11-11 23:55:49.929662 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2024-11-11 23:55:49.930652 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2024-11-11 23:55:49.931768 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2024-11-11 23:55:49.932906 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2024-11-11 23:55:49.945176 INFO AppDaemon: Loading App Module: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2024-11-11 23:55:50.348547 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2024-11-11 23:55:50.352138 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2024-11-11 23:55:50.358008 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2024-11-11 23:55:50.365547 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2024-11-11 23:55:50.372404 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2024-11-11 23:55:50.376227 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2024-11-11 23:55:50.380831 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2024-11-11 23:55:50.383436 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2024-11-11 23:55:50.387111 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2024-11-11 23:55:50.392017 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2024-11-11 23:55:50.395442 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2024-11-11 23:55:50.397622 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2024-11-11 23:55:50.409322 INFO AppDaemon: Calling initialize() for nspanel-1
2024-11-11 23:55:50.560438 INFO nspanel-1: Starting
2024-11-11 23:55:50.584738 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2024-11-11 23:55:50.588547 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/NSPANEL/RESULT', 'panelSendTopic': 'cmnd/NSPANEL/CustomSend', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'locale': 'fr_FR', 'screensaver': {'entity': 'weather.maison'}, 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'switch.radiateur_alice_2'}, {'entity': 'light.salon'}], 'title': 'Example 1'}, {'type': 'cardGrid', 'entities': [{'entity': 'switch.example_item'}, {'entity': 'light.example_item'}], 'title': 'Example 2'}]}
2024-11-11 23:55:50.591243 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/NSPANEL/RESULT', 'panelSendTopic': 'cmnd/NSPANEL/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': '7:00:00', 'value': 10}, {'time': '23:00:00', 'value': 0}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'featureExperimentalSliders': False, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'fr_FR', 'quiet': True, 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'switch.radiateur_alice_2'}, {'entity': 'light.salon'}], 'title': 'Example 1'}, {'type': 'cardGrid', 'entities': [{'entity': 'switch.example_item'}, {'entity': 'light.example_item'}], 'title': 'Example 2'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.maison', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2024-11-11 23:55:50.593463 WARNING nspanel-1: ------------------------------------------------------------
2024-11-11 23:55:50.593839 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2024-11-11 23:55:50.594128 WARNING nspanel-1: ------------------------------------------------------------
2024-11-11 23:55:50.600362 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 33, in initialize
    self._controller = LuiController(cfg, mqttsender.send_mqtt_msg)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 22, in __init__
    self._pages_gen.page_type("pageStartup")
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 140, in page_type
    self._send_mqtt_msg(f"pageType~{target_page}")
  File "/homeassistant/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 102, in send_mqtt_msg
    apis.mqtt_api.mqtt_publish(topic, msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2024-11-11 23:55:50.600818 WARNING nspanel-1: ------------------------------------------------------------
2024-11-11 23:55:50.605867 INFO AppDaemon: App initialization complete

**Comment by joBr99** [comment]
hey try to fix the identation of the mqtt seqtion in your appdaemon.yaml

```
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.1.24
      client_port: 1883
      client_user: mqtt_admin
      client_password: ********
      client_topics: NONE
```

MQTT needs to be on the same level as HASS

**Comment by mrcoktail** [comment]
it works!!!!

Thank you for your help


All I have to do is configure my cards
