### ISSUE TITLE
[BUG] I can't see the page with cards

### ISSUE THREAD

**Issue by dadopts94** [joBr99/nspanel-lovelace-ui#256]
Hi, i've installed today your realease on a display but i'm tring for hours to solve my problem.
if i tap the screen on the Panel and exit from the Screensaver i see black screen until the timeout for the screensaver. 1 second before the screensaver i see for a second the page with the entities.
I've try to update the backend to Main, change FW of panel, everything. I hope you can help me.
now i've the Backend V. MAIN, HACS updated to the last version

Here attached by apps.yaml 

nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  log_level: DEBUG
  config:
    panelRecvTopic: "tele/minidisplay/RESULT"
    panelSendTopic: "cmnd/minidisplay/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 10
    screensaver:
      entity: weather.casa
      theme: !include /config/appdaemon/apps/screensaver-theme.yaml
    cards:
      - type: cardEntities
        title: test
        entities:
          - entity: switch.0x000d6f000b7ace4e
          - entity: switch.0x00124b0024c09c83

here the log on MQTT after i tap and exit from the screensaver:

--
2022-06-01 00:52:05.295034 INFO nspanel: Sending MQTT Message: entityUpd~test~0\|0~switch~switch.0x000d6f000b7ace4e~���~63142~Grande Luce~1~switch~switch.0x00124b0024c09c83~���~63142~0x00124b0024c09c83~1
2022-06-01 00:52:05.292987 INFO nspanel: Previous message repeated 4 times
2022-06-01 00:52:05.276114 INFO nspanel: Previous message repeated 4 times
2022-06-01 00:52:05.258066 INFO nspanel: Started rendering of page 0 with type cardEntities
2022-06-01 00:52:05.211041 INFO nspanel: Sending MQTT Message: entityUpd~test~0\|0~switch~switch.0x000d6f000b7ace4e~���~63142~Grande Luce~1~switch~switch.0x00124b0024c09c83~���~63142~0x00124b0024c09c83~1
2022-06-01 00:52:05.208392 INFO nspanel: Previous message repeated 4 times
2022-06-01 00:52:05.179087 INFO nspanel: Previous message repeated 4 times
2022-06-01 00:52:05.091221 INFO nspanel: Sending MQTT Message: pageType~cardEntities
2022-06-01 00:52:05.080755 INFO nspanel: Started rendering of page 0 with type cardEntities
2022-06-01 00:52:05.067617 INFO nspanel: Button Press Event; entity_id: screensaver; button_type: bExit; value: 1
2022-06-01 00:52:05.053331 INFO nspanel: Received Message from Screen: event,buttonPress2,screensaver,bExit,1
2022-06-01 00:52:05.045193 INFO nspanel: MQTT callback for: {'topic': 'tele/minidisplay/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,screensaver,bExit,1"}'}

**Comment by wvalko** [comment]
Yes, I'm experiencing the same with todays release.  I see screensaver, when I tap to open, I get black screen.  Then after 20sec back to screensaver.

**Comment by dadopts94** [comment]
![photo_2022-06-01_00-55-06](https://user-images.githubusercontent.com/45181997/171297046-29fa1fbb-3d5c-4778-bde3-bcb613d79b1b.jpg)
![photo_2022-06-01_00-55-02](https://user-images.githubusercontent.com/45181997/171297060-55903e44-c9d6-4ff8-90e7-ae241e5bcb3f.jpg)

hare the photo after the TAP and 1 second before the end of screensaver

**Comment by tianzhuang55** [comment]
> Yes, I'm experiencing the same with todays release. I see screensaver, when I tap to open, I get black screen. Then after 20sec back to screensaver. (US-P TFT / AppDaemon updated today)

same here, so I flashed back to the release version.

**Comment by dadopts94** [comment]
> > Yes, I'm experiencing the same with todays release. I see screensaver, when I tap to open, I get black screen. Then after 20sec back to screensaver. (US-P TFT / AppDaemon updated today)
> 
> same here, so I flashed back to the release version.

How you have done the downgrade?

**Comment by tianzhuang55** [comment]
> > > Yes, I'm experiencing the same with todays release. I see screensaver, when I tap to open, I get black screen. Then after 20sec back to screensaver. (US-P TFT / AppDaemon updated today)
> > 
> > 
> > same here, so I flashed back to the release version.
> 
> How you have done the downgrade?

redownload to realese vesrion in HACS, and reflash the tft

**Comment by diginfo** [comment]
I am just getting the waiting for content:
```
2022-06-01 13:08:47.427306 WARNING nspanel-1: ------------------------------------------------------------
2022-06-01 13:08:47.427613 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2022-06-01 13:08:47.427895 WARNING nspanel-1: Worker Ags: {'id': '6250afd0e46740ffa1a27ee554d196a4', 'name': 'nspanel-1', 'objectid': '4b948e1fc4384001a618e519d0977ebb', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqttListener.LuiMqttListener object at 0x7fb9fac1fe50>>, 'data': {'topic': 'tele/nspanel-4c18/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,36,eu"}'}, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'topic': 'tele/nspanel-4c18/RESULT', '__thread_id': 'thread-2'}}
2022-06-01 13:08:47.428090 WARNING nspanel-1: ------------------------------------------------------------
2022-06-01 13:08:47.428383 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py", line 41, in mqtt_event_callback
    self._controller.startup()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 73, in startup
    self.update_screensaver_brightness(kwargs={"ssbr": self.current_screensaver_brightness, "sbr": self.current_screen_brightness})
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 98, in update_screensaver_brightness
    elif sOEntity is not None and sOBrightness is not None and self._ha_api.entity_exists(sOEntity) and self._ha_api.get_entity(sOEntity).state in ["on", "true", "home"]:
UnboundLocalError: local variable 'sOEntity' referenced before assignment
2022-06-01 13:08:47.428946 WARNING nspanel-1: ------------------------------------------------------------
2022-06-01 13:08:47.659376 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel-4c18/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"4"}'}
2022-06-01 13:08:47.660015 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 4 Panel Version: 36
```

**Comment by diginfo** [comment]
Adding these to controller.py fixed it for me:
```
        sOEntity = None;
        sOBrightness = None;
```
<img width="683" alt="Screenshot 2022-06-01 at 1 24 59 PM" src="https://user-images.githubusercontent.com/6010010/171333850-c9ba2e07-bea0-4d62-9c48-f4f989efad86.png">

**Comment by joBr99** [comment]
well, this can happen, it's the dev version

fixed with
https://github.com/joBr99/nspanel-lovelace-ui/commit/8632d3cc0a33558b19573ee8b0a3fe3e077e24a1

**Comment by mathgoy** [comment]
Gents, I am having the same issue here but couldn't fix it
Can you please be more explicit abouit how to solve?
Thanks!

**Comment by joBr99** [comment]
What issue do you have? Black screen after screensaver?
