### ISSUE TITLE
[BUG] Thermo: local variable 'dest_temp2' referenced before assignment

### ISSUE THREAD

**Issue by diginfo** [joBr99/nspanel-lovelace-ui#279]
Got this error while testing the thermo card:

```
      - type: cardThermo
        title: Heating
        key: heating
        entity: climate.wiser_living_room
```

```
2022-06-13 04:08:42.070347 WARNING nspanel-4c18: ------------------------------------------------------------
2022-06-13 04:08:42.071748 WARNING nspanel-4c18: Unexpected error in worker for App nspanel-4c18:
2022-06-13 04:08:42.073041 WARNING nspanel-4c18: Worker Ags: {'id': '5ab982b3592946d1bf06abe7bc622db3', 'name': 'nspanel-4c18', 'objectid': '8f1386b51d2b425e99afda92602a99ad', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqttListener.LuiMqttListener object at 0x7f9932fb50>>, 'data': {'topic': 'tele/nspanel-4c18/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,navigate.cardThermo_heating,button"}'}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'topic': 'tele/nspanel-4c18/RESULT', '__thread_id': 'thread-1'}}
2022-06-13 04:08:42.074115 WARNING nspanel-4c18: ------------------------------------------------------------
2022-06-13 04:08:42.076346 WARNING nspanel-4c18: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py", line 58, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 246, in button_press
    self._pages_gen.render_card(self._current_card)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 494, in render_card
    temp_unit = card.raw_config.get("temperatureUnit", "celsius")
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 354, in generate_thermo_page
UnboundLocalError: local variable 'dest_temp2' referenced before assignment
2022-06-13 04:08:42.077845 WARNING nspanel-4c18: ------------------------------------------------------------
```
I am using the wiser heating:

<img width="1149" alt="Screenshot 2022-06-13 at 11 12 17 AM" src="https://user-images.githubusercontent.com/6010010/173272864-fa5af32e-b364-418e-8538-b5168191f583.png">

**Comment by joBr99** [comment]
The line numbers in the error messages indicate that you are not on the latest release (or missing a restart of appdaemon)

**Comment by diginfo** [comment]
Ahh yes, now it needs appdaemon to be restarted ?

Is this a new requirement, the appdaemon apps I wrote get reloaded when they are modified ?

**Comment by joBr99** [comment]
Needs to be restarted after every update, not new requirement. Without the reboot it doesn't get the changes in imported files. (configuring global modules doesn't help)
