### ISSUE TITLE
[BUG] FAN Implementation Not working 100%

### ISSUE THREAD

**Issue by erugaman** [joBr99/nspanel-lovelace-ui#315]
### PROBLEM DESCRIPTION
1.- There is an entity at the bottom but I don't know what it is and what does it controls, the image attach shows it.
2.- There is no way I can turn it ON or OFF but the porcentages work fine

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Provide your apps.yaml:
```
- type: cardEntities
    entities:
      - entity: fan.control_cocina 
        name: Ventilador   
        icon: mdi:fan 
    title: Cocina Ventilador

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
2022-06-25 14:02:29.873466 WARNING nspanel-2: ------------------------------------------------------------
2022-06-25 14:02:29.875110 WARNING nspanel-2: Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py", line 58, in mqtt_event_callback
self._controller.button_press(entity_id, btype, value)
File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 228, in button_press
self._ha_api.get_entity(entity_id).call_service("set_value", value=value)
File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 3108, in get_entity
self._check_entity(namespace, entity)
File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
result = future.result(self.AD.internal_function_timeout)
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
raise self._exception
File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 589, in _check_entity
raise ValueError(f"{self.name}: Invalid entity ID: {entity}")
ValueError: nspanel-2: Invalid entity ID:
2022-06-25 14:02:29.879904 WARNING nspanel-2: ------------------------------------------------------------


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS

![Icono](https://user-images.githubusercontent.com/54918424/175830591-4284e7bf-7d86-41ae-a4ac-3115517923a5.jpeg)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

### PANEL / FIRMWARE VERION
 Version US-P

**Comment by joBr99** [comment]
Hey please add the missing information from the template. Which firmware version are you using?

> PANEL / FIRMWARE VERION
Please add the Panel/Firmware Version you are using (EU, US-L or US-P)

**Comment by illuzn** [comment]
I mentioned this same artifact in dev US-P in #310

**Comment by joBr99** [comment]
Pease update to the latest dev version

**Comment by joBr99** [comment]
if you are using the dev version, please update to the latest one and check if the fifth entity is still there

**Comment by erugaman** [comment]
> if you are using the dev version, please update to the latest one and check if the fifth entity is still there

After updating the fifth entity is gone!!

**Comment by joBr99** [comment]
is this appdaemon error message also relared to the fifth entity?

**Comment by erugaman** [comment]
> is this appdaemon error message also relared to the fifth entity?

Yes it was related to the fifth entity.

**Comment by joBr99** [comment]
What is your fan doing on percentage 0?

I don't have a fan, but shouldn't it turn off on this percentage?

**Comment by erugaman** [comment]
1.- I can´t turn it ON or OFF from the NSPanel, it have to be done using my PC or my iPhone
2.- Once turn on the porcentages work well but 0 does not turn it OFF

Here is the code at my configuration.yaml
-------------------------------------
fan:
  - platform: mqtt
    name: "Control Cocina"
    qos: 1
    state_topic: "stat/tasmota_B82AB5/POWER1"
    command_topic: "cmnd/tasmota_B82AB5/POWER1"
    availability_topic: "tele/tasmota_B82AB5/LWT"
    percentage_state_topic: "stat/tasmota_B82AB5/speed"
    percentage_value_template: '{{ ((value | replace("3,","")) | int + 1) * 25 }}'
    percentage_command_topic: "cmnd/tasmota_B82AB5/tuyasend4"
    percentage_command_template: "3,{{ ((value | int - 1) / 25) | int }}"
    preset_mode_state_topic: "stat/tasmota_B82AB5/speed"
    preset_mode_value_template: '{{ value | replace("3,0", "very_slow") | replace("3,1", "low") | replace("3,2", "medium") | replace("3,3", "high") }}'
    preset_mode_command_topic: "cmnd/tasmota_B82AB5/tuyasend4"
    preset_mode_command_template: '{{ value | replace("very_slow", "3,0") | replace("low", "3,1") | replace("medium", "3,2") | replace("high", "3,3") }}'
    preset_modes:
      - "very_slow"
      - "low"
      - "medium"
      - "high"
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_on: "ON"
    payload_off: "OFF"
-------------------------------------

I guess sending just the payload_on and payload_off it shoul work.

Here are two videos:
 1.- trying to turn it ON and adjusting the porcentages work but the FAN stills OFF

https://user-images.githubusercontent.com/54918424/176236772-2377de39-6cb2-45e1-9e55-566396265585.mp4


2.- Once turn ON the speed can be modified in porcentages (25% increment) but trying to turn it OFF don't work, I have the same Entity in different pages (one gridCard and entitiesCard) as you can see, but none turns ON or OFF the FAN

https://user-images.githubusercontent.com/54918424/176236823-e5a65e95-aafd-4cfd-b477-501ea7ae7608.mp4

**Comment by erugaman** [comment]
Here is the AppdDeamon LOG from the last button press:

2022-06-28 11:44:52.300898 INFO nspanel-2: Button Press Event; entity_id: fan.control_cocina; button_type: button; value: None 
2022-06-28 11:44:53.155978 INFO nspanel-2: MQTT callback for: {'topic': 'tele/tasmota_7D5790/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,fan.control_cocina,button"}'}
2022-06-28 11:44:53.160527 INFO nspanel-2: Received Message from Screen: event,buttonPress2,fan.control_cocina,button
2022-06-28 11:44:53.163766 INFO nspanel-2: Button Press Event; entity_id: fan.control_cocina; button_type: button; value: None 
2022-06-28 11:44:58.166275 INFO nspanel-2: MQTT callback for: {'topic': 'tele/tasmota_7D5790/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,cardGrid,bNext"}'}
2022-06-28 11:44:58.171091 INFO nspanel-2: Received Message from Screen: event,buttonPress2,cardGrid,bNext
2022-06-28 11:44:58.174378 INFO nspanel-2: Button Press Event; entity_id: cardGrid; button_type: bNext; value: None 
2022-06-28 11:44:58.178121 INFO nspanel-2: Started rendering of page 1 with type cardEntities
2022-06-28 11:44:58.182438 INFO nspanel-2: Sending MQTT Message: pageType~cardEntities
2022-06-28 11:44:58.202138 INFO nspanel-2: Sending MQTT Message: entityUpd~Cocina Ventilador~1|1~number~fan.control_cocina~???~63142~Ventilador~25|0|100
2022-06-28 11:44:58.465913 INFO nspanel-2: MQTT callback for: {'topic': 'tele/tasmota_7D5790/RESULT', 'wildcard': None, 'payload': '{"nextion":"bytes(\'1AFFFFFF1AFFFFFF1AFFFFFF1AFFFFFF1AFFFFFF1AFFFFFF1AFFFFFF1AFFFFFF...\')"}'}

**Comment by joBr99** [comment]
I guess I will just add a call for turn off on slider value == 0 and one for turn of on the other values

**Comment by erugaman** [comment]
> I guess I will just add a call for turn off on slider value == 0 and one for turn of on the other values

That could be a solution, we can try it out

**Comment by joBr99** [comment]
no, that are just icons and it cannot be changed, would interfear with the detail pages for light and covers

how do you get the 4 preset buttons in HA? All of the demo fans are displayed as switches

![image](https://user-images.githubusercontent.com/29555657/176259313-3824a843-36f4-4b02-9a2a-8da5a32db241.png)

**Comment by erugaman** [comment]
> 
I see, but for my FAN i does not appear as a switch, is only the slider and the icon

**Comment by joBr99** [comment]
yes this is how it's currently implemented

I decided to change the implemention for it, I'm going to change it to a switch with a detail page in the next release

![image](https://user-images.githubusercontent.com/29555657/176272974-3251c0e7-8f86-4a0f-9764-533f4c509b07.png)

I will close this issue in favour of #326
