### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by bartgabriels** [joBr99/nspanel-lovelace-ui#357]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[X] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

```
2022-07-18 11:22:46.372316 INFO MQTT: Connected to Broker at URL homeassistant.local:1883
2022-07-18 11:22:46.407072 INFO AppDaemon: Got initial state from namespace mqtt
2022-07-18 11:22:46.410221 INFO MQTT: MQTT Plugin initialization complete
```

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [X] Provide a screenshot of your tasmota mqtt configuration:

![image](https://user-images.githubusercontent.com/64467015/179482486-7c37c695-5667-4ef4-86c9-ec2f8d76bc37.png)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:

secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: homeassistant.local
      client_port: 1883
      client_user: "homeassistant"
      client_password: "REDACTED"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

- [X] Provide your apps.yaml:
```
  apps.yaml here:

nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_C78C04/RESULT"
    panelSendTopic: "cmnd/tasmota_C78C04/CustomSend"
    updateMode: "auto-notify"
    sleepTimeout: 20
    #sleepBrightness: 10
    sleepBrightness:
      - time: "7:00:00"
        value: 5
      - time: "23:00:00"
        value: 20
    locale: "nl_NL" # used for translations in translations.py and for localized date if babel python package is installed
    screensaver:
      entity: weather.zvds381
    cards:
      - type: cardEntities
        entities:
          - entity: switch.sonoff_1000c1270e
          - entity: switch.th16
          - entity: delete
          - entity: sensor.th16_ds18b20_temperature
        title: Zwembad
      - type: cardEntities
        entities:
          - entity: sensor.p1_meter_3c39e72c926c_active_power
          - entity: sensor.my_solis_inverter_ac_output_total_power
        title: Energy Dashboard
      - type: cardEntities
        entities:
          - entity: switch.example_item
          - entity: delete
          - entity: cover.example_item
          - entity: input_boolean.example_item
        title: Example Entities 2
      - type: cardEntities
        entities:
          - entity: binary_sensor.example_item
          - entity: sensor.example_item
          - entity: button.example_item
          - entity: number.example_item
        title: Example Entities 3
      - type: cardEntities
        entities:
          - entity: scenes.example_item
          - entity: script.example_item
          - entity: button.example_item
          - entity: input_button.example_item
        title: Example Entities 4

      - type: cardThermo
        entity: climate.example_item
      - type: cardAlarm
        entity: alarm_control_panel.safe_alarm_panel
      - type: cardQR
        title: Wifi
        qrCode: "WIFI:S:ZVDS381;T:WPA;P:ZVDS381!;"
        entities:
          - entity: iText.Name.ZVDS381
            icon: wifi
          - entity: iText.Password.ZVDS381!
            icon: key
```
- [X] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
2022-07-18 11:22:45.882345 INFO AppDaemon: App 'nspanel-4' added
2022-07-18 11:22:45.889265 INFO AppDaemon: App 'nspanel-5' added
2022-07-18 11:22:45.893140 INFO AppDaemon: Found 6 total apps
2022-07-18 11:22:45.895526 INFO AppDaemon: Starting Apps with 6 workers and 6 pins
2022-07-18 11:22:45.906759 INFO AppDaemon: Running on port 5050
2022-07-18 11:22:46.372316 INFO MQTT: Connected to Broker at URL homeassistant.local:1883
2022-07-18 11:22:46.407072 INFO AppDaemon: Got initial state from namespace mqtt
2022-07-18 11:22:46.410221 INFO MQTT: MQTT Plugin initialization complete
2022-07-18 11:22:47.940227 INFO AppDaemon: Scheduler running in realtime
2022-07-18 11:22:47.966379 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-07-18 11:22:47.969234 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2022-07-18 11:22:47.971927 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2022-07-18 11:22:47.974886 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2022-07-18 11:22:47.978348 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2022-07-18 11:22:47.981071 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2022-07-18 11:22:47.983222 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger to module import path
2022-07-18 11:22:47.985428 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger/omnik to module import path
2022-07-18 11:22:47.988097 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy to module import path
2022-07-18 11:22:47.990834 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output to module import path
2022-07-18 11:22:47.993099 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger/omnik/plugin_client to module import path
2022-07-18 11:22:47.995617 INFO AppDaemon: Adding /config/appdaemon/apps/omnikdatalogger/omnik/dsmr to module import path
2022-07-18 11:22:48.137998 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2022-07-18 11:22:48.339987 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2022-07-18 11:22:48.395550 WARNING Error: ------------------------------------------------------------
2022-07-18 11:22:48.397234 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py:
2022-07-18 11:22:48.398949 WARNING Error: ------------------------------------------------------------
2022-07-18 11:22:48.414293 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 784, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 1, in <module>
    import hassapi as hass
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/hassapi.py", line 6, in <module>
    class HASSAPI(LocalProxyPlugin):
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/__init__.py", line 7, in __init__
    cls.register(cls)  # Called when a plugin class is imported
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/__init__.py", line 11, in register
    cls.localproxy_plugins.append(plugin())
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/hassapi.py", line 22, in __init__
    hybridlogger.ha_log(
  File "/config/appdaemon/apps/omnikdatalogger/omnik/ha_logger.py", line 13, in ha_log
    logger.info(f"I {datetime.datetime.now().isoformat()} {message}")
AttributeError: 'NoneType' object has no attribute 'info'
2022-07-18 11:22:48.415954 WARNING Error: ------------------------------------------------------------
2022-07-18 11:22:48.418074 WARNING AppDaemon: Removing associated apps:
2022-07-18 11:22:48.420217 WARNING AppDaemon: nspanel-1
2022-07-18 11:22:48.424703 WARNING AppDaemon: nspanel-2
2022-07-18 11:22:48.429059 WARNING AppDaemon: nspanel-3
2022-07-18 11:22:48.433968 WARNING AppDaemon: nspanel-4
2022-07-18 11:22:48.438329 WARNING AppDaemon: nspanel-5
2022-07-18 11:22:48.448992 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2022-07-18 11:22:48.475873 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2022-07-18 11:22:48.480860 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2022-07-18 11:22:48.486524 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2022-07-18 11:22:48.492113 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2022-07-18 11:22:48.497365 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2022-07-18 11:22:48.502783 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2022-07-18 11:22:48.508307 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2022-07-18 11:22:48.513832 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2022-07-18 11:22:48.519204 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py - ignoring
2022-07-18 11:22:48.524640 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omniklogger.py - ignoring
2022-07-18 11:22:48.529946 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/__init__.py - ignoring
2022-07-18 11:22:48.535782 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/InverterMsg.py - ignoring
2022-07-18 11:22:48.541191 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/ha_logger.py - ignoring
2022-07-18 11:22:48.546562 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/daylight.py - ignoring
2022-07-18 11:22:48.551970 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plant.py - ignoring
2022-07-18 11:22:48.557198 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/datalogger.py - ignoring
2022-07-18 11:22:48.562512 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/__init__.py - ignoring
2022-07-18 11:22:48.567766 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/mqtt_proxy.py - ignoring
2022-07-18 11:22:48.573707 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/tcp_proxy.py - ignoring
2022-07-18 11:22:48.579154 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/hassapi.py - ignoring
2022-07-18 11:22:48.585009 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output/__init__.py - ignoring
2022-07-18 11:22:48.591877 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output/influxdb.py - ignoring
2022-07-18 11:22:48.599126 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output/mqtt.py - ignoring
2022-07-18 11:22:48.608198 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output/csvoutput.py - ignoring
2022-07-18 11:22:48.631957 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_output/pvoutput.py - ignoring
2022-07-18 11:22:48.646324 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_client/solarmanpv.py - ignoring
2022-07-18 11:22:48.656996 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_client/__init__.py - ignoring
2022-07-18 11:22:48.671279 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_client/localproxy.py - ignoring
2022-07-18 11:22:48.679828 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/plugin_client/tcpclient.py - ignoring
2022-07-18 11:22:48.685612 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/dsmr/__init__.py - ignoring
2022-07-18 11:22:48.691524 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/omnikdatalogger/omnik/dsmr/terminal.py - ignoring
2022-07-18 11:22:48.696845 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2022-07-18 11:22:49.084113 INFO hello_world: Hello from AppDaemon
2022-07-18 11:22:49.089625 INFO hello_world: You are now ready to run Apps!
2022-07-18 11:22:49.096761 INFO AppDaemon: App initialization complete

```

**Comment by bartgabriels** [comment]
It was working untill 1:03 last sunday. Then, suddenly all NSPanels in house were stuck.
I rebooted 1, but that one is still waiting for content. Other one is still stuck on the same screen as Sunday 1:03 CET.

**Comment by joBr99** [comment]
>  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 1, in <module>
    import hassapi as hass
    
    This indicates an communication issue between AppDaemon and HomeAssistant, are you using HomeAssistant OS or your own docker containers?


 > File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/hassapi.py", line 6, in <module>
    class HASSAPI(LocalProxyPlugin):
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/__init__.py", line 7, in __init__
    cls.register(cls)  # Called when a plugin class is imported
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/__init__.py", line 11, in register
    cls.localproxy_plugins.append(plugin())
  File "/config/appdaemon/apps/omnikdatalogger/omnik/plugin_localproxy/hassapi.py", line 22, in __init__
    hybridlogger.ha_log(
  File "/config/appdaemon/apps/omnikdatalogger/omnik/ha_logger.py", line 13, in ha_log
    logger.info(f"I {datetime.datetime.now().isoformat()} {message}")
AttributeError: 'NoneType' object has no attribute 'info'

Unrelated to nspanel-lovelace-ui, but also an error releated to the Homeassistant API.

**Comment by bartgabriels** [comment]
HomeAssistant OS I believe.

**Comment by bartgabriels** [comment]
@joBr99 Any idea for quick workaround? 1 screen is still stuck at 1:03 and the other one is a turning circle ;).

**Comment by joBr99** [comment]
> There might be some more infomration on the startup part of the appdaemon log after restarting appdaemon.

Cannot tell you more without startup log of appdaemon, but this is an issue with the communicatoin between HA and AppDaemon. There are not only error messages from my backend the majority of them are from omnikdatalogger.

**Comment by bartgabriels** [comment]
Closed. Re-Installing AppDeamon, NSPanel and Onmik integration fixed it.
