### ISSUE TITLE
[Help] Waiting for content 

### ISSUE THREAD

**Issue by Tropaion** [joBr99/nspanel-lovelace-ui#386]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
I got the "Waiting for content - This is taking longer than usual" on the screen, but I don't think it's an MQTT problem, because the mqtt explorer shows many messages on the topic.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_wc_og/RESULT"
    panelSendTopic: "cmnd/nspanel_wc_og/CustomSend"
    model: us-l
    locale: "de_DE"
    screensaver:
      entity: weather.flowerhouse

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2022-08-03 23:53:31.258605 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:53:36.271200 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:53:41.282084 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:53:46.309262 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:53:53.250471 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:53:58.808030 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:54:03.828422 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-03 23:54:09.173190 INFO HASS: Connected to Home Assistant 2022.8.0
2022-08-03 23:54:10.858925 INFO HASS: Evaluating startup conditions
2022-08-03 23:54:10.974766 INFO HASS: Startup condition met: hass state=RUNNING
2022-08-03 23:54:10.975733 INFO HASS: All startup conditions met
2022-08-03 23:54:11.045505 INFO AppDaemon: Processing restart for HASS
2022-08-03 23:54:11.046538 INFO AppDaemon: Terminating nspanel-1
2022-08-03 23:54:11.048723 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-08-03 23:54:11.057630 INFO nspanel-1: Starting
2022-08-03 23:54:11.061378 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2022-08-03 23:54:11.066085 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanel_wc_og/RESULT', 'panelSendTopic': 'cmnd/nspanel_wc_og/CustomSend', 'model': 'us-l', 'locale': 'de_DE', 'screensaver': {'entity': 'weather.flowerhouse'}}
2022-08-03 23:54:11.069709 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanel_wc_og/RESULT', 'panelSendTopic': 'cmnd/nspanel_wc_og/CustomSend', 'updateMode': 'auto-notify', 'model': 'us-l', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'de_DE', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.flowerhouse', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2022-08-03 23:54:11.072221 WARNING nspanel-1: ------------------------------------------------------------
2022-08-03 23:54:11.073375 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-08-03 23:54:11.074141 WARNING nspanel-1: ------------------------------------------------------------
2022-08-03 23:54:11.075220 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 23, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-08-03 23:54:11.075850 WARNING nspanel-1: ------------------------------------------------------------

```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![image](https://user-images.githubusercontent.com/6797663/182720506-85b3fed1-63f5-4451-87dc-4cd25177f269.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
appdaemon.yaml:
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: ***
  longitude: ***
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.88.10
      client_port: 1883
      client_user: "mqtt"
      client_password: "************"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```
### PANEL / FIRMWARE VERION
_Please add the Panel/Firmware Version you are using (EU, US-L or US-P)_
US-L, Firmware: 12.0.2

**Comment by joBr99** [comment]
Hey, did you check this?

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

**Comment by Tropaion** [comment]
Yes 😄 that's why I wrote that I don't think its my mqtt config, I see many messages on the topic.

**Comment by joBr99** [comment]
Please check the MQTT connection from AppDeamon to your broker, logs of your broker might be helpful.

**Comment by Tropaion** [comment]
Here is the log:
```
1659560999: New connection from 172.30.32.2:59802 on port 1883.
1659560999: Client <unknown> closed its connection.
1659561016: Saving in-memory database to /data//mosquitto.db.
1659561119: New connection from 172.30.32.2:40302 on port 1883.
1659561119: Client <unknown> closed its connection.
1659561239: New connection from 172.30.32.2:42658 on port 1883.
1659561239: Client <unknown> closed its connection.
1659561359: New connection from 172.30.32.2:36078 on port 1883.
1659561359: Client <unknown> closed its connection.
1659561479: New connection from 172.30.32.2:42254 on port 1883.
1659561479: Client <unknown> closed its connection.
1659561599: New connection from 172.30.32.2:54242 on port 1883.
1659561599: Client <unknown> closed its connection.
1659561719: New connection from 172.30.32.2:51182 on port 1883.
1659561719: Client <unknown> closed its connection.
1659561839: New connection from 172.30.32.2:45656 on port 1883.
1659561839: Client <unknown> closed its connection.
1659561959: New connection from 172.30.32.2:49448 on port 1883.
1659561959: Client <unknown> closed its connection.
1659562079: New connection from 172.30.32.2:41388 on port 1883.
1659562079: Client <unknown> closed its connection.
1659562199: New connection from 172.30.32.2:55350 on port 1883.
1659562199: Client <unknown> closed its connection.
1659562319: New connection from 172.30.32.2:60998 on port 1883.
1659562319: Client <unknown> closed its connection.
1659562439: New connection from 172.30.32.2:54630 on port 1883.
1659562439: Client <unknown> closed its connection.
1659562559: New connection from 172.30.32.2:55952 on port 1883.
1659562559: Client <unknown> closed its connection.
1659562679: New connection from 172.30.32.2:36622 on port 1883.
1659562679: Client <unknown> closed its connection.
1659562799: New connection from 172.30.32.2:43074 on port 1883.
1659562799: Client <unknown> closed its connection.
1659562817: Saving in-memory database to /data//mosquitto.db.
1659562919: New connection from 172.30.32.2:59048 on port 1883.
1659562919: Client <unknown> closed its connection.
1659563038: Client DVES_0BD528 closed its connection.
1659563039: New connection from 172.30.32.2:35472 on port 1883.
1659563039: Client <unknown> closed its connection.
1659563042: New connection from 192.168.44.10:57288 on port 1883.
1659563042: Client <unknown> disconnected, not authorised.
1659563046: New connection from 192.168.44.10:57289 on port 1883.
1659563046: Client <unknown> disconnected, not authorised.
1659563047: New connection from 192.168.88.102:63785 on port 1883.
1659563047: New client connected from 192.168.88.102:63785 as DVES_0BD528 (p2, c1, k30, u'mqtt').
1659563057: New connection from 192.168.44.10:57295 on port 1883.
1659563057: New client connected from 192.168.44.10:57295 as mqtt-explorer-72cf122e (p2, c1, k60, u'MQTT').
1659563159: New connection from 172.30.32.2:46008 on port 1883.
1659563159: Client <unknown> closed its connection.
1659563279: New connection from 172.30.32.2:55990 on port 1883.
1659563279: Client <unknown> closed its connection.
1659563309: Client 3i6OQ54TRIal7N6rAk4yTE closed its connection.
1659563331: New connection from 172.30.32.1:48051 on port 1883.
1659563331: New client connected from 172.30.32.1:48051 as 6CWa5tZBRanwO0n0MIyx3S (p2, c1, k60, u'homeassistant').
1659563399: New connection from 172.30.32.2:48414 on port 1883.
1659563399: Client <unknown> closed its connection.
1659563519: New connection from 172.30.32.2:47232 on port 1883.
1659563519: Client <unknown> closed its connection.
1659563615: Client 6CWa5tZBRanwO0n0MIyx3S closed its connection.
1659563618: Client DVES_0BD528 closed its connection.
1659563625: New connection from 192.168.88.102:59565 on port 1883.
1659563625: New client connected from 192.168.88.102:59565 as DVES_0BD528 (p2, c1, k30, u'mqtt').
1659563637: New connection from 172.30.32.1:51369 on port 1883.
1659563637: New client connected from 172.30.32.1:51369 as 5VgzzIWSy7Tv81mWA1EOjo (p2, c1, k60, u'homeassistant').
1659563639: New connection from 172.30.32.2:46090 on port 1883.
1659563639: Client <unknown> closed its connection.
1659563759: New connection from 172.30.32.2:49118 on port 1883.
1659563759: Client <unknown> closed its connection.
1659563879: New connection from 172.30.32.2:47118 on port 1883.
1659563879: Client <unknown> closed its connection.
1659563971: Client mqtt-explorer-72cf122e disconnected.
1659563999: New connection from 172.30.32.2:50764 on port 1883.
1659563999: Client <unknown> closed its connection.
1659564119: New connection from 172.30.32.2:59264 on port 1883.
1659564119: Client <unknown> closed its connection.
1659564239: New connection from 172.30.32.2:41776 on port 1883.
1659564239: Client <unknown> closed its connection.
1659564359: New connection from 172.30.32.2:53878 on port 1883.
1659564359: Client <unknown> closed its connection.
1659564479: New connection from 172.30.32.2:40468 on port 1883.
1659564479: Client <unknown> closed its connection.
1659564599: New connection from 172.30.32.2:37896 on port 1883.
1659564599: Client <unknown> closed its connection.
1659564618: Saving in-memory database to /data//mosquitto.db.
1659564719: New connection from 172.30.32.2:48762 on port 1883.
1659564719: Client <unknown> closed its connection.
1659564839: New connection from 172.30.32.2:40888 on port 1883.
1659564839: Client <unknown> closed its connection.
1659564875: Client auto-347E2906-63BF-1330-4415-23F432C34008 closed its connection.
1659564875: Client auto-141BFE42-F1EA-0313-A65C-61C8F837D9A7 closed its connection.
```
the ip address 172.30.32.2 is weird, my ip addresses are only 192.168.88.xx and the HA has 192.168.88.10

**Comment by joBr99** [comment]
That's probably fine, that are the internal ip's of the docker containers.

It should look like this in the log:

```
1659376829: New connection from 172.30.32.1:38322 on port 1883.
1659376829: New client connected from 172.30.32.1:38322 as appdaemon (p2, c1, k60, u'mqttuser').
```

**Comment by Tropaion** [comment]
LoL, okay, I don't think it's necessary anymore, after restarten AppDaemon, it works.
I always restarted the whole server before, maybe it didn't like that.

**Comment by joBr99** [comment]
Restarting Homeassistent won't restart the add-ons, they are running in different docker containers. (However restarting the whole is should)

**Comment by Tropaion** [comment]
I did both, but maybe at the wrong time, thanks for your help, and nice application^^
