### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by mathgameapi** [joBr99/nspanel-lovelace-ui#387]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

<img width="1440" alt="Screenshot 2022-08-07 at 3 42 03 AM" src="https://user-images.githubusercontent.com/703211/183263958-cc153c39-bb82-4189-833a-88ad08eb9053.png">

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.11.229
      client_port: 1883
      client_user: "homeassistant"
      client_password: "XXXXXXXXXX"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:


```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/appdaemon.sh
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.10.3-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.10/site-packages (from babel) (2021.3)
Installing collected packages: babel
Successfully installed babel-2.10.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting mqtt_publish
  Downloading mqtt_publish-1.0-py2.py3-none-any.whl (2.7 kB)
Requirement already satisfied: paho-mqtt in /usr/lib/python3.10/site-packages (from mqtt_publish) (1.6.1)
Installing collected packages: mqtt_publish
Successfully installed mqtt_publish-1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
cont-init: info: /etc/cont-init.d/appdaemon.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun appdaemon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[03:29:48] INFO: Starting AppDaemon...
2022-08-06 21:30:05.388523 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-08-06 21:30:05.389448 INFO AppDaemon: Python version is 3.10.5
2022-08-06 21:30:05.390530 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-08-06 21:30:05.391420 INFO AppDaemon: Added log: AppDaemon
2022-08-06 21:30:05.392328 INFO AppDaemon: Added log: Error
2022-08-06 21:30:05.393139 INFO AppDaemon: Added log: Access
2022-08-06 21:30:05.393988 INFO AppDaemon: Added log: Diag
2022-08-06 21:30:06.180030 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-08-06 21:30:06.933281 INFO HASS: HASS Plugin Initializing
2022-08-06 21:30:06.934376 INFO HASS: HASS Plugin initialization complete
2022-08-06 21:30:06.936738 INFO AppDaemon: Initializing HTTP
2022-08-06 21:30:06.938704 INFO AppDaemon: Using 'ws' for event stream
2022-08-06 21:30:06.960101 INFO AppDaemon: Starting API
2022-08-06 21:30:06.978327 INFO AppDaemon: Starting Admin Interface
2022-08-06 21:30:06.980222 INFO AppDaemon: Starting Dashboards
2022-08-06 21:30:07.147366 INFO HASS: Connected to Home Assistant 2022.7.7
2022-08-06 21:30:07.219909 INFO AppDaemon: App 'nspanel-1' added
2022-08-06 21:30:07.224419 INFO AppDaemon: Found 1 total apps
2022-08-06 21:30:07.226821 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2022-08-06 21:30:07.231251 INFO AppDaemon: Running on port 5050
2022-08-06 21:30:07.402836 INFO HASS: Evaluating startup conditions
2022-08-06 21:30:07.442985 INFO HASS: Startup condition met: hass state=RUNNING
2022-08-06 21:30:07.444397 INFO HASS: All startup conditions met
2022-08-06 21:30:07.488901 INFO AppDaemon: Got initial state from namespace default
2022-08-06 21:30:09.252435 INFO AppDaemon: Scheduler running in realtime
2022-08-06 21:30:09.262166 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-08-06 21:30:09.263893 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2022-08-06 21:30:09.265245 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2022-08-06 21:30:09.266925 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2022-08-06 21:30:09.268559 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2022-08-06 21:30:09.270494 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2022-08-06 21:30:09.291725 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2022-08-06 21:30:09.294310 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2022-08-06 21:30:09.867379 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2022-08-06 21:30:09.872002 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2022-08-06 21:30:09.876324 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2022-08-06 21:30:09.880734 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2022-08-06 21:30:09.885251 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2022-08-06 21:30:09.889715 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2022-08-06 21:30:09.894515 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2022-08-06 21:30:09.898852 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqttListener.py - ignoring
2022-08-06 21:30:09.903186 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2022-08-06 21:30:09.907652 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2022-08-06 21:30:09.911683 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-08-06 21:30:10.394330 INFO nspanel-1: Starting
2022-08-06 21:30:10.399504 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2022-08-06 21:30:10.409798 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend'}
2022-08-06 21:30:10.416523 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2022-08-06 21:30:10.421742 WARNING nspanel-1: ------------------------------------------------------------
2022-08-06 21:30:10.424278 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-08-06 21:30:10.425974 WARNING nspanel-1: ------------------------------------------------------------
2022-08-06 21:30:10.434570 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 23, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-08-06 21:30:10.437043 WARNING nspanel-1: ------------------------------------------------------------
2022-08-06 21:30:10.442667 INFO AppDaemon: App initialization complete
```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
Hey, there is something wrong with your appdaemon.yaml, however I'm not completly sure what.

Do you see authentication attempts in the log of your mqtt broker?

**Comment by joBr99** [comment]
Other tought, just try to restart the AppDaemon App, this could solve the issue.

**Comment by mathgameapi** [comment]
Thank you for your reply.
i tried to restart the home assistant

same result: 
2022-08-07 03:10:12.659333 WARNING nspanel-1: ------------------------------------------------------------
2022-08-07 03:10:12.661398 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-08-07 03:10:12.663346 WARNING nspanel-1: ------------------------------------------------------------
2022-08-07 03:10:12.671558 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 23, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-08-07 03:10:12.674778 WARNING nspanel-1: ------------------------------------------------------------

i have try to use other client to connect the mqtt broker successfully.

**Comment by joBr99** [comment]
![Screenshot_20220807-075639_Home Assistant](https://user-images.githubusercontent.com/29555657/183277432-a84aad74-6ce6-49dd-a601-5c26dd59b1c5.jpg)

Not Homeassistant, AppDameon is running in a separate container and won't restart with Homeassistant.
