### ISSUE TITLE
[Help] Beim Start der icon_mapping.ts stürzt der JavaScript-Adapter ab

### ISSUE THREAD

**Issue by Peet1985** [joBr99/nspanel-lovelace-ui#421]
Wie bereits im Tiltel beschieben, stürzt bei mir immer der JavaScript-Adapter ab wenn ich die icon-mapping.ts starte.

log:
2022-08-29 [14:18:31](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).285 - info: javascript.0 (1591) starting. Version 6.0.0 in /opt/iobroker/node_modules/iobroker.javascript, node: v16.17.0, js-controller: 4.0.23
2022-08-29 [14:18:32](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).619 - info: javascript.0 (1591) requesting all states
2022-08-29 [14:18:32](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).621 - info: javascript.0 (1591) requesting all objects
2022-08-29 [14:18:33](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).752 - info: javascript.0 (1591) received all objects
2022-08-29 [14:18:33](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).985 - info: javascript.0 (1591) received all states
2022-08-29 [14:18:34](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).050 - info: javascript.0 (1591) script.js.global.icon_mapping: compiling TypeScript source...
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).228 - info: javascript.0 (1591) script.js.global.icon_mapping: TypeScript compilation successful
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).368 - error: javascript.0 (1591) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).369 - error: javascript.0 (1591) unhandled promise rejection: Debug Failure. Unhandled SyntaxKind: Unknown.
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).369 - error: javascript.0 (1591) Error: Debug Failure. Unhandled SyntaxKind: Unknown.
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:113075:22)
at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112608:17)
at pipelineEmitWithComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:116249:13)
at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112548:13)
at emit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112521:13)
at emitModuleDeclaration (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114436:13)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112799:32)
at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112608:17)
at pipelineEmitWithComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:116249:13)
at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112548:13)
at emit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112521:13)
at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:116742:9)
at emitNodeListItems (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:115493:17)
at emitNodeList (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:115411:17)
at emitList (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:115376:13)
at emitSourceFileWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:115062:13)
at emitBodyWithDetachedComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:116369:17)
at emitSourceFile (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114981:17)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112623:24)
at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112608:17)
at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112548:13)
at print (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112484:13)
at writeFile (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112468:13)
at printFile (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112329:13)
at Object.printNode (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112313:62)
at transformGlobalDeclarations (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:496:31)
at Immediate. (/opt/iobroker/node_modules/iobroker.javascript/main.js:1078:64)
at processImmediate (node:internal/timers:468:21)
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).370 - error: javascript.0 (1591) Debug Failure. Unhandled SyntaxKind: Unknown.
2022-08-29 [14:18:40](https://www.youtube.com/watch?v=ZPLJk2ZLo_8&t=43200s).438 - info: javascript.0 (1591) terminating

kann mir jemand helfen?

Danke und Gruß
Peet

**Comment by joBr99** [comment]
Reopened this, I should create issue templates for iobroker related stuff

**Comment by Peet1985** [comment]
Thanks for reopening. can you help me please?

**Comment by joBr99** [comment]
Kein plan von dem iobroker Kram das ist etwas für @Armilar

**Comment by joBr99** [comment]
Hier wird dir aber vermutlich schneller geholfen:

https://forum.iobroker.net/topic/50888/sonoff-nspanel

**Comment by Peet1985** [comment]
ok danke, ich frage dort mal nach
