### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by kenge1967** [joBr99/nspanel-lovelace-ui#485]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide a screenshot of your tasmota mqtt configuration:

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:


```

- [x] Provide your apps.yaml:
```
  apps.yaml here:


```
- [x] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by kenge1967** [comment]
![Skärmavbild 2022-09-27 kl  21 18 36](https://user-images.githubusercontent.com/57861452/192618682-4c477e53-bafb-430a-9db3-2f42f78c8dfb.png)
![Skärmavbild 2022-09-27 kl  21 20 17](https://user-images.githubusercontent.com/57861452/192618769-69dd47eb-5688-4a3a-ba36-2fa278146a4c.png)
![Skärmavbild 2022-09-27 kl  21 19 37](https://user-images.githubusercontent.com/57861452/192618792-7682ca20-e167-4199-8a01-518b6a7ce521.png)

  appdaemon.yaml here:

---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.0
  longitude: 4.0
  elevation: 2
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 10.19.67.43
      client_port: 1883
      client_user: "homeassistant"
      client_password: "XXXXXXXXXXXXXXXX"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

  apps.yaml here:

---
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_your_mqtt_topic/RESULT"
    panelSendTopic: "cmnd/tasmota_your_mqtt_topic/CustomSend"


  Log output here:


  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2022-09-27 21:03:56.051673 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:01.062263 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:06.072761 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:11.082597 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:16.092966 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:21.102622 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:26.109587 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:31.161472 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:36.235872 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:45.967612 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:51.307042 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:04:56.804829 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:01.846777 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:06.879090 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:11.905907 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:16.918481 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:21.932857 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:26.945323 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:31.958302 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:36.972825 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:41.987567 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:47.020253 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:52.033313 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:05:57.048031 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:06:02.061873 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:06:07.079805 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:06:12.117523 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:06:17.131502 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:06:23.736383 INFO HASS: Connected to Home Assistant 2022.9.7
2022-09-27 21:06:24.083795 INFO HASS: Evaluating startup conditions
2022-09-27 21:06:24.607622 INFO HASS: Startup condition met: hass state=RUNNING
2022-09-27 21:06:24.608264 INFO HASS: All startup conditions met
2022-09-27 21:06:24.705470 INFO AppDaemon: Processing restart for HASS
2022-09-27 21:06:24.706283 INFO AppDaemon: Terminating nspanel-1
2022-09-27 21:06:24.707924 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-09-27 21:06:24.719761 INFO nspanel-1: Starting
2022-09-27 21:06:24.723523 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2022-09-27 21:06:24.730265 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend'}
2022-09-27 21:06:24.738124 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2022-09-27 21:06:24.741368 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:06:24.741971 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-09-27 21:06:24.742546 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:06:24.743449 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 19, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-09-27 21:06:24.743950 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:08:33.903438 INFO HASS: Registering new service notify/mobile_app_vad_ar_detta
2022-09-27 21:22:29.055615 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:34.066437 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:39.076657 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:44.087044 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:49.098130 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:54.105688 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:22:59.112949 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:04.133174 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:11.353729 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:16.852192 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:22.436177 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:27.457999 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:32.480298 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:37.497931 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:42.520584 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-09-27 21:23:48.153072 INFO HASS: Connected to Home Assistant 2022.9.7
2022-09-27 21:23:49.371098 INFO HASS: Evaluating startup conditions
2022-09-27 21:23:49.412393 INFO HASS: Startup condition met: hass state=RUNNING
2022-09-27 21:23:49.413010 INFO HASS: All startup conditions met
2022-09-27 21:23:49.520298 INFO AppDaemon: Processing restart for HASS
2022-09-27 21:23:49.521070 INFO AppDaemon: Terminating nspanel-1
2022-09-27 21:23:49.522657 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-09-27 21:23:49.529055 INFO nspanel-1: Starting
2022-09-27 21:23:49.530617 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2022-09-27 21:23:49.533800 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend'}
2022-09-27 21:23:49.536103 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_your_mqtt_topic/RESULT', 'panelSendTopic': 'cmnd/tasmota_your_mqtt_topic/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2022-09-27 21:23:49.538735 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:23:49.539598 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2022-09-27 21:23:49.540353 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:23:49.541678 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 19, in initialize
    mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2022-09-27 21:23:49.542561 WARNING nspanel-1: ------------------------------------------------------------
2022-09-27 21:25:31.868225 INFO HASS: Registering new service notify/mobile_app_iphone

**Comment by kenge1967** [comment]
OK here it is:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.9.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.9.7
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/appdaemon.sh
cont-init: info: /etc/cont-init.d/appdaemon.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun appdaemon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[21:46:09] INFO: Starting AppDaemon...
2022-09-27 21:46:14.373339 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-09-27 21:46:14.373649 INFO AppDaemon: Python version is 3.10.5
2022-09-27 21:46:14.373893 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-09-27 21:46:14.374111 INFO AppDaemon: Added log: AppDaemon
2022-09-27 21:46:14.374336 INFO AppDaemon: Added log: Error
2022-09-27 21:46:14.374530 INFO AppDaemon: Added log: Access
2022-09-27 21:46:14.374715 INFO AppDaemon: Added log: Diag
2022-09-27 21:46:14.569970 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-09-27 21:46:14.793173 INFO HASS: HASS Plugin Initializing
2022-09-27 21:46:14.793529 INFO HASS: HASS Plugin initialization complete
2022-09-27 21:46:14.794040 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-09-27 21:46:14.951661 INFO MQTT: MQTT Plugin Initializing
2022-09-27 21:46:14.952023 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-09-27 21:46:14.952275 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-09-27 21:46:14.953244 INFO AppDaemon: Initializing HTTP
2022-09-27 21:46:14.953807 INFO AppDaemon: Using 'ws' for event stream
2022-09-27 21:46:14.960295 INFO AppDaemon: Starting API
2022-09-27 21:46:14.965218 INFO AppDaemon: Starting Admin Interface
2022-09-27 21:46:14.965889 INFO AppDaemon: Starting Dashboards
2022-09-27 21:46:14.991033 INFO HASS: Connected to Home Assistant 2022.9.7
2022-09-27 21:46:15.018884 INFO AppDaemon: App 'nspanel-1' added
2022-09-27 21:46:15.020407 INFO AppDaemon: Found 1 total apps
2022-09-27 21:46:15.021163 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2022-09-27 21:46:15.022429 INFO AppDaemon: Running on port 5050
2022-09-27 21:46:15.092240 INFO HASS: Evaluating startup conditions
2022-09-27 21:46:15.111674 INFO HASS: Startup condition met: hass state=RUNNING
2022-09-27 21:46:15.112169 INFO HASS: All startup conditions met
2022-09-27 21:46:15.172301 INFO AppDaemon: Got initial state from namespace default
2022-09-27 21:46:20.002863 CRITICAL MQTT: Could not Complete Connection to Broker, please Ensure Broker at URL 10.19.67.43:1883 is correct and broker is not down and restart Appdaemon
2022-09-27 21:46:20.016944 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
2022-09-27 21:46:30.022323 CRITICAL MQTT: Could not Complete Connection to Broker, please Ensure Broker at URL 10.19.67.43:1883 is correct and broker is not down and restart Appdaemon
2022-09-27 21:46:30.031745 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
2022-09-27 21:46:40.037380 CRITICAL MQTT: Could not Complete Connection to Broker, please Ensure Broker at URL 10.19.67.43:1883 is correct and broker is not down and restart Appdaemon
2022-09-27 21:46:40.056337 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds

**Comment by joBr99** [comment]
So AppDaemon isn't able to connect to your MQTT Broker.

Are you sure that the IP Address is correct? 
The IP used in your tasmota configuration is a different one. (10.19.67.5)

**Comment by kenge1967** [comment]
Thanks a lot, I´ve got it working now
