### ISSUE TITLE
[BUG] cardGrid Alarmo icon on Arming/Triggering state

### ISSUE THREAD

**Issue by nelim** [joBr99/nspanel-lovelace-ui#541]
### PROBLEM DESCRIPTION
When arming Alarmo card, on phone Icon is Blinking, it is also blinking when in cardAlarm, but when i click back , on cardGrid is stays black screen, looks like there is no blink supported.
Exactly the same happen when Alarmo card is in state Triggered.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
  apps.yaml here:
    cards:
      - type: cardGrid
        entities:
          - entity: switch.sonoff_lampa
            name: "Двор"
            icon: mdi:coach-lamp
          - entity: switch.basic1_relay
            name: "Лампички"
            icon: mdi:string-lights
          - entity: light.dimmer
            name: "Хол"
          - entity: navigate.cardAlarm_myAlarm
            status: alarm_control_panel.alarmo
            name: Аларма
          - entity: navigate.cardThermo_Detska
            name: "Детска"
            status: switch.washer_switch
            icon: mdi:home-thermometer-outline
          - entity: switch.boiler
            name: "Бойлер"
            icon: mdi:water-boiler
    hiddenCards:
      - type: cardAlarm
        title: Аларма
        entity: alarm_control_panel.alarmo
        key: myAlarm
      - type: cardThermo
        title: Детска
        entity: climate.detska
        key: Detska



```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:

2022-10-26 09:50:47.762675 INFO nspanel-1: Sending MQTT Message: pageType~cardAlarm
2022-10-26 09:50:47.823968 INFO nspanel-1: Sending MQTT Message: entityUpd~alarm_control_panel.alarmo~2|0~������ ������������ - ����������~arm_home~������ ������������~arm_away~~~~~���~3334~enable~disable~���~62848~
2022-10-26 09:51:00.071834 INFO nspanel-1: Sending MQTT Message: time~09:51~���������������� ��������, 16.6��C
2022-10-26 09:51:01.239975 INFO nspanel-1: Started rendering of page None with type cardAlarm
2022-10-26 09:51:01.259081 INFO nspanel-1: Sending MQTT Message: entityUpd~alarm_control_panel.alarmo~2|0~������������������a����~disarm~~~~~~~���~62848~enable~enable~
2022-10-26 09:51:01.279682 INFO nspanel-1: Started rendering of page None with type cardAlarm
2022-10-26 09:51:06.190402 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,cardAlarm,bUp"}'}
2022-10-26 09:51:06.193965 INFO nspanel-1: Received Message from Screen: event,buttonPress2,cardAlarm,bUp
2022-10-26 09:51:06.196488 INFO nspanel-1: Button Press Event; entity_id: cardAlarm; button_type: bUp; value: None 
2022-10-26 09:51:06.198955 INFO nspanel-1: Started rendering of page 0 with type cardGrid
2022-10-26 09:51:06.201826 INFO nspanel-1: Sending MQTT Message: pageType~cardGrid
2022-10-26 09:51:06.259061 WARNING nspanel-1: ------------------------------------------------------------
2022-10-26 09:51:06.259862 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2022-10-26 09:51:06.260370 WARNING nspanel-1: Worker Ags: {'id': 'da341bde83224c74a5b2a75668a32ff2', 'name': 'nspanel-1', 'objectid': '22f0eda62aa44c63ba3d627c70f854bd', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f1a34e306d0>>, 'data': {'topic': 'tele/nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,cardAlarm,bUp"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/nspanel/RESULT', '__thread_id': 'thread-0'}}
2022-10-26 09:51:06.261014 WARNING nspanel-1: ------------------------------------------------------------
2022-10-26 09:51:06.262053 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 58, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 218, in button_press
    self._pages_gen.render_card(self._current_card)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 622, in render_card
    self.generate_entities_page(navigation, card.title, card.entities, card.cardType, temp_unit)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 379, in generate_entities_page
    command += self.generate_entities_item(item, cardType, tempUnit)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 226, in generate_entities_item
    icon_res = get_icon(item.status.split(".")[0], state=status_entity.state, device_class=status_entity.attributes.get("device_class", "_"), overwrite=icon)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py", line 219, in get_icon
    return get_icon_id(map_to_mdi_name(ha_type, state, device_class))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py", line 6903, in get_icon_id
    if "text:" in ma_name:
TypeError: argument of type 'NoneType' is not iterable
2022-10-26 09:51:06.263104 WARNING nspanel-1: ------------------------------------------------------------
2022-10-26 09:51:14.132435 INFO nspanel-1: Started rendering of page 0 with type cardGrid
2022-10-26 09:51:14.200700 INFO nspanel-1: Sending MQTT Message: entityUpd~������������~1|1~switch~switch.sonoff_lampa~���~17299~��������~0~switch~switch.basic1_relay~���~17299~����������������~0~light~light.dimmer~���~17299~������~0~button~navigate.cardAlarm_myAlarm~���~3334~������������~Press~button~navigate.cardThermo_Detska~���~17299~������������~Press~switch~switch.boiler~���~17299~������������~0
```

### TO REPRODUCE
try to go in cardGrid when Alarmo is in state triggered or arming

### EXPECTED BEHAVIOUR
It should blink, but even if not blinking, will be better to render some icon, not to stay black screen.

### SCREENSHOTS
not needed, it is black screen while icon is blinking

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU 3.5.0

**Comment by joBr99** [comment]
The exeption is coming from here:
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/icons.py#L179

I need to add icons for triggered and arming there. 
However blinking won't be supported on cardGrid/cardEntities.
