### ISSUE TITLE
[Feature Request] Display hiddenCard with mqtt command.

### ISSUE THREAD

**Issue by pro1212123** [joBr99/nspanel-lovelace-ui#567]
### FEATURE DESCRIPTION
I am looking for a way to exit screensaver and display the specified hidden card with CustomSend command

### ADDITIONAL CONTEXT
Something like: CustomSend displayCard {{ hidden_card_name }}
Would be useful when I switch on led light and the panel would show a card with color settings, and when I turn on dimmable lights the panel would show brightness settings, etc.

### PANEL / FIRMWARE VERION
EU, US-L, US-P

**Comment by joBr99** [comment]
You can navigate to pages by sending something to the RESULT Topic, but I don't think that this is way to want to do.
#513

There are details pages for lights where you can set the color and color temp; no need to craft your own hidden card.

![image](https://user-images.githubusercontent.com/29555657/201511253-afa65a8e-9154-48df-ac32-0a9b9c2fac93.png)

You can open thoose on cardGrid with a long press and on cardEntities with a click on the name.

Or do you want to open this popup page via mqtt?

**Comment by pro1212123** [comment]
> Or do you want to open this popup page via mqtt?

exactly, because I've got 2 leds and 3 dimmers in 1 room and they're all controlled with wall switches. So when person enters the room and turn the light on with the switch, appropriate page would show up, separate for leds and dimmers in my case.

**Comment by joBr99** [comment]
I'm doing this in my kitchen.

`pageType~popupLight~Kueche~light.kueche_lights`

Beaware that it wont show the icon in the current version.

**Comment by pro1212123** [comment]
Tried this, the reason why I need this to be hidden card is because my lights are grouped, dimmer_group contains 3 dimmers and it's impossible to control them separately, or select appropriate scene. This is useful for users not familiar with the system or for the elderly people.

**Comment by joBr99** [comment]
So you want to show a hiddenCard instead of the the popupPage?

See #513

**Comment by pro1212123** [comment]
Please tell me if I understand it correctly or I miss something.
1. I'll make hiddencards to be triggered with hw buttons
2. I'll trigger hw buttons with mqtt.

**Comment by joBr99** [comment]
It doesn't have anything to do with the Hardware Buttons.

You can configure a hidden card (acually doesn't matter if it's hidden or not):

```
    hiddenCards:
      - type: cardGrid
        title: Exmaple Hidden
        key: test
        entities:
          - entity: light.kueche_lights
```

And then navigate to it by sending `event,buttonPress2,navigate.cardGrid_test,button` to the `CustomRecv` topic.

**Comment by pro1212123** [comment]
I have in my apps.yaml
    panelRecvTopic: "tele/panel-gost/RESULT"
    panelSendTopic: "cmnd/panel-gost/CustomSend"

and my card contains key:
      - type: cardGrid
        key: lights_kuh

Script to trigger card:

alias: Popup Light
sequence:
  - service: mqtt.publish
    data:
      topic: tele/panel-gost/RESULT
      payload: CustomRecv event,buttonPress2,navigate.cardGrid_lights_kuh,button
      qos: "0"
mode: restart
icon: mdi:message-check-outline

Sorry for being stupid, please advice why it isn't working?

**Comment by joBr99** [comment]
remove `CustomRecv` from the payload

**Comment by pro1212123** [comment]
```
alias: Popup Light
sequence:
  - service: mqtt.publish
    data:
      topic: tele/panel-gost/RESULT
      payload: event,buttonPress2,navigate.cardGrid_lights_kuh,button
      qos: "0"
mode: restart
icon: mdi:message-check-outline
```

nothing happens,

tracing the script:
```
Executed: 13 ноября 2022 г., 12:00:57
Result:

params:
  domain: mqtt
  service: publish
  service_data:
    topic: tele/panel-gost/RESULT
    payload: event,buttonPress2,navigate.cardGrid_kuh,button
    qos: '0'
  target: {}
running_script: false
limit: 10
```

**Comment by joBr99** [comment]
please check the appdaemon log and post the output during running the script

**Comment by joBr99** [comment]
The key in payload in your trace is different, it's missing the `light`

`    payload: event,buttonPress2,navigate.cardGrid_kuh,button`

`      payload: event,buttonPress2,navigate.cardGrid_lights_kuh,button`

**Comment by pro1212123** [comment]
I tested to see if renaming card would help, but it didn't.

new trace here:

```
Executed: 13 ноября 2022 г., 12:12:07
Result:

params:
  domain: mqtt
  service: publish
  service_data:
    topic: tele/panel-gost/RESULT
    payload: event,buttonPress2,navigate.cardGrid_lights_kuh,button
    qos: '0'
  target: {}
running_script: false
limit: 10
```
and appdaemon log is here:

```
2022-11-13 12:13:41.365665 INFO panel-gost: Sending MQTT Message: color~0~65535~33808~65535~33808~33808~33808~33808~33808~33808~50712~50712~50712~50712~65535~65535~65535~65535~65535~33808~33808~50712
2022-11-13 12:13:41.393907 INFO panel-entry: Sending MQTT Message: color~0~65535~33808~65535~33808~33808~33808~33808~33808~33808~50712~50712~50712~50712~65535~65535~65535~65535~65535~33808~33808~50712
2022-11-13 12:13:41.769843 INFO panel-gost: MQTT callback for: {'topic': 'tele/panel-gost/RESULT', 'wildcard': None, 'payload': 'event,buttonPress2,navigate.cardGrid_lights_kuh,button'}
2022-11-13 12:13:41.771643 WARNING panel-gost: ------------------------------------------------------------
2022-11-13 12:13:41.773443 WARNING panel-gost: Unexpected error in worker for App panel-gost:
2022-11-13 12:13:41.775451 WARNING panel-gost: Worker Ags: {'id': '814fb37103c54c978e62c240feb76d31', 'name': 'panel-gost', 'objectid': '14e406599be94b75be5392c76ab6ae8a', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f93a73e20>>, 'data': {'topic': 'tele/panel-gost/RESULT', 'wildcard': None, 'payload': 'event,buttonPress2,navigate.cardGrid_lights_kuh,button'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/panel-gost/RESULT', '__thread_id': 'thread-0'}}
2022-11-13 12:13:41.777656 WARNING panel-gost: ------------------------------------------------------------
2022-11-13 12:13:41.781777 WARNING panel-gost: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 17, in mqtt_event_callback
    data = json.loads(data["payload"])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-11-13 12:13:41.783757 WARNING panel-gost: ------------------------------------------------------------
2022-11-13 12:13:46.898216 INFO panel-gost: Started rendering of page None with type screensaver
2022-11-13 12:13:46.944933 INFO panel-gost: Previous message repeated 1 times
2022-11-13 12:13:46.947178 INFO panel-gost: Forecast 1 is overriden with {'entity': 'sensor.dom_wind_speed', 'name': ' ', 'icon': 'weather-windy'}
2022-11-13 12:13:46.976075 INFO panel-gost: Previous message repeated 1 times
2022-11-13 12:13:46.977962 INFO panel-gost: Forecast 2 is overriden with {'entity': 'sensor.panel_entry_temp', 'name': ' ', 'icon': 'thermometer'}
2022-11-13 12:13:46.982549 INFO panel-gost: Forecast 2 is overriden with {'entity': 'sensor.trv_spalnya_current_temperature', 'name': ' ', 'icon': 'thermometer'}
2022-11-13 12:13:47.012358 INFO panel-gost: Forecast 3 is overriden with {'entity': 'sensor.house_power_consumption', 'name': ' ', 'icon': 'mdi:transmission-tower'}
2022-11-13 12:13:47.042861 INFO panel-gost: Previous message repeated 1 times
2022-11-13 12:13:47.045190 INFO panel-gost: Forecast 4 is overriden with {'entity': 'switch.gas_boiler', 'name': ' ', 'icon': {'on': 'mdi:fire-circle', 'unavailable': 'mdi:fire-alert', 'off': 'mdi:fire-off'}, 'color': {'off': [192, 192, 192], 'unavailable': [255, 25, 25], 'on': [255, 255, 25]}}
2022-11-13 12:13:47.053991 INFO panel-gost: Forecast 4 is overriden with {'entity': 'switch.gas_boiler', 'name': ' ', 'icon': {'on': 'mdi:fire-circle', 'unavailable': 'mdi:fire-off', 'off': 'mdi:fire-off'}, 'color': {'off': [192, 192, 192], 'unavailable': [128, 128, 128], 'on': [255, 255, 25]}}
2022-11-13 12:13:47.113803 INFO panel-gost: Sending MQTT Message: weatherUpdate~���~7.0��C~ ~���~7.0 m/s~ ~���~24.0 ��~ ~���~187 W~ ~���~off ~~~���~0~���~16904
2022-11-13 12:13:47.119248 INFO panel-entry: Sending MQTT Message: weatherUpdate~���~7.0��C~ ~���~7.0 m/s~ ~���~26.5  ~ ~���~187 W~ ~���~off ~~~���~0~���~16904
2022-11-13 12:13:47.144256 INFO panel-entry: Sending MQTT Message: color~0~65535~33808~65535~33808~33808~33808~33808~33808~33808~50712~50712~50712~50712~65535~65535~65535~65535~65535~33808~33808~50712
2022-11-13 12:13:47.152941 INFO panel-gost: Sending MQTT Message: color~0~65535~33808~65535~33808~33808~33808~33808~33808~33808~50712~50712~50712~50712~65535~65535~65535~65535~65535~33808~33808~50712
```

**Comment by joBr99** [comment]
Ah sorry; payload needs to looks like this:

`{"CustomRecv":"event,buttonPress2,navigate.cardGrid_lights_kuh,button"}`

**Comment by pro1212123** [comment]
Almost there, thanks.

Is there a way to force card to close? like CustomSend notify~~

Pretty much what I try to achieve:
```
alias: Popup Light
sequence:
  - service: mqtt.publish
    data:
      topic: tele/panel-gost/RESULT
      payload: '{"CustomRecv":"event,buttonPress2,navigate.cardGrid_lights_kuh,button"}'
      qos: "0"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: cmnd/panel-gost/Backlog
      payload: CustomSend notify~~
      qos: "0"
mode: restart
icon: mdi:message-check-outline
```

**Comment by joBr99** [comment]
use

`      payload: '{"CustomRecv":"event,sleepReached,cardGrid"}'`

**Comment by pro1212123** [comment]
> probably not what you want

Sorry, I somehow treat the card like a popup message, I shouldn't do that. I guess the normal use case is actually leave it on, and let it disappear with the screensaver. My goal was reached, guests and my mother-in-law can use it now without figuring out how it works. It's not the first time you're saving my day. THANKS.
