### ISSUE TITLE
[Feature Request] Wait to run "select" entity type ?

### ISSUE THREAD

**Issue by JBaptisme33** [joBr99/nspanel-lovelace-ui#595]
### FEATURE DESCRIPTION
Hi,

thanks for hard work, it's impressive and really unsefull.

Is there a way to use a select entity ?
image

Or use a template into entities as workaround to apply each of available modes (Low, Medium, Hard), an entity for low mode, another for Medium, etc....

Another, thanks for work !
### ADDITIONAL CONTEXT
Impossible to use a select entity into NS Panel
### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Hey, can you send a screenshot from HA dev tools of that entity?

**Comment by joBr99** [comment]
No worries, got it

![image](https://user-images.githubusercontent.com/29555657/204045349-dc19c253-83e3-4179-88d1-c5015803e4d7.png)

**Comment by joBr99** [comment]
Hey, latest dev version should support select entities.

Just update to main in HACS and restart AppDaemon, no need to update the firmware.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by JBaptisme33** [comment]
Hi, 
Faster than you is impossible...

I've tried last main version.
Hum, not shure to understand how to use this entity ?
 ```     - type: cardEntities
        entities:
          - entity: input_select.heated_seat_left
          - entity: input_select.select.heated_seat_left
```

But not work, i've error `not found check, apps.yml`
I need to create an input_select entity to use my select I'm not shure to understand ?

**Comment by illuzn** [comment]
Shouldn't it be:

````yaml
entities:
- entity: select.heated_seat_left
````

and make sure to be running `main` branch and latest firmware.

**Comment by JBaptisme33** [comment]
I think there is an issue into last commit for shuffle:

```
2022-11-28 10:10:29.203054 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 1026, in check_app_updates
    await self.init_object(app)
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 321, in init_object
    modname = await utils.run_in_executor(self, __import__, app_args["module"])
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 4, in <module>
    from luibackend.controller import LuiController
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 331
    apis.ha_api.get_entity(entity_id).call_service("shuffle_set", shuffle=!cur_suffle)
                                                                          ^
SyntaxError: invalid syntax
```

Can you rollback or make tag without this commit to test the select feature ?

**Comment by joBr99** [comment]
fixed

**Comment by JBaptisme33** [comment]
Hi, 
Main branch is ok now, indeed.
It seem start working.
I have select button, with actual value (Off in my case). When I click i don't have available choices.

Here appdaemon logs if it can help ?

```
2022-11-28 18:14:25.647056 INFO nspanel-1: Received Message from Screen: event,buttonPress2,popupLight,bExit
2022-11-28 18:14:25.648119 INFO nspanel-1: Button Press Event; entity_id: popupLight; button_type: bExit; value: None 
2022-11-28 18:14:25.649182 INFO nspanel-1: Started rendering of page 2 with type cardEntities
2022-11-28 18:14:25.650360 INFO nspanel-1: Sending MQTT Message: pageType~cardEntities
2022-11-28 18:14:25.666911 INFO nspanel-1: Sending MQTT Message: entityUpd~Tesla~1|1~input_sel~select.heated_seat_left~���~17299~k2000 Heated seat left~Off~text~sensor.battery~���~17299~Batterie~93 %~shutter~cover.trunk~���~17299~Coffre~���||���|enable|disable|disable~switch~switch.heated_steering~���~17299~Volant chauffant~0~switch~switch.sentry_mode~���~17299~Sentinelle~0
2022-11-28 18:14:27.052772 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_entree/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,select.heated_seat_left,button"}'}
2022-11-28 18:14:27.054265 INFO nspanel-1: Received Message from Screen: event,buttonPress2,select.heated_seat_left,button
2022-11-28 18:14:27.055811 INFO nspanel-1: Button Press Event; entity_id: select.heated_seat_left; button_type: button; value: None 
2022-11-28 18:14:29.089812 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_entree/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,pageOpenDetail,popupInSel,select.heated_seat_left"}'}
2022-11-28 18:14:29.090217 INFO nspanel-1: Received Message from Screen: event,pageOpenDetail,popupInSel,select.heated_seat_left
2022-11-28 18:14:29.091726 INFO nspanel-1: Sending MQTT Message: entityUpdateDetail2~select.heated_seat_left~~17299~select~Off~~
```

**Comment by joBr99** [comment]
screenshot from HA Dev tools would help

looks like the provided options are empty

![image](https://user-images.githubusercontent.com/29555657/204342354-351df3e1-47ee-4fbf-8028-cfd6279047c1.png)
