### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by uros76** [joBr99/nspanel-lovelace-ui#599]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:
![image](https://user-images.githubusercontent.com/25409772/204417032-57539bc7-75b6-49b9-93c4-71f89d15f5e3.png)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.226
      client_port: 1883
      client_user: mqttonly
      client_password: 
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
---
nspanel:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
[02:39:32] INFO: Starting AppDaemon...
2022-11-29 02:39:37.951501 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-11-29 02:39:37.951818 INFO AppDaemon: Python version is 3.10.8
2022-11-29 02:39:37.952042 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-11-29 02:39:37.952271 INFO AppDaemon: Added log: AppDaemon
2022-11-29 02:39:37.952522 INFO AppDaemon: Added log: Error
2022-11-29 02:39:37.952734 INFO AppDaemon: Added log: Access
2022-11-29 02:39:37.952935 INFO AppDaemon: Added log: Diag
2022-11-29 02:39:38.164517 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-11-29 02:39:38.407684 INFO HASS: HASS Plugin Initializing
2022-11-29 02:39:38.408023 INFO HASS: HASS Plugin initialization complete
2022-11-29 02:39:38.408577 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-11-29 02:39:38.559379 INFO MQTT: MQTT Plugin Initializing
2022-11-29 02:39:38.559733 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-11-29 02:39:38.560016 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-11-29 02:39:38.560597 WARNING AppDaemon: error loading plugin: MQTT - ignoring
2022-11-29 02:39:38.560872 WARNING AppDaemon: ------------------------------------------------------------
2022-11-29 02:39:38.561851 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugin_management.py", line 112, in __init__
    raise ValueError("Duplicate namespace: {}".format(namespace))
ValueError: Duplicate namespace: default
2022-11-29 02:39:38.562131 WARNING AppDaemon: ------------------------------------------------------------
2022-11-29 02:39:38.562892 INFO AppDaemon: Initializing HTTP
2022-11-29 02:39:38.563660 INFO AppDaemon: Using 'ws' for event stream
2022-11-29 02:39:38.570601 INFO AppDaemon: Starting API
2022-11-29 02:39:38.575979 INFO AppDaemon: Starting Admin Interface
2022-11-29 02:39:38.576652 INFO AppDaemon: Starting Dashboards
2022-11-29 02:39:38.599960 INFO HASS: Connected to Home Assistant 2022.11.4
2022-11-29 02:39:38.623475 INFO AppDaemon: App 'nspanel' added
2022-11-29 02:39:38.624988 INFO AppDaemon: Found 1 total apps
2022-11-29 02:39:38.625810 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2022-11-29 02:39:38.627675 INFO AppDaemon: Running on port 5050
2022-11-29 02:39:38.690656 INFO HASS: Evaluating startup conditions
2022-11-29 02:39:38.704638 INFO HASS: Startup condition met: hass state=RUNNING
2022-11-29 02:39:38.705105 INFO HASS: All startup conditions met
2022-11-29 02:39:38.747924 INFO AppDaemon: Got initial state from namespace default
2022-11-29 02:39:40.639098 INFO AppDaemon: Scheduler running in realtime
2022-11-29 02:39:40.649728 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-11-29 02:39:40.651106 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2022-11-29 02:39:40.652377 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2022-11-29 02:39:40.653807 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2022-11-29 02:39:40.655378 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2022-11-29 02:39:40.657024 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2022-11-29 02:39:40.693422 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2022-11-29 02:39:40.696633 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2022-11-29 02:39:40.992199 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2022-11-29 02:39:40.993614 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2022-11-29 02:39:40.994988 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2022-11-29 02:39:40.996355 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2022-11-29 02:39:40.997748 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2022-11-29 02:39:40.999114 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2022-11-29 02:39:41.000476 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2022-11-29 02:39:41.001839 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2022-11-29 02:39:41.003176 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2022-11-29 02:39:41.004542 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2022-11-29 02:39:41.005925 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2022-11-29 02:39:41.007104 INFO AppDaemon: Initializing app nspanel using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2022-11-29 02:39:41.137295 INFO nspanel: Starting
2022-11-29 02:39:41.145112 INFO nspanel: Input config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'model': 'eu'}
2022-11-29 02:39:41.147031 INFO nspanel: Loaded config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2022-11-29 02:39:41.154255 INFO nspanel: Sending MQTT Message: pageType~pageStartup
2022-11-29 02:39:41.170570 INFO nspanel: Registering callbacks for the following items: ['iText.', 'iText.', 'iText.', 'iText.', 'weather.example']
2022-11-29 02:39:41.181109 WARNING nspanel: ------------------------------------------------------------
2022-11-29 02:39:41.182132 WARNING nspanel: Unexpected error running initialize() for nspanel
2022-11-29 02:39:41.182924 WARNING nspanel: ------------------------------------------------------------
2022-11-29 02:39:41.186376 WARNING nspanel: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 45, in initialize
    LuiMqttListener(mqtt_api, topic_recv, controller, updater)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 10, in __init__
    mqtt_api.mqtt_subscribe(topic=topic)
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/mqtt/mqttapi.py", line 257, in mqtt_subscribe
    result = self.call_service(service, **kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/services.py", line 158, in call_service
    raise ServiceException(
appdaemon.exceptions.ServiceException: ('Unknown service (%s/%s/%s) in call_service from %s', 'default', 'mqtt', 'subscribe', 'nspanel')
2022-11-29 02:39:41.186835 WARNING nspanel: ------------------------------------------------------------
2022-11-29 02:39:41.188126 INFO AppDaemon: App initialization complete
2022-11-29 02:40:00.059593 INFO nspanel: Sending MQTT Message: time~02:40~
```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by joBr99** [comment]
```
      namespace: mqtt
```

is missing in the appdaemon.yaml

**Comment by uros76** [comment]
Thanks again. Namespace was missing, now it all works.
