### ISSUE TITLE
[Feature Request] Make next / prev / up / home icons in title bar configurable entities.

### ISSUE THREAD

**Issue by esclear** [joBr99/nspanel-lovelace-ui#633]
### FEATURE DESCRIPTION
I would like to have the option to make the next / prev / up / home icons in the top left and top right corners of the screen configurable entities.
Then, one would have the option of navigating, switching  outputs, triggering automations, etc.

This would be somewhat similar to `statusIcon1` and `statusIcon2` for the screensaver

### ADDITIONAL CONTEXT
This _might_ be a duplicate of #403, though I think this request may be a bit broader and #403 seems to be limited to ioBroker.

### PANEL / FIRMWARE VERION
nspanel-lovelace-ui v3.7.3, tasmota 12.3.1 on NSPanel EU.

**Comment by joBr99** [comment]
interesting idea, however this is a pretty significat change and it's not going to land on the roadmap in the near future

**Comment by esclear** [comment]
Aww, that's unfortunate :/

I don't know much about how the Nextion UI works, but I assume that the icons are already some form of buttons.
This is one of the cases where I can see myself making a PR to scratch my own itch, if that would be acceptable for you. Though I would probably need some support.

How is the `homeButton` currently controlled?
I looked at the [HMI protocol](https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI), but I didn't find any mention of it there.

**Comment by joBr99** [comment]
Initially there was only one "horizontal" level for the pages. (controlled with bPrev/bNext)

With the addion of navigate there was bUp added, the apperace of the buttons is controlled though the second value of entiyUpd Command. (`entityUpd~test~1|1`)

0 -> disabled
1 -> bPrev/bNext
2 -> bUp/bHome

In general you can categorize the buttons in the HMI Project into "static" and more "dynamic" ones.

The static ones are doing what's defined in them and the apperance is defined in the Project.

The button for bNext is for example sending this: (simplified, there is some logic for bNext/bHome)
```
tSend.txt="event,buttonPress2,cardMedia,bNext"
```

The buttons used on cardGrid and on the buttom row of cardMedia (since last version) are based on the format build for cardEntities. This allows to reuse code to generate entities for cardGrid/cardEntities and cardMedia.
```
{type}~{internalNameEntity}~{icon}~{iconColor}~{displayNameEntity}~{optionalValue}
```
`displayNameEntity` and the `optionalValue` isn't really needed for the usage as button; however the paramter needs to be there to stick with the format.

I will look into implementing this in the HMI Project (replacing the 1|1 prameter with the 12 parameters needed for the two buttons).

However that's only the HMI side of things, there are also some todo's on the python side.

**Comment by joBr99** [comment]
do you think it's importent to be able to open popup/detail pages from thoose button in the nav bar?

**Comment by esclear** [comment]
This hasn't come up for the use cases I imagine, however I don't want to assume that others don't have ones where this would apply.

**Comment by joBr99** [comment]
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/HMI/README.md#cardentities-page

Serial Protocol has been changed.

Also Navigation in the backend has been changed to use new format.

https://github.com/joBr99/nspanel-lovelace-ui/blob/8ab20b16a8919bbbca43799de86427fb0f4e3cc6/apps/nspanel-lovelace-ui/luibackend/pages.py#L641

Should be possible to implement a config option to overwrite the navigation buttons from there.

**Comment by joBr99** [comment]
Should be working like this:

```
    cards:
      - type: cardGrid
        title: Wohnzimmer
        navItem1:
          entity: light.bad_lights
        navItem2:
          entity: light.bad_lights
        entities:
          - entity: navigate.cardGrid_szenen
            icon: palette
```

**Comment by esclear** [comment]
Cool, thanks a lot!

Can this be tested with the latest / current Nextion firmware / configuration, as described in https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version ?
I tried that out, but it renders incorrectly (with no navItems configured).

**Comment by joBr99** [comment]
Will have a look, but if there's an error it's on the python side.

**Comment by esclear** [comment]
I am seeing two errors in my appdaemon logs:
```
2023-01-04 19:23:46.370830 WARNING nspanel: ------------------------------------------------------------
2023-01-04 19:23:46.371767 WARNING nspanel: Unexpected error in worker for App nspanel:
2023-01-04 19:23:46.372541 WARNING nspanel: Worker Ags: {}
2023-01-04 19:23:46.373207 WARNING nspanel: ------------------------------------------------------------
2023-01-04 19:23:46.380825 WARNING nspanel: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/hacs/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 22, in initialize
    mqttsend = LuiMqttSender(self, topic_send)
TypeError: __init__() missing 1 required positional argument: 'topic_send'
```
This is likely not the cause of the problem, however this one may be:
```
2023-01-04 19:24:46.659018 WARNING Error: ------------------------------------------------------------
2023-01-04 19:24:46.660006 WARNING Error: Unexpected error loading module: /conf/apps/hacs/nspanel-lovelace-ui/nspanel-lovelace-ui.py:
2023-01-04 19:24:46.660796 WARNING Error: ------------------------------------------------------------
2023-01-04 19:24:46.669622 WARNING Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 784, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/conf/apps/hacs/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 3, in <module>
    from luibackend.config import LuiBackendConfig
  File "/conf/apps/hacs/nspanel-lovelace-ui/luibackend/config.py", line 1, in <module>
    from itertools import pairwise
ImportError: cannot import name 'pairwise' from 'itertools' (unknown location)
```

**Comment by joBr99** [comment]
did you restart appdaemon after redownloading the app?

**Comment by esclear** [comment]
I did, yes. It seems that the problem is that the appdaemon container comes with Python 3.9 installed, but `itertools.pairwise` was added in Python 3.10.

**Comment by joBr99** [comment]
oh shoot ... appdaemon on homeassistant supervisor is alrady bundled with 3.10

**Comment by esclear** [comment]
An alternative might be using `itertools.combinations( sequence, 2)`.
Although I think that the generated sequence might be slightly different.

**Comment by esclear** [comment]
Wouldn't it have to be something like `AC BD CE` then?
(I haven't looked at the code yet).

**Comment by joBr99** [comment]
It's a loop going over each card.

Inside of the loop it needs to access the previous and the next card's uuid to set it to the prev and next attribute of the current card.

**Comment by esclear** [comment]
Yes, so if I'm in card `B`, I'd want the ids of card `A`, the previous, and card `C`, the next one, don't I?

**Comment by esclear** [comment]
The `previous` id for the next card is set when setting the `next` id for the current card. That works.

**Comment by joBr99** [comment]
yep, there are probably thousands of ways to do this, end result should look like this:

```
cardA:
  self.uuid = A
  self.uuid_next = B
  self.uuid_prev = C
  
 cardB:
  self.uuid = B
  self.uuid_next = C
  self.uuid_prev = A
  
 cardC:
  self.uuid = C
  self.uuid_next = A
  self.uuid_prev = B
 ```
 
 during rendering of the card it's going to use uuid_prev and uuid_next for the entities in the corner of the card

**Comment by esclear** [comment]
I wrote an alternative implementation, that works in python 3.9 (and also older versions), which I could provide in a PR.

I'm currently facing some other issues, but I don't know what may have caused them:
```
2023-01-04 20:11:42.852882 WARNING HASS: Code: 500, error: 500 Internal Server Error  Server got itself in trouble
--
2023-01-04 20:11:42.852058 WARNING HASS: Error calling Home Assistant service default/template/render
```
I'm not sure whether these are related by the upgrade to HA 2023.01 or to this projects' HEAD.

**Comment by joBr99** [comment]
do that

I would guess this error could be caused by a `render_template` call, do you have an idea on which actions thoose warnings appear?

**Comment by joBr99** [comment]
Ok, I've the same warnings in my log and I'm still on 2022.12.1

**Comment by esclear** [comment]
In the HA log, I see:
```
2023-01-04 20:19:49.950 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 364, in post
    tpl = template.Template(data["template"], request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 338, in __init__
    raise TypeError("Expected template to be a string")
TypeError: Expected template to be a string
```

**Comment by joBr99** [comment]
Took me some time to figure it out, but it's most likely caused by `        defaultCard = apis.ha_api.render_template(defaultCard)` in config.py

**Comment by esclear** [comment]
Ah, yes. this is `None` in my case.

**Comment by joBr99** [comment]
going to refactor searchCard to search_card and fix that call to the HA api with none

**Comment by joBr99** [comment]
should be fixed

tested with and without defaultCard configured

**Comment by esdcmc** [comment]
now that the home button has disappeared: it is unclear what should be added in apps.yaml to get it back

**Comment by esclear** [comment]
> now that the home button has disappeared: it is unclear what should be added in apps.yaml to get it back

The home button should be there, if nothing is configured – it remains the standard.

**Comment by joBr99** [comment]
You have to configure it on your cards; as noted in the breaking changes of the release notes:

> bHome config options to display Home Button has been removed, use overwrite of navigation buttons instead https://github.com/joBr99/nspanel-lovelace-ui/issues/633 @joBr99



```
    cards:
      - type: cardGrid
        title: Home
        key: home
        entities:
          - entity: light.bad

    hiddenCards:
      - type: cardGrid
        title: Wohnzimmer
        navItem2:
          entity: navigate.home
          icon: mdi:home
        entities:
          - entity: light.kitchen
```

**Comment by esdcmc** [comment]
thanks it does work again now (I will just have to add instruction on all cards).

Sorry description on "the breaking changes of the release notes" confused me as this 633# is about something not working in Python and could not find a clear example of revised apps.yaml.

Maybe it's just me
Thanks a lot anyway

**Comment by joBr99** [comment]
added an example in the docs & a link in the release notes
