### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by yecine06** [joBr99/nspanel-lovelace-ui#647]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![Screenshot 2022-12-29 at 06 26 52](https://user-images.githubusercontent.com/98430/209907145-cb7d5374-c524-44a0-a031-37a339b7e7c0.png)

- [ ] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.2.217:8123
      token: "xxxxx"
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.2.217
      client_port: 1883
      client_user: "mqttuser"
      client_password: "xxxx"
      client_topics: NONE
http:
  url: http://192.168.2.217:5050/
admin:
api:
hadashboard:

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:


hello_world:
  module: hello
  class: HelloWorld
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: eu

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
2022-12-29 06:19:26.023621 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-12-29 06:19:26.023899 INFO AppDaemon: Python version is 3.9.9
2022-12-29 06:19:26.024098 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
2022-12-29 06:19:26.024310 INFO AppDaemon: Added log: AppDaemon
2022-12-29 06:19:26.024528 INFO AppDaemon: Added log: Error
2022-12-29 06:19:26.024733 INFO AppDaemon: Added log: Access
2022-12-29 06:19:26.024934 INFO AppDaemon: Added log: Diag
2022-12-29 06:19:26.045460 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-12-29 06:19:26.065730 INFO HASS: HASS Plugin Initializing
2022-12-29 06:19:26.065924 INFO HASS: HASS Plugin initialization complete
2022-12-29 06:19:26.066190 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-12-29 06:19:26.074161 INFO MQTT: MQTT Plugin Initializing
2022-12-29 06:19:26.074383 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-12-29 06:19:26.074563 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-12-29 06:19:26.075073 INFO AppDaemon: Initializing HTTP
2022-12-29 06:19:26.075431 INFO AppDaemon: Using 'ws' for event stream
2022-12-29 06:19:26.079853 INFO AppDaemon: Starting API
2022-12-29 06:19:26.082563 INFO AppDaemon: Starting Admin Interface
2022-12-29 06:19:26.082949 INFO AppDaemon: Starting Dashboards
2022-12-29 06:19:26.099799 INFO HASS: Connected to Home Assistant 2022.12.8
2022-12-29 06:19:26.117832 INFO MQTT: Connected to Broker at URL 192.168.2.217:1883
2022-12-29 06:19:26.123151 INFO AppDaemon: App 'hello_world' added
2022-12-29 06:19:26.123815 INFO AppDaemon: Got initial state from namespace mqtt
2022-12-29 06:19:26.124132 INFO MQTT: MQTT Plugin initialization complete
2022-12-29 06:19:26.128411 INFO AppDaemon: App 'nspanel-1' added
2022-12-29 06:19:26.129213 INFO AppDaemon: Found 2 total apps
2022-12-29 06:19:26.129658 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2022-12-29 06:19:26.130925 INFO AppDaemon: Running on port 5050
2022-12-29 06:19:26.165355 INFO HASS: Evaluating startup conditions
2022-12-29 06:19:26.169427 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-29 06:19:26.169722 INFO HASS: All startup conditions met
2022-12-29 06:19:26.180908 INFO AppDaemon: Got initial state from namespace default
2022-12-29 06:19:28.139748 INFO AppDaemon: Scheduler running in realtime
2022-12-29 06:19:28.147655 INFO AppDaemon: Adding /conf/apps to module import path
2022-12-29 06:19:28.152279 INFO AppDaemon: Loading App Module: /conf/apps/hello.py
2022-12-29 06:19:28.165252 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2022-12-29 06:19:28.457488 INFO AppDaemon: New client Admin Client connected
2022-12-29 06:19:28.507373 INFO hello_world: Hello from AppDaemon
2022-12-29 06:19:28.515008 INFO hello_world: You are now ready to run Apps!
2022-12-29 06:19:28.518427 INFO AppDaemon: App initialization complete


```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

i have correctly shared my appdaemon conf folder as sugested in the documentation and other issues

````
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    restart: always

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    environment:
      - HA_URL=http://192.168.2.217:8123
      - DASH_URL=http://192.168.2.217:5050/
      - TOKEN="xxx"
    ports:
      - 5050:5050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/appdaemon:/conf
    depends_on:
      - homeassistant
    restart: always

````

All images are updated 

But on my nspanel i'm still seeing waiting for content

I have a step that i have skipped in the documentation :
https://docs.nspanel.pky.eu/prepare_ha/#installing-lovelace-appdaemon-backend-application

Because i haven't found how to do it without hacs as i'm using docker i don't have it

**Comment by yecine06** [comment]
I have tried to copy the content of the folder `nspanel-lovelace-ui` inside my config folder

````
user@docker1:~/docker/homeassistant/config/appdaemon$ tree -L 2
.
├── appdaemon.yaml
├── apps
│   ├── apps.yaml
│   ├── apps.yaml.example
│   ├── hello.py
│   ├── nspanel-lovelace-ui
│   └── __pycache__
├── compiled
│   ├── css
│   ├── html
│   └── javascript
├── dashboards
│   └── Hello.dash
├── namespaces
├── requirements.txt
└── www
````


And i have an error during startup of appdaemon

`````

Requirement already satisfied: babel in /usr/local/lib/python3.9/site-packages (from -r /conf/requirements.txt (line 1)) (2.11.0)
Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.9/site-packages (from babel->-r /conf/requirements.txt (line 1)) (2021.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
2022-12-29 06:47:26.503535 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-12-29 06:47:26.503858 INFO AppDaemon: Python version is 3.9.9
2022-12-29 06:47:26.504098 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
2022-12-29 06:47:26.504304 INFO AppDaemon: Added log: AppDaemon
2022-12-29 06:47:26.504516 INFO AppDaemon: Added log: Error
2022-12-29 06:47:26.504735 INFO AppDaemon: Added log: Access
2022-12-29 06:47:26.504935 INFO AppDaemon: Added log: Diag
2022-12-29 06:47:26.532040 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-12-29 06:47:26.553459 INFO HASS: HASS Plugin Initializing
2022-12-29 06:47:26.553685 INFO HASS: HASS Plugin initialization complete
2022-12-29 06:47:26.554188 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-12-29 06:47:26.562183 INFO MQTT: MQTT Plugin Initializing
2022-12-29 06:47:26.562444 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-12-29 06:47:26.562762 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-12-29 06:47:26.563656 INFO AppDaemon: Initializing HTTP
2022-12-29 06:47:26.564136 INFO AppDaemon: Using 'ws' for event stream
2022-12-29 06:47:26.568644 INFO AppDaemon: Starting API
2022-12-29 06:47:26.571524 INFO AppDaemon: Starting Admin Interface
2022-12-29 06:47:26.571896 INFO AppDaemon: Starting Dashboards
2022-12-29 06:47:26.588344 INFO HASS: Connected to Home Assistant 2022.12.8
2022-12-29 06:47:26.594610 INFO MQTT: Connected to Broker at URL 192.168.2.217:1883
2022-12-29 06:47:26.600463 INFO AppDaemon: Got initial state from namespace mqtt
2022-12-29 06:47:26.600883 INFO MQTT: MQTT Plugin initialization complete
2022-12-29 06:47:26.613826 INFO AppDaemon: App 'hello_world' added
2022-12-29 06:47:26.615568 INFO AppDaemon: App 'nspanel-1' added
2022-12-29 06:47:26.616717 INFO AppDaemon: Found 2 total apps
2022-12-29 06:47:26.617114 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2022-12-29 06:47:26.618364 INFO AppDaemon: Running on port 5050
2022-12-29 06:47:26.645815 INFO HASS: Evaluating startup conditions
2022-12-29 06:47:26.650172 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-29 06:47:26.650464 INFO HASS: All startup conditions met
2022-12-29 06:47:26.660972 INFO AppDaemon: Got initial state from namespace default
2022-12-29 06:47:28.653428 INFO AppDaemon: Scheduler running in realtime
2022-12-29 06:47:28.662335 INFO AppDaemon: Adding /conf/apps to module import path
2022-12-29 06:47:28.663241 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui to module import path
2022-12-29 06:47:28.664046 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend to module import path
2022-12-29 06:47:28.664879 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2022-12-29 06:47:28.665878 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2022-12-29 06:47:28.666838 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2022-12-29 06:47:28.707025 INFO AppDaemon: Loading App Module: /conf/apps/hello.py
2022-12-29 06:47:28.722953 INFO AppDaemon: Loading App Module: /conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2022-12-29 06:47:28.727949 WARNING Error: ------------------------------------------------------------
2022-12-29 06:47:28.728606 WARNING Error: Unexpected error loading module: /conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py:
2022-12-29 06:47:28.729159 WARNING Error: ------------------------------------------------------------
2022-12-29 06:47:28.736425 WARNING Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 784, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 34
    match model:
          ^
SyntaxError: invalid syntax

2022-12-29 06:47:28.737053 WARNING Error: ------------------------------------------------------------
2022-12-29 06:47:28.737591 WARNING AppDaemon: Removing associated apps:
2022-12-29 06:47:28.738242 WARNING AppDaemon: nspanel-1
2022-12-29 06:47:28.743064 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2022-12-29 06:47:28.746328 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2022-12-29 06:47:28.749351 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2022-12-29 06:47:28.752244 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2022-12-29 06:47:28.755233 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2022-12-29 06:47:28.758114 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2022-12-29 06:47:28.761388 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2022-12-29 06:47:28.764580 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2022-12-29 06:47:28.767497 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2022-12-29 06:47:28.770148 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2022-12-29 06:47:28.772452 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2022-12-29 06:47:28.774209 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2022-12-29 06:47:29.075065 INFO hello_world: Hello from AppDaemon
2022-12-29 06:47:29.077857 INFO hello_world: You are now ready to run Apps!
2022-12-29 06:47:29.081109 INFO AppDaemon: App initialization complete

`````

**Comment by joBr99** [comment]
Hey, 
you copied the latest development version into the apps folder.

Please delete the nspanel-lovelace-ui folder and download the latest release though HACS (easiest way and it will also tell you if there are updates).

(apperantly the appdaemon docker image is still on python 3.9 and the development version started to use python 3.10 syntax ..., reverted that should now also be working again)

**Comment by yecine06** [comment]
Yep exactly.

I downloaded the latest release from https://github.com/joBr99/nspanel-lovelace-ui/releases and then uploaded the folder `apps/nspanel-lovelace-ui` to `/homeassistant/config/appdaemon/apps/nspanel-lovelace-ui `

And now it's working

Thanks
