### ISSUE TITLE
Please fill out the requested Information in new Issues

### ISSUE THREAD

**Issue by joBr99** [joBr99/nspanel-lovelace-ui#675]

**Comment by johntdyer** [comment]
So where do we ask general questions ?  I dont see a template for that in the issue types on Github...

**Comment by joBr99** [comment]
well, what's your question?

**Comment by johntdyer** [comment]
Ha, well I wanted to two things...

First:  is there a way in the grid card to toggle a cover vs hitting the icon and then going to the other screen w/ the up / down arrow.  

Second: Is there a way to change the color of the heading of a page based on state of an entity or entities ?

Thanks!

**Comment by joBr99** [comment]
>First: is there a way in the grid card to toggle a cover vs hitting the icon and then going to the other screen w/ the up / down arrow.

Something like this should work:
```
          - entity: service.cover.toggle
            status: cover.rolladen
            data:
              entity_id: cover.rolladen
```

>Second: Is there a way to change the color of the heading of a page based on state of an entity or entities ?

No, the color of the heading is fixed.

**Comment by johntdyer** [comment]
Yea, the server.cover.toggle didnt work 

```
 - type: cardGrid
        title: Test Grid Card
        entities:
          - entity: service.cover.toggle
            status: cover.one_car_garage_door
            color: '{{iif(states("cover.one_car_garage_door")=="open", "[255,0,0]", "[0,255,0]")}}'
            icon:
              open: mdi:garage-open
              closed: mdi:garage-lock
            data:
              entity_id: cover.one_car_garage_door

```

**Comment by joBr99** [comment]
Please update to the latest development version and try again.

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

**Comment by johntdyer** [comment]
Updated appDamon to main branch, I then went to the console and ran the firmware update for Landscape.   I then restarted the NS Panel afterward for good measure.  

Here are the logs when I save app.yaml

```
023-01-24 13:45:44.626998 WARNING nspanel-1: ------------------------------------------------------------
2023-01-24 13:46:01.008991 INFO nspanel-1: Sending MQTT Message: time~13:46~
2023-01-24 13:46:13.094551 INFO nspanel-1: MQTT callback for: {'topic': 'tele/tasmota_0DBF2C/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,49,us-l"}'}
2023-01-24 13:46:13.095245 INFO nspanel-1: Received Message from Screen: event,startup,49,us-l
2023-01-24 13:46:13.096071 INFO nspanel-1: Sending MQTT Message: X
2023-01-24 13:46:13.098183 INFO nspanel-1: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 49
2023-01-24 13:46:13.098935 INFO nspanel-1: Startup Event
2023-01-24 13:46:13.102994 INFO nspanel-1: Sending MQTT Message: time~13:46~
2023-01-24 13:46:13.107196 INFO nspanel-1: Sending MQTT Message: date~Tuesday, January 24, 2023
2023-01-24 13:46:13.108992 INFO nspanel-1: Sending MQTT Message: timeout~20
2023-01-24 13:46:13.111252 INFO nspanel-1: Sending MQTT Message: dimmode~10~100~6371
2023-01-24 13:46:13.113415 INFO nspanel-1: Sending MQTT Message: pageType~cardGrid
2023-01-24 13:46:13.117271 WARNING nspanel-1: ------------------------------------------------------------
2023-01-24 13:46:13.117521 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2023-01-24 13:46:13.117710 WARNING nspanel-1: Worker Ags: {'id': 'cc3f4420d4134926af07442f9ecf5f60', 'name': 'nspanel-1', 'objectid': 'da6b9352e6464e6ea67ee6479a3a36cb', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f3bfcb21ab0>>, 'data': {'topic': 'tele/tasmota_0DBF2C/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,49,us-l"}'}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'topic': 'tele/tasmota_0DBF2C/RESULT', '__thread_id': 'thread-5'}}
2023-01-24 13:46:13.117889 WARNING nspanel-1: ------------------------------------------------------------
2023-01-24 13:46:13.118231 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 40, in mqtt_event_callback
    self._controller.startup()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 44, in startup
    self._pages_gen.render_card(self._current_card)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 688, in render_card
    return
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 403, in generate_entities_page
    dest_temp2   = int(dest_temp2*10)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 264, in generate_entities_item
    icon_up   = get_action_icon(ha_type=entityType, action="open", device_class=device_class)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py", line 186, in get_icon
    if ha_type == "script":
NameError: name 'state' is not defined
2023-01-24 13:46:13.118395 WARNING nspanel-1: ------------------------------------------------------------
2023-01-24 13:46:13.166245 INFO nspanel-1: MQTT callback for: {'topic': 'tele/tasmota_0DBF2C/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":"8"}'}
2023-01-24 13:46:13.166988 INFO nspanel-1: Update Pre-Check sucessful Tasmota Driver Version: 8 Panel Version: 49
2023-01-24 13:46:43.958269 INFO AppDaemon: Reading config
2023-01-24 13:46:43.990445 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2023-01-24 13:46:43.996886 INFO AppDaemon: Found 7 total apps
```


The weather screensaver now looks incomplete...
![IMG_1507](https://user-images.githubusercontent.com/58234/214382168-6de61266-fb27-43a3-b325-1fb474ad1d38.JPG)


and when I click on the screen I get the same blank display..
![IMG_1508](https://user-images.githubusercontent.com/58234/214382224-3a5022c7-e600-4af0-b7f9-b73d1339274b.JPG)





(

**Comment by joBr99** [comment]
You need to restart the AppDaemon Addon not the Nspanel and also not HomeAssistant. Go to the place where you also get the logs and restart the addon.

**Comment by johntdyer** [comment]
ok, but I did just find out one thing...  It works w/o the icon: config

## Working:
```
- type: cardGrid
  title: Test Grid Card
  entities:
    - entity: service.cover.toggle
      status: cover.one_car_garage_door
      color: '{{iif(states("cover.one_car_garage_door")=="open", "[255,0,0]", "[0,255,0]")}}'
      data:
        entity_id: cover.one_car_garage_door

```

## not working
```
- type: cardGrid
  title: Test Grid Card
  entities:
    - entity: service.cover.toggle
      status: cover.one_car_garage_door
      color: '{{iif(states("cover.one_car_garage_door")=="open", "[255,0,0]", "[0,255,0]")}}'
      icon:
        open: mdi:garage-open
        closed: mdi:garage-lock
      data:
        entity_id: cover.one_car_garage_door

```

restarting now

**Comment by johntdyer** [comment]
Works like a charm now !

**Comment by joBr99** [comment]
also this should wo, no need to use templates there

```
- type: cardGrid
  title: Test Grid Card
  entities:
    - entity: service.cover.toggle
      status: cover.one_car_garage_door
      color:
        open: [255,0,0]
        closed: [0,255,0]
      icon:
        open: mdi:garage-open
        closed: mdi:garage-lock
      data:
        entity_id: cover.one_car_garage_door

```

**Comment by johntdyer** [comment]
Yea, I changed this.... but I am seemingly having an issue w/ service.light.toggle entities and inability to change their icon... new issue ?
