### ISSUE TITLE
[Help] Waiting for content

### ISSUE THREAD

**Issue by KrystianIOS** [joBr99/nspanel-lovelace-ui#684]
hi, i have an another issue with waiting for content. I do everything like in faq. I have no clue whats wrong...
AppDeamon logs looks like that:

![Zrzut ekranu z 2023-01-08 19-01-37](https://user-images.githubusercontent.com/80451824/211211601-8c7ca5f2-4f19-4a9a-8641-236bcf147c30.png)

Under some screens with configs and mqqt settings. Password deleted for known reasons.

![Zrzut ekranu z 2023-01-08 18-58-14](https://user-images.githubusercontent.com/80451824/211211471-539463de-3bb1-4c68-af4e-66d5678ea1c7.png)
![Zrzut ekranu z 2023-01-08 18-59-53](https://user-images.githubusercontent.com/80451824/211211524-04a197f7-f129-43af-9dff-76183270c87f.png)
![Zrzut ekranu z 2023-01-08 18-59-12](https://user-images.githubusercontent.com/80451824/211211529-132c07c0-9f01-4ec8-a646-1a4c734e41b1.png)

Does any1 know whats wrong?

**Comment by joBr99** [comment]
There's something wrong with our MQTT Configuration in AppDaemon. Without the log output right after restarting appdaemon I cannot tell you more. Also check the log of your mqtt broker.

**Comment by KrystianIOS** [comment]
> There's something wrong with our MQTT Configuration in AppDaemon. Without the log output right after restarting appdaemon I cannot tell you more. Also check the log of your mqtt broker.

Maybe, but have no idea whats wrong with configuration. Whole log output after restarting ha:

2023-01-08 19:43:08.423320 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:13.432327 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:18.442223 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:23.456973 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:28.470775 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:30.410249 WARNING HASS: Error getting services - retrying
Task exception was never retrieved
future: <Task finished name='Task-660055' coro=<HassPlugin.run_hass_service_check() done, defined at /usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py:783> exception=ClientResponseError(RequestInfo(url=URL('http://supervisor/core/api/services'), method='GET', headers=<CIMultiDictProxy('Host': 'supervisor', 'Authorization': 'Bearer dd41b119f63b221346d2f41e605b596b602f3ba46af7ecb5c06d34c3cfa8bcc666cf027f69a4d50adc8b2a0e51f26c85cc4d756076bd913d', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.1')>, real_url=URL('http://supervisor/core/api/services')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '16', 'Date': 'Sun, 08 Jan 2023 18:43:30 GMT', 'Server': 'Python/3.10 aiohttp/3.8.3')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 792, in run_hass_service_check
    hass_services = await self.get_hass_services()
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 754, in get_hass_services
    r.raise_for_status()
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2023-01-08 19:43:33.483079 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:38.644962 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:44.228596 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 19:43:51.515554 INFO HASS: Connected to Home Assistant 2022.11.3
2023-01-08 19:43:52.111440 INFO HASS: Evaluating startup conditions
2023-01-08 19:43:52.146795 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-08 19:43:52.147283 INFO HASS: All startup conditions met
2023-01-08 19:43:52.202947 INFO AppDaemon: Processing restart for HASS
2023-01-08 19:43:52.203492 INFO AppDaemon: Terminating nspanel-1
2023-01-08 19:43:52.204775 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-01-08 19:43:52.212405 INFO nspanel-1: Starting
2023-01-08 19:43:52.218150 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-01-08 19:43:52.221326 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanell/RESULT', 'panelSendTopic': 'cmnd/nspanell/CustomSend'}
2023-01-08 19:43:52.225156 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanell/RESULT', 'panelSendTopic': 'cmnd/nspanell/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'homeButton': False, 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-01-08 19:43:52.230247 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 19:43:52.232192 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-01-08 19:43:52.233633 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 19:43:52.235202 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2023-01-08 19:43:52.236305 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 19:44:03.542513 INFO HASS: Registering new service ffmpeg/start
2023-01-08 19:44:03.545143 INFO HASS: Registering new service ffmpeg/stop
2023-01-08 19:44:03.547652 INFO HASS: Registering new service ffmpeg/restart


here is also tasmota console screenshot
![Zrzut ekranu z 2023-01-08 19-45-51](https://user-images.githubusercontent.com/80451824/211213444-e7572c4b-14a8-4323-aa90-ec6058853f49.png)
![Zrzut ekranu z 2023-01-08 18-58-14](https://user-images.githubusercontent.com/80451824/211213522-970ce55a-f302-428f-b0a8-ccb93849c940.png)

![Zrzut ekranu z 2023-01-08 19-44-50](https://user-images.githubusercontent.com/80451824/211213462-abe9c37f-de00-4615-a4d5-8f791f82f076.png)

**Comment by joBr99** [comment]
okay, so tasmota is also not able to reach your mqtt broker?

"connect failed to 192.168.1.17"

where do you have your homeassistant installed?
where and what mqtt broker do you have installed?

**Comment by KrystianIOS** [comment]
> okay, so tasmota is also not able to reach your mqtt broker?
> 
> "connect failed to 192.168.1.17"
> 
> where do you have your homeassistant installed? where and what mqtt broker do you have installed?

Homeasistant is installed on docker.
Mosquitto broker installed thu addons store.

**Comment by joBr99** [comment]
how do you install moquitto though addon store if you have installed homeassistant on docker?

HomeAssistant on docker doesn't have support for add-ons

> Add-ons are only available if you've used the Home Assistant Operating System or Home Assistant Supervised [installation](https://www.home-assistant.io/installation) method. If you installed Home Assistant using any other method then you cannot use add-ons. Often you can achieve the same manually, refer to the documentation by the vendor of the application you'd like to install.

https://www.home-assistant.io/addons/

**Comment by KrystianIOS** [comment]
i just used the tutorial on yt, and i do have addons, But it change anythning at all?

**Comment by janprive** [comment]
When Home-Assistant runs in docker other programs like appdaemon  and mqtt must run in their own docker-containers too! It is possible but is is complicated! Best and by far easiest is Home Assistant Operating System or Home Assistant Supervised.

**Comment by KrystianIOS** [comment]
so... i change the mqtt broker cfg and also these in tasmota settings and i think it connected but still i have waiting for content...
![Zrzut ekranu z 2023-01-08 20-41-33](https://user-images.githubusercontent.com/80451824/211215631-bf31876c-df27-45c5-a655-a7bee5a0a5de.png)

**Comment by joBr99** [comment]
you've changed the full topic in tasmota documentation says clearly that you shouldn't do this unless you know what it does and what the implications are


> Please leave the Full Topic as it is in default configuration (and on the screenshot).
https://docs.nspanel.pky.eu/configure_mqtt/

**Comment by KrystianIOS** [comment]
ok, so i changed full topic as you said, and now i have connection to mqtt. But it still wont load screen cuz "waiting for content". here is new screenshots.

Tasmota mqtt cfg: 
![Zrzut ekranu z 2023-01-08 21-12-02](https://user-images.githubusercontent.com/80451824/211216940-bd7014de-153d-4fdc-bbb8-d2718b22fb3e.png)

tasmota console logs:
![Zrzut ekranu z 2023-01-08 21-13-06](https://user-images.githubusercontent.com/80451824/211216957-915e6e52-17a5-45c3-a295-f88b636e0010.png)

mqtt broker logs:
![Zrzut ekranu z 2023-01-08 21-12-16](https://user-images.githubusercontent.com/80451824/211216990-a02f8336-b37e-4f9e-826e-df4f3fc977f4.png)

apps.yaml:
![Zrzut ekranu z 2023-01-08 21-12-25](https://user-images.githubusercontent.com/80451824/211217010-821f046e-0f74-4d4c-917e-de4482660050.png)

appdeamon.yaml:
![Zrzut ekranu z 2023-01-08 21-12-36](https://user-images.githubusercontent.com/80451824/211217047-aa1541c4-fb71-48ae-8716-11b393ec8017.png)

and appdeaon logs: 

2023-01-08 21:04:11.863404 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 21:04:59.169817 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:04.191249 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:09.199727 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:14.630108 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:19.654592 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:24.666982 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:29.680467 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:35.926936 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2023-01-08 21:05:43.851146 INFO HASS: Connected to Home Assistant 2022.11.3
2023-01-08 21:05:44.253251 INFO HASS: Evaluating startup conditions
2023-01-08 21:05:44.273204 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-08 21:05:44.275018 INFO HASS: All startup conditions met
2023-01-08 21:05:44.378968 INFO AppDaemon: Processing restart for HASS
2023-01-08 21:05:44.379576 INFO AppDaemon: Terminating nspanel-1
2023-01-08 21:05:44.381145 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-01-08 21:05:44.387488 INFO nspanel-1: Starting
2023-01-08 21:05:44.388786 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-01-08 21:05:44.391630 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanell/RESULT', 'panelSendTopic': 'cmnd/nspanell/CustomSend'}
2023-01-08 21:05:44.394005 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanell/RESULT', 'panelSendTopic': 'cmnd/nspanell/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'homeButton': False, 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-01-08 21:05:44.397103 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 21:05:44.397564 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-01-08 21:05:44.397905 WARNING nspanel-1: ------------------------------------------------------------
2023-01-08 21:05:44.398626 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2023-01-08 21:05:44.398989 WARNING nspanel-1: ------------------------------------------------------------


**Im new in that so im sorry if something is incomprehensible for me.**

**Comment by joBr99** [comment]
There's still something wrong with your MQTT configuration in appdaemon.yaml.

You need to fix that, as long as you are getting this error in the log it won't work 
`AttributeError: 'NoneType' object has no attribute 'mqtt_publish'`

**Comment by joBr99** [comment]
I don't know could also be the wrong IP Address. 

It sound's like you have a really uncommon setup of homeassistant and I do not have any details about it.

**Comment by KrystianIOS** [comment]
> I don't know could also be the wrong IP Address.
> 
> It sound's like you have a really uncommon setup of homeassistant and I do not have any details about it.

yea, i know that...
i used https://github.com/home-assistant/supervised-installer to install ha supervised on the debian.
This debian terminal ip is: 192.168.1.17  / homeassistant: 172.30.32.1  / nspanel tasmota: 192.168.1.4


it looks like nspanel is conneting to mqtt, but appdeamon wont.
`AttributeError: 'NoneType' object has no attribute 'mqtt_publish`
i checked so many times the appdeamon.yaml and i cant figure whats wrong.

in addition i dont know what to add more cuz i dont have clue whats wrong. I think that i already sent all i can.

**Comment by joBr99** [comment]
Why are you not just using HomeAssistant OS?

Did you try to use the IP Address of your mosquitto container instead of 192.168.1.17 in appdaemon.yaml?

**Comment by KrystianIOS** [comment]
> Why are you not just using HomeAssistant OS?
> 
> Did you try to use the IP Address of your mosquitto container instead of 192.168.1.17 in appdaemon.yaml?

at first I didn't want to install home assistant os because I wanted to use thermal as well as a desktop but I have more and more reasons to install it anyway. 

I probably know thats stupid question but where i can find the ip adress of my mosquitto container?

**Comment by joBr99** [comment]
well, how do you get the ip address of your homeassistant container?

**Comment by KrystianIOS** [comment]
> well, how do you get the ip address of your homeassistant container?

by `docker inspect homeassistant` in the terminal (cmd)

**Comment by joBr99** [comment]
why are you not doing the same with your mosquitto container?

**Comment by KrystianIOS** [comment]
> why are you not doing the same with your mosquitto container?
> 
> on homeassistant os you can just use "core-mosquitto.local.hass.io" which will resolve to your mosquitto container, but that proably doesn't apply to this setup.

yea as i expected it shows me the same ip as the homeassistant.
ill install homeassistant os tomorrow, and maybe it will be so much easier.

**Comment by joBr99** [comment]
if you have a host that you want to use for more than homeassistant install proxmox on it and create a virtual machine for HA OS

**Comment by KrystianIOS** [comment]
Alright. I installed ha os, configure all once more, and **it works!** I think it was the IP and previous instaltion it self was to complicated where i cannot find correct IP address. 


**Thank you so much for your help and time!**
