### ISSUE TITLE
[BUG] AppDaemon fails to initialize app. AttributeError: 'NoneType' object has no attribute 'mqtt_publish'

### ISSUE THREAD

**Issue by beanian** [joBr99/nspanel-lovelace-ui#713]
### PROBLEM DESCRIPTION
AppDaemon fails to start the nspanel-1 app

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
hello_world:
  module: hello
  class: HelloWorld
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel/RESULT"
    panelSendTopic: "cmnd/nspanel/CustomSend"
    model: eu



```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.11.0-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 32.7 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.10/site-packages (from babel) (2021.3)
Installing collected packages: babel
Successfully installed babel-2.11.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:23:58] INFO: Starting AppDaemon...
2023-01-25 17:24:00.126663 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2023-01-25 17:24:00.126764 INFO AppDaemon: Python version is 3.10.9
2023-01-25 17:24:00.126834 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-01-25 17:24:00.126906 INFO AppDaemon: Added log: AppDaemon
2023-01-25 17:24:00.126987 INFO AppDaemon: Added log: Error
2023-01-25 17:24:00.127068 INFO AppDaemon: Added log: Access
2023-01-25 17:24:00.127135 INFO AppDaemon: Added log: Diag
2023-01-25 17:24:00.182459 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-01-25 17:24:00.259979 INFO HASS: HASS Plugin Initializing
2023-01-25 17:24:00.260092 INFO HASS: HASS Plugin initialization complete
2023-01-25 17:24:00.260258 INFO AppDaemon: Loading Plugin mqtt using class MqttPlugin from module mqttplugin
2023-01-25 17:24:00.290550 INFO mqtt: MQTT Plugin Initializing
2023-01-25 17:24:00.290655 INFO mqtt: Using 'appdaemon/status' as Will Topic
2023-01-25 17:24:00.290734 INFO mqtt: Using 'appdaemon/status' as Birth Topic
2023-01-25 17:24:00.291050 INFO AppDaemon: Initializing HTTP
2023-01-25 17:24:00.291226 INFO AppDaemon: Using 'ws' for event stream
2023-01-25 17:24:00.292808 INFO AppDaemon: Starting API
2023-01-25 17:24:00.294315 INFO AppDaemon: Starting Admin Interface
2023-01-25 17:24:00.294519 INFO AppDaemon: Starting Dashboards
2023-01-25 17:24:00.301373 INFO HASS: Connected to Home Assistant 2023.1.6
2023-01-25 17:24:00.307205 INFO mqtt: Connected to Broker at URL 192.168.1.73:1883
2023-01-25 17:24:00.309367 INFO AppDaemon: Got initial state from namespace mqtt
2023-01-25 17:24:00.309645 INFO mqtt: MQTT Plugin initialization complete
2023-01-25 17:24:00.312953 INFO AppDaemon: App 'hello_world' added
2023-01-25 17:24:00.313801 INFO AppDaemon: App 'nspanel-1' added
2023-01-25 17:24:00.314334 INFO AppDaemon: Found 2 total apps
2023-01-25 17:24:00.314703 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2023-01-25 17:24:00.315453 INFO AppDaemon: Running on port 5050
2023-01-25 17:24:00.338927 INFO HASS: Evaluating startup conditions
2023-01-25 17:24:00.344083 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-25 17:24:00.344240 INFO HASS: All startup conditions met
2023-01-25 17:24:00.374219 INFO AppDaemon: Got initial state from namespace default
2023-01-25 17:24:02.321180 INFO AppDaemon: Scheduler running in realtime
2023-01-25 17:24:02.325372 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-01-25 17:24:02.326025 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-01-25 17:24:02.326589 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-01-25 17:24:02.327186 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-01-25 17:24:02.327865 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-01-25 17:24:02.328578 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-01-25 17:24:02.343752 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2023-01-25 17:24:02.373211 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-01-25 17:24:02.438618 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-01-25 17:24:02.439187 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-01-25 17:24:02.439917 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-01-25 17:24:02.440686 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-01-25 17:24:02.441421 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-01-25 17:24:02.441912 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-01-25 17:24:02.442319 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-01-25 17:24:02.442684 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-01-25 17:24:02.443063 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-01-25 17:24:02.443459 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-01-25 17:24:02.443830 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-01-25 17:24:02.444177 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2023-01-25 17:24:02.444899 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-01-25 17:24:02.470334 INFO hello_world: Hello from AppDaemon
2023-01-25 17:24:02.470792 INFO hello_world: You are now ready to run Apps!
2023-01-25 17:24:02.471979 INFO nspanel-1: Starting
2023-01-25 17:24:02.472613 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-01-25 17:24:02.473390 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'model': 'eu'}
2023-01-25 17:24:02.473830 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'homeButton': False, 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-01-25 17:24:02.474433 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 17:24:02.474561 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-01-25 17:24:02.474656 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 17:24:02.475296 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2023-01-25 17:24:02.475420 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 17:24:02.475785 INFO AppDaemon: App initialization complete

```

### TO REPRODUCE
Restart App Daemon

### EXPECTED BEHAVIOUR
App Daemon start the nspanel-1 app

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._
![image](https://user-images.githubusercontent.com/930359/214636940-e774e34d-d44e-4b0d-b5bd-0e37c69ba7a1.png)

### ADDITIONAL CONTEXT
I can see the panel successfully post messages to my MQTT broker. I can also see AppDaemon successfully post its "online" message to a topic.
Here is my MQTT configuration in AppDaemon
`---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Dublin
  plugins:
    HASS:
      type: hass
    mqtt:
      type: mqtt
      namespace: mqtt
      verbose: True
      client_id: "appdaemon"
      client_host: 192.168.1.73
      client_port: 1883
      client_user: "poxbottle"
      client_password: "XXXXX"
      client_topics: NONE
      verify_cert: false
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:`

### PANEL / FIRMWARE VERION
EU

**Comment by joBr99** [comment]
Can you pleast post your appdaemon.yaml?

Also which AppDaemon Version are you using?

**Comment by beanian** [comment]
Here is my AppDaemon.yaml. I'm using the Home Assistant OS version of AppDaemon which is  v0.11.0
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Dublin
  plugins:
    HASS:
      type: hass
    mqtt:
      type: mqtt
      namespace: mqtt
      verbose: True
      client_id: appdaemon
      client_host: 192.168.1.73
      client_port: 1883
      client_user: "poxbottle"
      client_password: "XXXX"
      client_topics: NONE
      verify_cert: false
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

**Comment by joBr99** [comment]
Hmm, strange looks fine, I'm not really sure where the `Unknown Plugin Configuration` Error is coming from.


Can you remove the addional parameters you have in the MQTT section and restart the addon afterwards?


```yaml
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.75.30
      client_port: 1883
      client_user: "mqttuser"
      client_password: "xxx"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

**Comment by beanian** [comment]
I had added them in whilst troubleshooting this issue. My appdaemon.yaml now looks like:
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Dublin
  plugins:
    HASS:
      type: hass
    mqtt:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.73
      client_port: 1883
      client_user: "poxbottle"
      client_password: "XXXX"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```

and the log output remains the same:
```
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.11.0-py3-none-any.whl (9.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 33.9 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2015.7 in /usr/lib/python3.10/site-packages (from babel) (2021.3)
Installing collected packages: babel
Successfully installed babel-2.11.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:01:15] INFO: Starting AppDaemon...
2023-01-25 18:01:17.174279 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2023-01-25 18:01:17.174393 INFO AppDaemon: Python version is 3.10.9
2023-01-25 18:01:17.174471 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-01-25 18:01:17.174559 INFO AppDaemon: Added log: AppDaemon
2023-01-25 18:01:17.174651 INFO AppDaemon: Added log: Error
2023-01-25 18:01:17.174728 INFO AppDaemon: Added log: Access
2023-01-25 18:01:17.174806 INFO AppDaemon: Added log: Diag
2023-01-25 18:01:17.229906 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-01-25 18:01:17.308595 INFO HASS: HASS Plugin Initializing
2023-01-25 18:01:17.308726 INFO HASS: HASS Plugin initialization complete
2023-01-25 18:01:17.308904 INFO AppDaemon: Loading Plugin mqtt using class MqttPlugin from module mqttplugin
2023-01-25 18:01:17.340199 INFO mqtt: MQTT Plugin Initializing
2023-01-25 18:01:17.340329 INFO mqtt: Using 'appdaemon/status' as Will Topic
2023-01-25 18:01:17.340410 INFO mqtt: Using 'appdaemon/status' as Birth Topic
2023-01-25 18:01:17.340736 INFO AppDaemon: Initializing HTTP
2023-01-25 18:01:17.340918 INFO AppDaemon: Using 'ws' for event stream
2023-01-25 18:01:17.342523 INFO AppDaemon: Starting API
2023-01-25 18:01:17.344055 INFO AppDaemon: Starting Admin Interface
2023-01-25 18:01:17.344270 INFO AppDaemon: Starting Dashboards
2023-01-25 18:01:17.351447 INFO HASS: Connected to Home Assistant 2023.1.6
2023-01-25 18:01:17.355332 INFO mqtt: Connected to Broker at URL 192.168.1.73:1883
2023-01-25 18:01:17.359382 INFO AppDaemon: Got initial state from namespace mqtt
2023-01-25 18:01:17.359672 INFO mqtt: MQTT Plugin initialization complete
2023-01-25 18:01:17.362766 INFO AppDaemon: App 'hello_world' added
2023-01-25 18:01:17.363482 INFO AppDaemon: App 'nspanel-1' added
2023-01-25 18:01:17.364050 INFO AppDaemon: Found 2 total apps
2023-01-25 18:01:17.364324 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2023-01-25 18:01:17.364930 INFO AppDaemon: Running on port 5050
2023-01-25 18:01:17.389084 INFO HASS: Evaluating startup conditions
2023-01-25 18:01:17.394137 INFO HASS: Startup condition met: hass state=RUNNING
2023-01-25 18:01:17.394310 INFO HASS: All startup conditions met
2023-01-25 18:01:17.423566 INFO AppDaemon: Got initial state from namespace default
2023-01-25 18:01:19.371025 INFO AppDaemon: Scheduler running in realtime
2023-01-25 18:01:19.375389 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-01-25 18:01:19.376040 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-01-25 18:01:19.376664 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-01-25 18:01:19.377290 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-01-25 18:01:19.377970 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-01-25 18:01:19.378696 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-01-25 18:01:19.382852 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2023-01-25 18:01:19.396745 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-01-25 18:01:19.460308 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-01-25 18:01:19.460779 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-01-25 18:01:19.461197 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-01-25 18:01:19.461572 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-01-25 18:01:19.461973 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-01-25 18:01:19.462341 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-01-25 18:01:19.462706 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-01-25 18:01:19.463106 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-01-25 18:01:19.463488 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-01-25 18:01:19.463852 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-01-25 18:01:19.464222 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-01-25 18:01:19.464528 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2023-01-25 18:01:19.465221 INFO AppDaemon: Initializing app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-01-25 18:01:19.491262 INFO hello_world: Hello from AppDaemon
2023-01-25 18:01:19.491734 INFO hello_world: You are now ready to run Apps!
2023-01-25 18:01:19.493130 INFO nspanel-1: Starting
2023-01-25 18:01:19.493480 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-01-25 18:01:19.494239 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'model': 'eu'}
2023-01-25 18:01:19.494682 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspanel/RESULT', 'panelSendTopic': 'cmnd/nspanel/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'homeButton': False, 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-01-25 18:01:19.495301 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 18:01:19.495429 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-01-25 18:01:19.495526 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 18:01:19.496180 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2023-01-25 18:01:19.496303 WARNING nspanel-1: ------------------------------------------------------------
2023-01-25 18:01:19.496673 INFO AppDaemon: App initialization complete
```

**Comment by joBr99** [comment]
I've never seen this error in combination with successful homeassistent and mqtt authentication, normally it's just something with mqtt not authenticated.

**Comment by beanian** [comment]
I have managed to get past this issue by changing the line
`apis.mqtt_api = self.get_plugin_api("MQTT")`
to
`apis.mqtt_api = self.get_plugin_api("mqtt")`

Using lowercase immediately resolved the issue. No idea why or if anything has changed here recently

**Comment by joBr99** [comment]
interesting, can you try `namespace: MQTT` in appdaemon.yaml?

**Comment by beanian** [comment]
I updated my appdaemon.yaml to the below and rolled back the code change I made and it is working as expected now. Note the uppercased MQTT for the plugin section for MQTT. I had tried uppercasing the type and namespace previously but never tried the key section name itself. 
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Dublin
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.1.73
      client_port: 1883
      client_user: "poxbottle"
      client_password: "Myth6984"
      client_topics: NONE
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
```

**Comment by joBr99** [comment]
it's still lowercase mqtt in your example o.O

**Comment by joBr99** [comment]
ah you mean the name of the mqtt section lol; didn't pay attention to this

**Comment by beanian** [comment]
![image](https://user-images.githubusercontent.com/930359/214658209-3d94cbc3-b7c9-4fd9-a4fb-eb33c59e9c1e.png)

See the above image, the section name is case sensitive it appears!
