### ISSUE TITLE
Time Format in forecast

### ISSUE THREAD

**Issue by mikosoft83** [joBr99/nspanel-lovelace-ui#750]
### FEATURE DESCRIPTION
Display time instead of day for hourly weather on screensaver (as it was pre 3.9 update)

Previous version (shows "11:00", "12:00" etc):
![image](https://user-images.githubusercontent.com/63317931/216783475-30347d43-d382-4e58-9c1e-b971acb3c7ed.png)

Current version (shows "so" as in "sobota" [Samstag]):
![image](https://user-images.githubusercontent.com/63317931/216783457-2a9e2854-53c5-47d5-99c7-011114320c9a.png)

### ADDITIONAL CONTEXT

I tried templating the name but it results in an error:

```
2023-02-04 19:15:00.229905 WARNING nspanel-hallway: Unexpected error in worker for App nspanel-hallway:
2023-02-04 19:15:00.231165 WARNING nspanel-hallway: Worker Ags: {'id': '93e20721e0264828b8519363ef449077', 'name': 'nspanel-hallway', 'objectid': '2e453d9d2cc744ea9298ba4dc6048483', 'type': 'state', 'function': <bound method LuiController.state_change_callback of <luibackend.controller.LuiController object at 0x74a9d460>>, 'attribute': 'all', 'entity': 'sensor.outside_north_temperature', 'new_state': {'entity_id': 'sensor.outside_north_temperature', 'state': '-1.4', 'attributes': {'unit_of_measurement': '°C', 'icon': 'mdi:thermometer', 'friendly_name': 'Outside north temperature'}, 'last_changed': '2023-02-04T18:14:59.912035+00:00', 'last_updated': '2023-02-04T18:14:59.912035+00:00', 'context': {'id': '01GRET701KTFMJJZ0Q87H63N4Q', 'parent_id': None, 'user_id': None}}, 'old_state': {'entity_id': 'sensor.outside_north_temperature', 'state': '-0.9', 'attributes': {'unit_of_measurement': '°C', 'icon': 'mdi:thermometer', 'friendly_name': 'Outside north temperature'}, 'last_changed': '2023-02-04T15:59:59.049597+00:00', 'last_updated': '2023-02-04T15:59:59.049597+00:00', 'context': {'id': '01GREJFS1Y522RPYX5Z3SV3VXW', 'parent_id': None, 'user_id': None}}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': 'all', '__thread_id': 'thread-1'}}
2023-02-04 19:15:00.232522 WARNING nspanel-hallway: ------------------------------------------------------------
2023-02-04 19:15:00.235109 WARNING nspanel-hallway: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 161, in state_change_callback
    self._pages_gen.render_card(self._current_card, send_page_type=False)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 717, in render_card
    self.update_screensaver_weather(theme)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 139, in update_screensaver_weather
    item_str += self.generate_entities_item(item, "cardEntities")
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 364, in generate_entities_item
    name = babel.dates.format_date(fdate, dateformat, locale=self._locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 730, in format_date
    return pattern.apply(date, locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1308, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1305, in __mod__
    return self.format % other
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1360, in __getitem__
    return self.format(self.value.second, num)
AttributeError: 'datetime.date' object has no attribute 'second'
```

### PANEL / FIRMWARE VERION
EU, backend 3.9.4, LUI 3.9.0

**Comment by joBr99** [comment]
Hey, the way to do this in the newest version is through templating, however the templates for the weather forecast are working a bit differently. You need to supply see the example here.

https://github.com/joBr99/nspanel-lovelace-ui/pull/667

I need to add documentation for this.

**Comment by mikosoft83** [comment]
Ah, okay, I think I understand. Is that standard python format for date/time?

**Comment by joBr99** [comment]
Depends, if you have babel installed see this:

https://babel.pocoo.org/en/latest/dates.html?highlight=name%20of%20day#date-fields

**Comment by mikosoft83** [comment]
I do have babel, I tried "HH:mm" but it fails exactly the same. I tried your example from #667 , I even tried babel syntax with % but nothing works

**Comment by joBr99** [comment]
I guess it's "H:m"

**Comment by mikosoft83** [comment]
It should work either way, number of letter just denotes number of digits in format (H:M would result in 1:0 and HH:mm in 01:00). Anyway, I tried that but still the same.

**Comment by joBr99** [comment]
Please post the error u're getting in the log

**Comment by mikosoft83** [comment]
Seems very similar to what I posted above:

```
2023-02-04 19:53:31.451734 WARNING nspanel-hallway: Unexpected error in worker for App nspanel-hallway:
2023-02-04 19:53:31.453028 WARNING nspanel-hallway: Worker Ags: {'id': '9d5a3bcce00e438787914dda63f5e423', 'name': 'nspanel-hallway', 'objectid': 'e33d62d30fd542c88aad35bc94b1f011', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x73fd70a0>>, 'data': {'topic': 'tele/nspanel-hallway/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,49,eu"}'}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'topic': 'tele/nspanel-hallway/RESULT', '__thread_id': 'thread-1'}}
2023-02-04 19:53:31.454344 WARNING nspanel-hallway: ------------------------------------------------------------
2023-02-04 19:53:31.456834 WARNING nspanel-hallway: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 40, in mqtt_event_callback
    self._controller.startup()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 44, in startup
    self._pages_gen.render_card(self._current_card)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 717, in render_card
    self.update_screensaver_weather(theme)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 139, in update_screensaver_weather
    item_str += self.generate_entities_item(item, "cardEntities")
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py", line 364, in generate_entities_item
    name = babel.dates.format_date(fdate, dateformat, locale=self._locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 730, in format_date
    return pattern.apply(date, locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1308, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1305, in __mod__
    return self.format % other
  File "/usr/lib/python3.10/site-packages/babel/dates.py", line 1349, in __getitem__
    return self.format(self.value.hour, num)
AttributeError: 'datetime.date' object has no attribute 'hour'
```

**Comment by joBr99** [comment]
Try to replace `format_date` with `format_datetime` in pages.py

https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/pages.py#L376

And restart Appdaemon afterwards.

**Comment by mikosoft83** [comment]
Yep, that fixed it!

![image](https://user-images.githubusercontent.com/63317931/216785488-fc8512fd-c8ed-45ae-b463-025d2683e0b8.png)
