### ISSUE TITLE
[BUG] Unlock card not working anymore in dev-branch

### ISSUE THREAD

**Issue by EddyK69** [joBr99/nspanel-lovelace-ui#756]
### PROBLEM DESCRIPTION
I'm on the latest dev-version 86b8e63, and the Unlock Card doesn't seem to work anymore. After typing the code and 'Unlock' nothing happens.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-test:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel_test/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel_test/CustomSend"
    model: eu
    sleepTimeout: 10
    screensaver:
      defaultCard: navigate.main
      entities:
        - entity: delete
    cards:
      - type: cardGrid
        key: main
        title: Mainpage
        entities:
           - entity: navigate.lock
    hiddenCards:
      - type: cardUnlock
        title: Lock
        key: lock
        pin: 1234
        destination: navigate.sub
      - type: cardGrid
        key: sub
        title: Subpage
        entities:
           - entity: light.bedroom
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-02-09 12:01:29.897131 INFO nspanel-test: Sending MQTT Message: pageType~cardGrid
2023-02-09 12:01:29.926936 INFO nspanel-test: Sending MQTT Message: entityUpd~Mainpage~delete~~~~~~delete~~~~~~button~navigate.lock~���~17299~Lock~Press
2023-02-09 12:01:31.242910 INFO nspanel-test: MQTT callback for: {'topic': 'tele/tasmota_nspanel_1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,navigate.lock,button"}'}
2023-02-09 12:01:31.245651 INFO nspanel-test: Received Message from Screen: event,buttonPress2,navigate.lock,button
2023-02-09 12:01:31.248774 INFO nspanel-test: Button Press Event; entity_id: navigate.lock; button_type: button; value: None 
2023-02-09 12:01:31.252503 INFO nspanel-test: Sending MQTT Message: pageType~cardAlarm
2023-02-09 12:01:31.273101 INFO nspanel-test: Sending MQTT Message: entityUpd~Lock~x~navUp~���~65535~~~delete~~~~~~uuid.NUWea18zot~Unlock~cardUnlock-unlock~~~~~~~���~63488~enable~disable~
2023-02-09 12:01:34.883954 INFO nspanel-test: MQTT callback for: {'topic': 'tele/tasmota_nspanel_1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.NUWea18zot,cardUnlock-unlock,1234"}'}
2023-02-09 12:01:34.886758 INFO nspanel-test: Received Message from Screen: event,buttonPress2,uuid.NUWea18zot,cardUnlock-unlock,1234
2023-02-09 12:01:34.889557 INFO nspanel-test: Button Press Event; entity_id: uuid.NUWea18zot; button_type: cardUnlock-unlock; value: 1234 
2023-02-09 12:01:34.890533 WARNING nspanel-test: ------------------------------------------------------------
2023-02-09 12:01:34.891434 WARNING nspanel-test: Unexpected error in worker for App nspanel-test:
2023-02-09 12:01:34.892476 WARNING nspanel-test: Worker Ags: {'id': '90413bab18364b1782f1a1c1d4972ab3', 'name': 'nspanel-test', 'objectid': '6aec5a2a51b44e568ac8efeaa6f37c87', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0xffff9f6e1330>>, 'data': {'topic': 'tele/tasmota_nspanel_1/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.NUWea18zot,cardUnlock-unlock,1234"}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'tele/tasmota_nspanel_1/RESULT', '__thread_id': 'thread-0'}}
2023-02-09 12:01:34.893582 WARNING nspanel-test: ------------------------------------------------------------
2023-02-09 12:01:34.898502 WARNING nspanel-test: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 199, in button_press
    entity_id = entity_config.entityId
AttributeError: 'NoneType' object has no attribute 'entityId'
2023-02-09 12:01:34.899442 WARNING nspanel-test: ------------------------------------------------------------
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION
EU, dev-version

**Comment by joBr99** [comment]
hmm, just tried works fine for me

**Comment by EddyK69** [comment]
Strange; when reverted to 3.9.4 it is working again, but not with the dev-branch

**Comment by EddyK69** [comment]
Did some debuging and it happens to do with code in controller.py
```
    def button_press(self, entity_id, button_type, value):
        apis.ha_api.log(f"Button Press Event; entity_id: {entity_id}; button_type: {button_type}; value: {value} ")
        if entity_id.startswith('uuid'):
            entity_config = self._config._config_entites_table.get(entity_id)
            entity_id = entity_config.entityId
```
The entity.id of the unlock card is passed and not found in the list of entities obviously. If I comment out this if, it works ok. So for unlock-cards this should be skipped in my opinion.

**Comment by EddyK69** [comment]
> hmm, just tried works fine for me

Can you please give me your yaml config, so I can check if it works? My app.yaml is in the info in the bug registration

**Comment by joBr99** [comment]
moved the code ; however didn' test if its working now

**Comment by EddyK69** [comment]
Yep, confirmed that it is working now. Thnx!
