### ISSUE TITLE
[BUG] navItem entity doesn't toggle anymore

### ISSUE THREAD

**Issue by Censored3** [joBr99/nspanel-lovelace-ui#795]
### PROBLEM DESCRIPTION
Since v4.0.4 (or is it v4.0.3 :-)), tapping navItem1 (at least on a cardGrid) with an entity set to a light doesn't toggle it anymore. My navItem2 (which is a navigate. entity) still works.
Swapping them has no effect, seems to be related to the entity.

Worked fine in v3.9.4.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
      - type: cardGrid
        key: living_mode
        title: Living Mode
        navItem1:
          entity: light.living_switch
        navItem2:
          entity: navigate.living_page1
          icon: 'mdi:home'

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
  Log output here:
2023-03-04 13:46:50.371158 INFO nspui-living-nspanel: Sending MQTT Message: entityUpd~Living Mode~light~uuid.LzhRwCwI6f~���~65222~Living Licht: Switch~1~button~navigate.living_page1~���~17299~Living~Klik~switch~switch.living_mode_vollenbak~���~17299~Vollen Bak~0~switch~switch.living_mode_normaal~���~65222~Normaal~1~switch~switch.living_mode_gedimd~���~17299~Gedimd~0~switch~switch.living_mode_cinema~���~17299~Cinema~0~switch~switch.living_mode_nacht~���~17299~Nachtlicht~0
2023-03-04 13:46:51.647097 INFO nspui-living-nspanel: MQTT callback for: {'topic': 'tele/living-nspanel/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.LzhRwCwI6f,button"}'}
2023-03-04 13:46:51.649565 INFO nspui-living-nspanel: Received Message from Screen: event,buttonPress2,uuid.LzhRwCwI6f,button
2023-03-04 13:46:51.651811 INFO nspui-living-nspanel: Button Press Event; entity_id: uuid.LzhRwCwI6f; button_type: button; value: None
```

### EXPECTED BEHAVIOUR
Perform the action on the entity (toggle).

### PANEL / FIRMWARE VERION
EU, current (50)

**Comment by joBr99** [comment]
hey can you checkout the development version (updating to main in HACS and restarting appdaemon)

this should fix it:

https://github.com/joBr99/nspanel-lovelace-ui/commit/006e8d37c155e9fea040dbb6d997fade8f79666a

**Comment by Censored3** [comment]
Too bad :-(

```
2023-03-05 11:43:00.785227 WARNING nspui-living-nspanel: ------------------------------------------------------------
2023-03-05 11:43:00.786267 WARNING nspui-living-nspanel: Unexpected error running initialize() for nspui-living-nspanel
2023-03-05 11:43:00.787194 WARNING nspui-living-nspanel: ------------------------------------------------------------
2023-03-05 11:43:00.789072 WARNING nspui-living-nspanel: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 17, in initialize
    cfg = self._cfg = LuiBackendConfig(self, self.args["config"])
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 167, in __init__
    self.load(config_in)
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 196, in load
    self._config_entites_table = {x.uuid: x for x in self.get_all_entitys()}
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py", line 196, in <dictcomp>
    self._config_entites_table = {x.uuid: x for x in self.get_all_entitys()}
AttributeError: 'dict' object has no attribute 'uuid'
2023-03-05 11:43:00.790732 WARNING nspui-living-nspanel: ------------------------------------------------------------
```

**Comment by joBr99** [comment]
try again :)

**Comment by Censored3** [comment]
Confirmed working!
