### ISSUE TITLE
[BUG] The text “None” is visible below the current time and after the date in screensaver

### ISSUE THREAD

**Issue by saschaludwig** [joBr99/nspanel-lovelace-ui#856]
### PROBLEM DESCRIPTION

The text "None" is visible below the current time and after the date in screensaver

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Provide your apps.yaml (or your config):
```
nspanel-05:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel05/RESULT"
    panelSendTopic: "cmnd/nspanel05/CustomSend"
    sleepTimeout: 20
    sleepBrightness:
      - time: "09:00:00"
        value: 10
      - time: "23:00:00"
        value: 1
    locale: "de_DE"
    screensaver:
      entities:
        - entity: weather.home
        - entity: weather.home
          type: 0
        - entity: weather.home
          type: 1
        - entity: weather.home
          type: 2
        - entity: sensor.fronius_7_inverter_dc_watts
          name: Solar
          icon: mdi:solar-panel-large
    cards:
      - type: cardEntities
        title: Test Karte
        entities:
          - entity: sensor.bewegungsmelder_01_battery
          - entity: scene.wohnzimmer_ein
          - entity: scene.wohnzimmer_aus
          - entity: switch.dhl_drucker_1
      - type: cardQR
        title: Guest Wifi
        qrCode: "WIFI:S:test_ssid;T:WPA;P:test_pw;;"
        entities:
          - entity: iText.test_ssid
            name: Name
            icon: mdi:wifi
          - entity: iText.test_pw
            name: Password
            icon: mdi:key
      - type: cardAlarm
        title: Alarm Test 1
        entity: alarm_control_panel.alarm
      - type: cardMedia
        entity: media_player.musik_raum_2
        name: Küche
      - type: cardMedia
        entity: media_player.musik_raum_1
        name: Badezimmer
      - type: cardThermo
        entity: climate.homematicip_local_00265d89896e38_1
        title: Heizung

```
- [x] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-04-13 15:16:30.778505 INFO nspanel-05: MQTT callback for: {'topic': 'tele/nspanel05/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,startup,50,eu"}'}
2023-04-13 15:16:30.781654 INFO nspanel-05: Received Message from Screen: event,startup,50,eu
2023-04-13 15:16:30.784536 INFO nspanel-05: Sending MQTT Message: X
2023-04-13 15:16:30.793123 INFO nspanel-05: Update Pre-Check failed Tasmota Driver Version: None Panel Version: 50
2023-04-13 15:16:30.796032 INFO nspanel-05: Startup Event
2023-04-13 15:16:30.800689 ERROR HASS: ------------------------------------------------------------
2023-04-13 15:16:30.801769 ERROR HASS: Unexpected error during call_plugin_service()
2023-04-13 15:16:30.802506 ERROR HASS: Service: default.template.render Arguments: {'template': ''}
2023-04-13 15:16:30.803568 ERROR HASS: ------------------------------------------------------------
2023-04-13 15:16:30.805221 ERROR HASS: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 556, in call_plugin_service
    r = await self.session.post(api_url, json=data)
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /api/template
2023-04-13 15:16:30.806126 ERROR HASS: ------------------------------------------------------------
2023-04-13 15:16:30.814925 INFO nspanel-05: Sending MQTT Message: time~15:16~None
2023-04-13 15:16:30.823019 INFO HASS: Previous message repeated 1 times
2023-04-13 15:16:30.823531 ERROR HASS: Unexpected error during call_plugin_service()
2023-04-13 15:16:30.823796 ERROR HASS: Service: default.template.render Arguments: {'template': ''}
2023-04-13 15:16:30.824494 ERROR HASS: ------------------------------------------------------------
2023-04-13 15:16:30.825674 ERROR HASS: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 556, in call_plugin_service
    r = await self.session.post(api_url, json=data)
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /api/template
2023-04-13 15:16:30.827269 ERROR HASS: ------------------------------------------------------------
2023-04-13 15:16:30.833237 INFO nspanel-05: Sending MQTT Message: date~Donnerstag, 13. April 2023None
2023-04-13 15:16:30.840369 INFO nspanel-05: Sending MQTT Message: dimmode~10~100~6371
2023-04-13 15:16:30.851164 INFO nspanel-05: Sending MQTT Message: pageType~screensaver
2023-04-13 15:16:30.866036 INFO nspanel-05: Sending MQTT Message: timeout~20
2023-04-13 15:16:30.913310 INFO nspanel-05: Sending MQTT Message: weatherUpdate~~~���~31728~Forecast Zuhause~10.4��C~~~���~38066~Fr.~13.2��C~~~���~31728~Sa.~11.8��C~~~���~31728~So.~8.7��C~~~���~17299~Solar~1979.5 W
2023-04-13 15:16:30.917225 INFO nspanel-05: Sending MQTT Message: statusUpdate~~~~~~
2023-04-13 15:16:30.929797 INFO nspanel-05: MQTT callback for: {'topic': 'tele/nspanel05/RESULT', 'wildcard': None, 'payload': '{"nlui_driver_version":999}'}
2023-04-13 15:16:30.931867 INFO nspanel-05: Update Pre-Check sucessful Tasmota Driver Version: 999 Panel Version: 50

```

### TO REPRODUCE
Restart NSPanel hardware and wait for screensaver:
"None" is displayed below time and after date

### EXPECTED BEHAVIOUR
No display of "None" strings

### SCREENSHOTS
![23-04-13 15-10-35 2531](https://user-images.githubusercontent.com/12997980/231772469-c85cad39-9b0f-4059-9e59-9d74d6881550.jpg)

### ADDITIONAL CONTEXT
I do see that error in the logfile, but I have no idea on where to fix that or how I am holding this wrong ;-)

### PANEL / FIRMWARE VERSION
EU Panel Version: 50

**Comment by labeltycoon** [comment]
The same here since a few day's. I didn't change anything and it did never show 'None' before.

![nspanel](https://user-images.githubusercontent.com/105174041/231820048-ff760ed9-36d6-4e83-91a2-fff9ed9f3fc3.jpg)

**Comment by NS-Panel** [comment]
I have the same since a few day's and did not change anything.

![nspanel](https://user-images.githubusercontent.com/105174041/231821832-7b0a01e5-5e59-431a-8fdc-6716bb2aae51.jpg)

**Comment by joBr99** [comment]
See #847

You can restore your backup and downgrade to the previous appdaemon version until a fixed version of the addon is released.

(already fixed in development version, they need to release it and then the ha addon needs to be updated aswell)

**Comment by Dattel** [comment]
:-D
