### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by pbranly** [joBr99/nspanel-lovelace-ui#886]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![2023-05-07_17-42](https://user-images.githubusercontent.com/22018509/236687883-3256e210-16f6-42dd-8ed2-e360296cc648.png)

- [ ] Provide your appdaemon.yaml: 
```
appdaemon:
  latitude: 50.6456825
  longitude: 3.152857
  elevation: 28
  time_zone: Europe/Paris
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.1.8:8123
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      cert_verify: True
MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      #client_host: core-mosquitto.local.hass.io # This should work if you are using supervised HomeAssistant; if not use the IP Address instead.
      client_host: 192.168.1.8
      client_port: 1883
      client_user: "xxxxxx"
      client_password: "xxxxxxxxxxxxxxxxxxxxx"
      client_topics: NONE      
http:
  url: http://192.168.1.8:5050
admin:
api:
hadashboard:


```

- [ ] Provide your apps.yaml:
```
hello_world:
  module: hello
  class: HelloWorld
  
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspaneltest/RESULT"
    panelSendTopic: "cmnd/nspaneltest/CustomSend"
    model: us-p


```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
2023-05-07 17:34:28.413046 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui

2023-05-07 17:34:28.419401 INFO AppDaemon: Calling initialize() for hello_world

2023-05-07 17:34:28.555241 INFO hello_world: Hello from AppDaemon

2023-05-07 17:34:28.556477 INFO hello_world: You are now ready to run Apps!

2023-05-07 17:34:28.559119 INFO AppDaemon: Calling initialize() for nspanel-1

2023-05-07 17:34:28.562524 INFO nspanel-1: Starting

2023-05-07 17:34:28.563960 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()

2023-05-07 17:34:28.567524 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspaneltest/RESULT', 'panelSendTopic': 'cmnd/nspaneltest/CustomSend', 'model': 'us-p'}

2023-05-07 17:34:28.569364 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspaneltest/RESULT', 'panelSendTopic': 'cmnd/nspaneltest/CustomSend', 'updateMode': 'auto-notify', 'model': 'us-p', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}

2023-05-07 17:34:28.571521 WARNING nspanel-1: ------------------------------------------------------------

2023-05-07 17:34:28.572150 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1

2023-05-07 17:34:28.572501 WARNING nspanel-1: ------------------------------------------------------------

2023-05-07 17:34:28.575189 WARNING nspanel-1: Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app

    await utils.run_in_executor(self, init)

  File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor

    response = future.result()

  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize

    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")

AttributeError: 'NoneType' object has no attribute 'mqtt_publish'

2023-05-07 17:34:28.575518 WARNING nspanel-1: ------------------------------------------------------------

2023-05-07 17:34:28.576456 INFO AppDaemon: App initialization complete

2023-05-07 17:34:28.717369 INFO AppDaemon: New client Admin Client connected

2023-05-07 17:34:29.925045 INFO AppDaemon: New client Admin Client connected


```

### ADDITIONAL INFORMATION

I use docker version and I see mqtt frames arriving in tasmota console

**Comment by joBr99** [comment]
`AttributeError: 'NoneType' object has no attribute 'mqtt_publish'`

This error happends if there is something wrong with your mqtt configuration of appdaemon, however the error isn't part of the part of the appdaemon log you've posted. Restart the Appdaemon docker container and post the entire startup log.

**Comment by pbranly** [comment]
here it is
Thanks
`    07/05/2023 18:52:51
    2023-05-07 18:52:51.059783 INFO AppDaemon: Previous message repeated 1 times
    07/05/2023 18:52:51
    2023-05-07 18:52:51.060197 INFO AppDaemon: SIGTERM Received
    07/05/2023 18:52:51
    2023-05-07 18:52:51.060503 INFO AppDaemon: AppDaemon is shutting down
    07/05/2023 18:52:51
    2023-05-07 18:52:51.063896 INFO HASS: Disconnecting from Home Assistant
    07/05/2023 18:52:51
    2023-05-07 18:52:51.882725 INFO AppDaemon: Removing module /conf/apps/hello.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.883526 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.884297 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/icons.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.884982 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/config.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.886205 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/apis.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.887068 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/localization.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.887762 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/pages.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.888766 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/theme.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.889719 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.891368 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/helper.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.892197 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/controller.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.892998 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/mqtt.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.893880 INFO AppDaemon: Removing module /conf/apps/nspanel-lovelace-ui/luibackend/updater.py
    07/05/2023 18:52:51
    2023-05-07 18:52:51.895494 INFO AppDaemon: Terminating hello_world
    07/05/2023 18:52:51
    2023-05-07 18:52:51.897769 INFO AppDaemon: Terminating nspanel-1
    07/05/2023 18:52:51
    2023-05-07 18:52:51.901259 INFO AppDaemon: Shutting down webserver
    07/05/2023 18:52:51
    2023-05-07 18:52:51.904241 INFO AppDaemon: Saving all namespaces
    07/05/2023 18:52:51
    2023-05-07 18:52:51.904800 INFO AppDaemon: AppDaemon is stopped.
    07/05/2023 18:52:54
    2023-05-07 18:52:54.187386 INFO AppDaemon: AppDaemon Version 4.4.2 starting
    07/05/2023 18:52:54
    2023-05-07 18:52:54.187656 INFO AppDaemon: Python version is 3.10.11
    07/05/2023 18:52:54
    2023-05-07 18:52:54.187802 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
    07/05/2023 18:52:54
    2023-05-07 18:52:54.187957 INFO AppDaemon: Added log: AppDaemon
    07/05/2023 18:52:54
    2023-05-07 18:52:54.188150 INFO AppDaemon: Added log: Error
    07/05/2023 18:52:54
    2023-05-07 18:52:54.188340 INFO AppDaemon: Added log: Access
    07/05/2023 18:52:54
    2023-05-07 18:52:54.188513 INFO AppDaemon: Added log: Diag
    07/05/2023 18:52:54
    2023-05-07 18:52:54.229689 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
    07/05/2023 18:52:54
    2023-05-07 18:52:54.261326 INFO HASS: HASS Plugin Initializing
    07/05/2023 18:52:54
    2023-05-07 18:52:54.261594 INFO HASS: HASS Plugin initialization complete
    07/05/2023 18:52:54
    2023-05-07 18:52:54.262094 INFO AppDaemon: Initializing HTTP
    07/05/2023 18:52:54
    2023-05-07 18:52:54.262761 INFO AppDaemon: Using 'ws' for event stream
    07/05/2023 18:52:54
    2023-05-07 18:52:54.267982 INFO AppDaemon: Starting API
    07/05/2023 18:52:54
    2023-05-07 18:52:54.272052 INFO AppDaemon: Starting Admin Interface
    07/05/2023 18:52:54
    2023-05-07 18:52:54.272548 INFO AppDaemon: Starting Dashboards
    07/05/2023 18:52:54
    2023-05-07 18:52:54.288630 INFO HASS: Connected to Home Assistant 2023.5.2
    07/05/2023 18:52:54
    2023-05-07 18:52:54.337711 INFO AppDaemon: App 'hello_world' added
    07/05/2023 18:52:54
    2023-05-07 18:52:54.339849 INFO AppDaemon: App 'nspanel-1' added
    07/05/2023 18:52:54
    2023-05-07 18:52:54.341052 INFO AppDaemon: Found 2 active apps
    07/05/2023 18:52:54
    2023-05-07 18:52:54.342323 INFO AppDaemon: Found 0 inactive apps
    07/05/2023 18:52:54
    2023-05-07 18:52:54.342858 INFO AppDaemon: Found 0 global libraries
    07/05/2023 18:52:54
    2023-05-07 18:52:54.343313 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
    07/05/2023 18:52:54
    2023-05-07 18:52:54.347064 INFO AppDaemon: Running on port 5050
    07/05/2023 18:52:54
    2023-05-07 18:52:54.383309 INFO HASS: Evaluating startup conditions
    07/05/2023 18:52:54
    2023-05-07 18:52:54.390193 INFO HASS: Startup condition met: hass state=RUNNING
    07/05/2023 18:52:54
    2023-05-07 18:52:54.390617 INFO HASS: All startup conditions met
    07/05/2023 18:52:54
    2023-05-07 18:52:54.470171 INFO AppDaemon: Got initial state from namespace default
    07/05/2023 18:52:56
    2023-05-07 18:52:56.358423 INFO AppDaemon: Scheduler running in realtime
    07/05/2023 18:52:56
    2023-05-07 18:52:56.365068 INFO AppDaemon: Adding /conf/apps to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.366091 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.367031 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.368144 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.369317 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.370389 INFO AppDaemon: Adding /conf/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
    07/05/2023 18:52:56
    2023-05-07 18:52:56.396758 INFO AppDaemon: Loading App Module: /conf/apps/hello.py
    07/05/2023 18:52:56
    2023-05-07 18:52:56.432678 INFO AppDaemon: Loading App Module: /conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
    07/05/2023 18:52:56
    2023-05-07 18:52:56.471617 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.473779 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.475886 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.478153 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.480332 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.482524 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.484591 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.486867 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.488881 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.491222 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.493573 WARNING AppDaemon: No app description found for: /conf/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
    07/05/2023 18:52:56
    2023-05-07 18:52:56.495369 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
    07/05/2023 18:52:56
    2023-05-07 18:52:56.499402 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
    07/05/2023 18:52:56
    2023-05-07 18:52:56.504246 INFO AppDaemon: Calling initialize() for hello_world
    07/05/2023 18:52:56
    2023-05-07 18:52:56.609422 INFO hello_world: Hello from AppDaemon
    07/05/2023 18:52:56
    2023-05-07 18:52:56.610681 INFO hello_world: You are now ready to run Apps!
    07/05/2023 18:52:56
    2023-05-07 18:52:56.612551 INFO AppDaemon: Calling initialize() for nspanel-1
    07/05/2023 18:52:56
    2023-05-07 18:52:56.615336 INFO nspanel-1: Starting
    07/05/2023 18:52:56
    2023-05-07 18:52:56.616361 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
    07/05/2023 18:52:56
    2023-05-07 18:52:56.619022 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/nspaneltest/RESULT', 'panelSendTopic': 'cmnd/nspaneltest/CustomSend', 'model': 'us-p'}
    07/05/2023 18:52:56
    2023-05-07 18:52:56.620658 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/nspaneltest/RESULT', 'panelSendTopic': 'cmnd/nspaneltest/CustomSend', 'updateMode': 'auto-notify', 'model': 'us-p', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
    07/05/2023 18:52:56
    2023-05-07 18:52:56.622629 WARNING nspanel-1: ------------------------------------------------------------
    07/05/2023 18:52:56
    2023-05-07 18:52:56.623020 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
    07/05/2023 18:52:56
    2023-05-07 18:52:56.623361 WARNING nspanel-1: ------------------------------------------------------------
    07/05/2023 18:52:56
    2023-05-07 18:52:56.627387 WARNING nspanel-1: Traceback (most recent call last):
    07/05/2023 18:52:56
      File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    07/05/2023 18:52:56
        await utils.run_in_executor(self, init)
    07/05/2023 18:52:56
      File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    07/05/2023 18:52:56
        response = future.result()
    07/05/2023 18:52:56
      File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    07/05/2023 18:52:56
        result = self.fn(*self.args, **self.kwargs)
    07/05/2023 18:52:56
      File "/conf/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    07/05/2023 18:52:56
        apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
    07/05/2023 18:52:56
    AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
    07/05/2023 18:52:56
    07/05/2023 18:52:56
    2023-05-07 18:52:56.627780 WARNING nspanel-1: ------------------------------------------------------------
    07/05/2023 18:52:56
    2023-05-07 18:52:56.629379 INFO AppDaemon: App initialization complete

`

**Comment by joBr99** [comment]
The indentation of your mqtt plugin is wrong MQTT needs to be on the same level HASS is.

**Comment by pbranly** [comment]
Fantastic thanl you very much
Phil
