### ISSUE TITLE
[BUG] apps.yaml error (appdeamon 0.13.0 NSPanel Lovelace UI 4.1.1) Unexpected error running initialize()

### ISSUE THREAD

**Issue by lmbalcao** [joBr99/nspanel-lovelace-ui#900]
### PROBLEM DESCRIPTION
starting appdaemon with only screensaver and apps\CardAlarm, nspanel boots without problem, if i add any other cards i get a error.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide your apps.yaml (or your config):
```
nspanel-cozinha:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/nspanel_cozinha/RESULT"
    panelSendTopic: "cmnd/nspanel_cozinha/CustomSend"
    model: eu
    sleepTimeout: 20
    sleepBrightness:
      - time: "sunrise"
        value: 10
      - time: "sunset + 1:00:00"
        value: 0
    locale: "pt_PT"
    screensaver:
      entities:
        - entity: weather.home
        - entity: weather.home
          type: 0
        - entity: weather.home
          type: 1
        - entity: weather.home
          type: 2
        - entity: delete
        - entity: sensor.cozinha_temperatura
          icon: mdi:home-thermometer-outline
    cards:
      - type: cardGrid
        key: grid1
        title: Aspiração
        entities:
          - entity: script.aspirador_cozinha
            name: Aspirar Cozinha
            icon: mdi:silverware-fork-knife
          - entity:
            name: Aspirar Casa
            icon: mdi:home
          - entity: script.1684501449172
            name: Retornar
            icon: mdi:home-import-outline
          - entity: script.aspirador_localizar
            name: Localizar
      - type: cardAlarm
        title: Alarme
        entity: alarm_control_panel.alarme
      # - type: cardQR
      #   title: Wifi
      #   qrCode: "WIFI:S:mmmmm;T:WPA;P:mmmmm;;"
      #   entities:
      #     - entity: iText.test_ssid
      #       name: mmmmm
      #       icon: mdi:wifi
      #     - entity: iText.test_pw
      #       name:mmmmm
      #       icon: mdi:key
      # - type: cardMedia
      #   title: Coluna
      #   entity: media_player.cozinha_coluna
```
- [ ] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 913.2 kB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.12.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[23:18:20] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-05-20 23:18:24.034742 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-05-20 23:18:24.035084 INFO AppDaemon: Python version is 3.11.3
2023-05-20 23:18:24.035301 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-05-20 23:18:24.035505 INFO AppDaemon: Added log: AppDaemon
2023-05-20 23:18:24.035703 INFO AppDaemon: Added log: Error
2023-05-20 23:18:24.035950 INFO AppDaemon: Added log: Access
2023-05-20 23:18:24.036151 INFO AppDaemon: Added log: Diag
2023-05-20 23:18:24.262551 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-05-20 23:18:24.446074 INFO HASS: HASS Plugin Initializing
2023-05-20 23:18:24.446289 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2023-05-20 23:18:24.446441 INFO HASS: HASS Plugin initialization complete
2023-05-20 23:18:24.446685 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-05-20 23:18:24.553967 INFO MQTT: MQTT Plugin Initializing
2023-05-20 23:18:24.554207 INFO MQTT: Using 'appdaemon/status' as Will Topic
2023-05-20 23:18:24.554349 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2023-05-20 23:18:24.554874 INFO AppDaemon: HTTP is disabled
2023-05-20 23:18:24.567705 INFO HASS: Connected to Home Assistant 2023.5.2
2023-05-20 23:18:24.579133 INFO MQTT: Connected to Broker at URL 192.168.1.101:1883
2023-05-20 23:18:24.592239 INFO AppDaemon: Got initial state from namespace mqtt
2023-05-20 23:18:24.598136 INFO MQTT: MQTT Plugin initialization complete
2023-05-20 23:18:24.607538 INFO AppDaemon: App 'nspanel-cozinha' added
2023-05-20 23:18:24.608428 INFO AppDaemon: Found 1 active apps
2023-05-20 23:18:24.608691 INFO AppDaemon: Found 0 inactive apps
2023-05-20 23:18:24.608973 INFO AppDaemon: Found 0 global libraries
2023-05-20 23:18:24.609193 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-05-20 23:18:24.654203 INFO HASS: Evaluating startup conditions
2023-05-20 23:18:24.665343 INFO HASS: Startup condition met: hass state=RUNNING
2023-05-20 23:18:24.665683 INFO HASS: All startup conditions met
2023-05-20 23:18:24.708735 INFO AppDaemon: Got initial state from namespace default
2023-05-20 23:18:26.614307 INFO AppDaemon: Scheduler running in realtime
2023-05-20 23:18:26.616916 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-05-20 23:18:26.617452 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-05-20 23:18:26.618040 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-05-20 23:18:26.618492 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-05-20 23:18:26.619023 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-05-20 23:18:26.619521 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-05-20 23:18:26.631286 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2023-05-20 23:18:26.632437 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-05-20 23:18:26.815890 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-05-20 23:18:26.816995 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-05-20 23:18:26.818264 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-05-20 23:18:26.819514 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-05-20 23:18:26.820674 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-05-20 23:18:26.821847 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-05-20 23:18:26.823029 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-05-20 23:18:26.824161 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-05-20 23:18:26.825356 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-05-20 23:18:26.826508 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-05-20 23:18:26.827558 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-05-20 23:18:26.828443 INFO AppDaemon: Loading app nspanel-cozinha using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-05-20 23:18:26.830915 INFO AppDaemon: Calling initialize() for nspanel-cozinha
2023-05-20 23:18:26.910129 INFO nspanel-cozinha: Starting
2023-05-20 23:18:26.915881 INFO nspanel-cozinha: Input config: {'panelRecvTopic': 'tele/nspanel_cozinha/RESULT', 'panelSendTopic': 'cmnd/nspanel_cozinha/CustomSend', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': 'sunrise', 'value': 10}, {'time': 'sunset + 1:00:00', 'value': 0}], 'locale': 'pt_PT', 'screensaver': {'entities': [{'entity': 'weather.home'}, {'entity': 'weather.home', 'type': 0}, {'entity': 'weather.home', 'type': 1}, {'entity': 'weather.home', 'type': 2}, {'entity': 'delete'}, {'entity': 'sensor.cozinha_temperatura', 'icon': 'mdi:home-thermometer-outline'}]}, 'cards': [{'type': 'cardGrid', 'key': 'grid1', 'title': 'Aspiração', 'entities': [{'entity': 'script.aspirador_cozinha', 'name': 'Aspirar Cozinha', 'icon': 'mdi:silverware-fork-knife'}, {'entity': None, 'name': 'Aspirar Casa', 'icon': 'mdi:home'}, {'entity': 'script.1684501449172', 'name': 'Retornar', 'icon': 'mdi:home-import-outline'}, {'entity': 'script.aspirador_localizar', 'name': 'Localizar'}]}, {'type': 'cardAlarm', 'title': 'Alarme', 'entity': 'alarm_control_panel.alarme'}]}
2023-05-20 23:18:26.917604 INFO nspanel-cozinha: Loaded config: {'panelRecvTopic': 'tele/nspanel_cozinha/RESULT', 'panelSendTopic': 'cmnd/nspanel_cozinha/CustomSend', 'updateMode': 'auto-notify', 'model': 'eu', 'sleepTimeout': 20, 'sleepBrightness': [{'time': 'sunrise', 'value': 10}, {'time': 'sunset + 1:00:00', 'value': 0}], 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'pt_PT', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardGrid', 'key': 'grid1', 'title': 'Aspiração', 'entities': [{'entity': 'script.aspirador_cozinha', 'name': 'Aspirar Cozinha', 'icon': 'mdi:silverware-fork-knife'}, {'entity': None, 'name': 'Aspirar Casa', 'icon': 'mdi:home'}, {'entity': 'script.1684501449172', 'name': 'Retornar', 'icon': 'mdi:home-import-outline'}, {'entity': 'script.aspirador_localizar', 'name': 'Localizar'}]}, {'type': 'cardAlarm', 'title': 'Alarme', 'entity': 'alarm_control_panel.alarme'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver', 'entities': [{'entity': 'weather.home'}, {'entity': 'weather.home', 'type': 0}, {'entity': 'weather.home', 'type': 1}, {'entity': 'weather.home', 'type': 2}, {'entity': 'delete'}, {'entity': 'sensor.cozinha_temperatura', 'icon': 'mdi:home-thermometer-outline'}]}, 'hiddenCards': []}
2023-05-20 23:18:26.923886 INFO nspanel-cozinha: Sending MQTT Message: pageType~pageStartup
2023-05-20 23:18:26.937726 INFO nspanel-cozinha: gtest123: ['script.aspirador_cozinha', None, 'script.1684501449172', 'script.aspirador_localizar', 'alarm_control_panel.alarme', 'weather.example', 'weather.home', 'weather.home', 'weather.home', 'weather.home', 'delete', 'sensor.cozinha_temperatura']
2023-05-20 23:18:26.938580 WARNING nspanel-cozinha: ------------------------------------------------------------
2023-05-20 23:18:26.938986 WARNING nspanel-cozinha: Unexpected error running initialize() for nspanel-cozinha
2023-05-20 23:18:26.939193 WARNING nspanel-cozinha: ------------------------------------------------------------
2023-05-20 23:18:26.942039 WARNING nspanel-cozinha: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 27, in initialize
    controller = LuiController(cfg, mqttsend.send_mqtt_msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 27, in __init__
    self.register_callbacks()
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 149, in register_callbacks
    items = [x for x in items if not x.startswith(prefixes)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py", line 149, in <listcomp>
    items = [x for x in items if not x.startswith(prefixes)]
                                     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
2023-05-20 23:18:26.942323 WARNING nspanel-cozinha: ------------------------------------------------------------
2023-05-20 23:18:26.945704 INFO AppDaemon: App initialization complete
2023-05-20 23:19:00.951220 INFO nspanel-cozinha: Sending MQTT Message: time~23:19~

```

### TO REPRODUCE
making app.yaml with secreensaver and apps\cardalarm works.
adding apps\cardgrid or cardqr or cardmedia (or all) will prevent the config to be injected in nspanel

### EXPECTED BEHAVIOUR
is expected that nspanel boots with apps.yaml config

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
_Please note here in case you are using ioBroker_

### PANEL / FIRMWARE VERION

```
Program Version | 12.5.0(tasmota32)
-- | --
2023-04-17T08:07:16
2_0_7/4.4.4.20230310
0T01:45:58
5188
102
Software reset CPU
 
 
 
hassio 8 (80%, -60 dBm) 11n
nspanel-cozinha-0284
2001:818:d80b:4400:4617:93ff:fe7c:11c
fe80::4617:93ff:fe7c:11c
44:17:93:7C:01:1C
192.168.1.78
192.168.1.1
255.255.255.0
192.168.1.100
192.168.1.1
 
Enabled
 
192.168.1.101
1883
Disabled
mqttuser
DVES_7C011C
nspanel_cozinha
cmnd/tasmotas/
cmnd/nspanel_cozinha/
cmnd/DVES_7C011C_fb/
Disabled
 
None
 
8126748 (ESP32-D0WD-V3 rev.3)
0x16405E (DOUT)
4096 KB
4096 KB
1525 KB
1856 KB
126.5 KB (frag. 13%)
 
1856 KB
1856 KB (used 82%)
320 KB
```

**Comment by joBr99** [comment]
replace this empty entity with delete

```
          - entity:
            name: Aspirar Casa
```

```
          - entity: delete
            name: Aspirar Casa
```

Updating to 4.1.2 should also fix the issue.
