### ISSUE TITLE
[Help] Waiting for Content

### ISSUE THREAD

**Issue by truzzman** [joBr99/nspanel-lovelace-ui#914]
### PROBLEM DESCRIPTION

I'm seeing the waiting for content message on the Panel and I'm unable to find the configuration issue.

[] I've double checked each step explained in the FAQ:

https://docs.nspanel.pky.eu/faq/#waiting-for-content-this-is-taking-longer-than-usual-on-the-screen

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Provide a screenshot of your tasmota mqtt configuration:

![Immagine 2023-05-31 223712](https://github.com/joBr99/nspanel-lovelace-ui/assets/11472977/824ca7fb-547c-41ef-906a-d3e39a7707b5)

- [x] Provide your appdaemon.yaml: 
```
  appdaemon.yaml here:
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
http:
  url: http://192.168.178.111:5050
admin:
api:
hadashboard:
    MQTT:
      type: mqtt
      namespace: mqtt
      client_id: "appdaemon"
      client_host: 192.168.178.110
      client_port: 1883
      client_user: "emonpi"
      client_password: "same as for other mqtt item"
      client_topics: NONE

```

- [ ] Provide your apps.yaml:
```
  apps.yaml here:
# hello_world:
#   module: hello
#   class: HelloWorld
nspanel-1:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  config:
    panelRecvTopic: "tele/tasmota_nspanel/RESULT"
    panelSendTopic: "cmnd/tasmota_nspanel/CustomSend"
    model: us-l

```
- [ ] Go to Settings>Add-ons>AppDaemon>Log and then, provide the output of the log after restarting the appdaemon container:
```
  Log output here:
ystem: Home Assistant OS 10.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
Looking in links: https://wheels.home-assistant.io/musllinux/
Collecting babel
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 3.9 MB/s eta 0:00:00
Installing collected packages: babel
Successfully installed babel-2.12.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[22:47:46] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-05-31 22:47:51.330816 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-05-31 22:47:51.331215 INFO AppDaemon: Python version is 3.11.3
2023-05-31 22:47:51.331524 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-05-31 22:47:51.331863 INFO AppDaemon: Added log: AppDaemon
2023-05-31 22:47:51.332197 INFO AppDaemon: Added log: Error
2023-05-31 22:47:51.332560 INFO AppDaemon: Added log: Access
2023-05-31 22:47:51.332877 INFO AppDaemon: Added log: Diag
2023-05-31 22:47:51.648343 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-05-31 22:47:51.917403 INFO HASS: HASS Plugin Initializing
2023-05-31 22:47:51.917658 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2023-05-31 22:47:51.917851 INFO HASS: HASS Plugin initialization complete
2023-05-31 22:47:51.918487 INFO AppDaemon: Initializing HTTP
2023-05-31 22:47:51.919077 INFO AppDaemon: Using 'ws' for event stream
2023-05-31 22:47:51.929139 INFO AppDaemon: Starting API
2023-05-31 22:47:51.932932 INFO AppDaemon: Starting Admin Interface
2023-05-31 22:47:51.933523 INFO AppDaemon: Starting Dashboards
2023-05-31 22:47:51.959457 INFO HASS: Connected to Home Assistant 2023.5.4
2023-05-31 22:47:51.988978 INFO AppDaemon: App 'nspanel-1' added
2023-05-31 22:47:52.046799 INFO AppDaemon: Found 1 active apps
2023-05-31 22:47:52.047428 INFO AppDaemon: Found 0 inactive apps
2023-05-31 22:47:52.047919 INFO AppDaemon: Found 0 global libraries
2023-05-31 22:47:52.048450 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-05-31 22:47:52.049977 INFO AppDaemon: Running on port 5050
2023-05-31 22:47:52.106916 INFO HASS: Evaluating startup conditions
2023-05-31 22:47:52.125656 INFO HASS: Startup condition met: hass state=RUNNING
2023-05-31 22:47:52.126214 INFO HASS: All startup conditions met
2023-05-31 22:47:52.162469 INFO AppDaemon: Got initial state from namespace default
2023-05-31 22:47:54.063643 INFO AppDaemon: Scheduler running in realtime
2023-05-31 22:47:54.071548 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-05-31 22:47:54.072744 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path
2023-05-31 22:47:54.074069 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend to module import path
2023-05-31 22:47:54.075498 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations to module import path
2023-05-31 22:47:54.076931 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/frontend to module import path
2023-05-31 22:47:54.078546 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/translations/backend to module import path
2023-05-31 22:47:54.101559 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2023-05-31 22:47:54.104854 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py
2023-05-31 22:47:54.402203 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/apis.py - ignoring
2023-05-31 22:47:54.403845 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icon_mapping.py - ignoring
2023-05-31 22:47:54.405401 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/mqtt.py - ignoring
2023-05-31 22:47:54.406626 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/controller.py - ignoring
2023-05-31 22:47:54.407958 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/config.py - ignoring
2023-05-31 22:47:54.409687 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/icons.py - ignoring
2023-05-31 22:47:54.411001 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/helper.py - ignoring
2023-05-31 22:47:54.412281 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/localization.py - ignoring
2023-05-31 22:47:54.413718 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/updater.py - ignoring
2023-05-31 22:47:54.415375 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/theme.py - ignoring
2023-05-31 22:47:54.416800 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/nspanel-lovelace-ui/luibackend/pages.py - ignoring
2023-05-31 22:47:54.417900 INFO AppDaemon: Loading app nspanel-1 using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui
2023-05-31 22:47:54.420456 INFO AppDaemon: Calling initialize() for nspanel-1
2023-05-31 22:47:54.522211 INFO nspanel-1: Starting
2023-05-31 22:47:54.523749 WARNING AppDaemon: Unknown Plugin Configuration in get_plugin_api()
2023-05-31 22:47:54.527150 INFO nspanel-1: Input config: {'panelRecvTopic': 'tele/tasmota_nspanel/RESULT', 'panelSendTopic': 'cmnd/tasmota_nspanel/CustomSend', 'model': 'us-l'}
2023-05-31 22:47:54.529500 INFO nspanel-1: Loaded config: {'panelRecvTopic': 'tele/tasmota_nspanel/RESULT', 'panelSendTopic': 'cmnd/tasmota_nspanel/CustomSend', 'updateMode': 'auto-notify', 'model': 'us-l', 'sleepTimeout': 20, 'sleepBrightness': 20, 'screenBrightness': 100, 'defaultBackgroundColor': 'ha-dark', 'sleepTracking': None, 'sleepTrackingZones': ['not_home', 'off'], 'sleepOverride': None, 'locale': 'en_US', 'timeFormat': '%H:%M', 'dateFormatBabel': 'full', 'dateAdditionalTemplate': '', 'timeAdditionalTemplate': '', 'dateFormat': '%A, %d. %B %Y', 'cards': [{'type': 'cardEntities', 'entities': [{'entity': 'iText.', 'name': 'MQTT Config successful', 'icon': 'mdi:check', 'color:': [0, 255, 0]}, {'entity': 'iText.', 'name': 'Continue adding', 'icon': 'mdi:arrow-right-bold'}, {'entity': 'iText.', 'name': 'cards to your', 'icon': 'mdi:card'}, {'entity': 'iText.', 'name': 'apps.yaml', 'icon': 'mdi:cog'}], 'title': 'Setup successful'}], 'screensaver': {'type': 'screensaver', 'entity': 'weather.example', 'weatherUnit': 'celsius', 'forecastSkip': 0, 'weatherOverrideForecast1': None, 'weatherOverrideForecast2': None, 'weatherOverrideForecast3': None, 'weatherOverrideForecast4': None, 'doubleTapToUnlock': False, 'alternativeLayout': False, 'defaultCard': None, 'key': 'screensaver'}, 'hiddenCards': []}
2023-05-31 22:47:54.531519 WARNING nspanel-1: ------------------------------------------------------------
2023-05-31 22:47:54.532211 WARNING nspanel-1: Unexpected error running initialize() for nspanel-1
2023-05-31 22:47:54.532634 WARNING nspanel-1: ------------------------------------------------------------
2023-05-31 22:47:54.537671 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 25, in initialize
    apis.mqtt_api.mqtt_publish(topic_send.replace("CustomSend", "GetDriverVersion"), "x")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mqtt_publish'
2023-05-31 22:47:54.539048 WARNING nspanel-1: ------------------------------------------------------------
2023-05-31 22:47:54.540617 INFO AppDaemon: App initialization complete

```

### ADDITIONAL INFORMATION

_Add information about your setup here, if any. (For example docker version of AppDaemon instead of the HomeAssistant Add-on)_

**Comment by truzzman** [comment]
Perfect now is working! Thanks a lot

**Comment by truzzman** [comment]
Great, thanks a lot for your ultra fast help. Best regards
Stefano
