### ISSUE TITLE
[BUG] Error calling service on vaccum

### ISSUE THREAD

**Issue by blaurence** [joBr99/nspanel-lovelace-ui#982]
### PROBLEM DESCRIPTION
Error calling service on vaccum (But turn on light is ok)

### REQUESTED INFORMATION

Apps.yaml : 
```
      - type: cardGrid
        title: Aspirateur (Fonctionne pas)
        key: vaccum
        entities:
          - entity: service.vacuum.start
            data:
              entity_id: vacuum.robot_aspirateur
              color_name: "green"
            name: Démarrrer
            icon: "mdi:play"
          - entity: service.vaccum.pause
            data:
              entity_id: vacuum.robot_aspirateur
            color_name: "green"
            name: Pause
            icon: "mdi:play-pause"
          - entity: service.vacuum.return_to_base
            data:
              entity_id: vacuum.robot_aspirateur
              color_name: "green"
            name: Retour Base
            icon: "mdi:stop"

          - entity: service.light.turn_on
            data:
              entity_id: light.bureau
              color_name: "green"


```
Log output :
```
2023-09-30 15:14:21.106658 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_topic/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.qsZgFl67aU,button"}'}
2023-09-30 15:14:21.108493 INFO nspanel-1: Received Message from Screen: event,buttonPress2,uuid.qsZgFl67aU,button
2023-09-30 15:14:21.110034 INFO nspanel-1: Button Press Event; entity_id: uuid.qsZgFl67aU; button_type: button; value: None
2023-09-30 15:14:21.125449 WARNING HASS: Error calling Home Assistant service default/vacuum/start
2023-09-30 15:14:21.126283 WARNING HASS: Code: 400, error: 400: Bad Request
2023-09-30 15:14:22.109709 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_topic/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.OJEy2Cr9KD,button"}'}
2023-09-30 15:14:22.111276 INFO nspanel-1: Received Message from Screen: event,buttonPress2,uuid.OJEy2Cr9KD,button
2023-09-30 15:14:22.112145 INFO nspanel-1: Button Press Event; entity_id: uuid.OJEy2Cr9KD; button_type: button; value: None
2023-09-30 15:14:22.113253 WARNING nspanel-1: ------------------------------------------------------------
2023-09-30 15:14:22.113447 WARNING nspanel-1: Unexpected error in worker for App nspanel-1:
2023-09-30 15:14:22.113586 WARNING nspanel-1: Worker Ags: {'id': 'aba883ba3d884bfdb44ef11eac2bfdae', 'name': 'nspanel-1', 'objectid': '1766ea7364da4e359c7333d458f29add', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method LuiMqttListener.mqtt_event_callback of <luibackend.mqtt.LuiMqttListener object at 0x7f7ca63c48e0>>, 'data': {'topic': 'tele/nspanel_topic/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.OJEy2Cr9KD,button"}'}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'topic': 'tele/nspanel_topic/RESULT', '__thread_id': 'thread-1'}}
2023-09-30 15:14:22.113700 WARNING nspanel-1: ------------------------------------------------------------
2023-09-30 15:14:22.114332 WARNING nspanel-1: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/conf/apps/nspanel-lovelace-ui/luibackend/mqtt.py", line 57, in mqtt_event_callback
    self._controller.button_press(entity_id, btype, value)
  File "/conf/apps/nspanel-lovelace-ui/luibackend/controller.py", line 335, in button_press
    apis.ha_api.call_service(entity_id.replace('service.', '', 1).replace('.','/', 1), **entity_config.data)
  File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 231, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 313, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/appdaemon/adapi.py", line 1762, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/local/lib/python3.10/site-packages/appdaemon/services.py", line 166, in call_service
    raise DomainException(f"Unknown domain ({namespace}/{domain}) in call_service from {name}")
appdaemon.exceptions.DomainException: Unknown domain (default/vaccum) in call_service from nspanel-1

2023-09-30 15:14:22.114540 WARNING nspanel-1: ------------------------------------------------------------
2023-09-30 15:14:23.886424 INFO nspanel-1: MQTT callback for: {'topic': 'tele/nspanel_topic/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,buttonPress2,uuid.XN3blO0YE4,button"}'}
2023-09-30 15:14:23.887772 INFO nspanel-1: Received Message from Screen: event,buttonPress2,uuid.XN3blO0YE4,button
2023-09-30 15:14:23.889111 INFO nspanel-1: Button Press Event; entity_id: uuid.XN3blO0YE4; button_type: button; value: None
2023-09-30 15:14:23.903963 WARNING HASS: Error calling Home Assistant service default/vacuum/return_to_base
2023-09-30 15:14:23.904606 WARNING HASS: Code: 400, error: 400: Bad Request
```

### TO REPRODUCE
Copy/Paste button.

### EXPECTED BEHAVIOUR
Robot pause

**Comment by joBr99** [comment]
For just starting/stopping you can use the vacuum as entity:

```
          - entity: vacuum.valetudo_dustin
```

For calling it as a service you have to remove color_name, as this is only valid for lights.

```
          - entity: service.vacuum.start
            data:
              entity_id: vacuum.valetudo_dustin
              #color_name: "green"
            name: Démarrrer
            icon: "mdi:play"
```

**Comment by blaurence** [comment]
My bad, thank you.
